### PR TITLE
Refactored threescale external resource metric creation

### PR DESCRIPTION
**Pull request by obrienrobert**
## Description
https://issues.redhat.com/browse/INTLY-6490

This PR addresses 2 issues:

1. When installing RHMI using external AWS resources resources, the Threescale Postgres/Redis alerts would trigger initially, and then resolve when the resources were in an available state. This PR refactors the existing Threescale alert creation flow to ensure that the alerts are created only when the resources are in an available state.

threescale_alerts

2. AWS Postgres and Redis alerts were noticed to be firing continuously, on what looked to be every hour. Any AWS resource related Prometheus alerts are now created with `for = '5m'`.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Verification
- Using this branch, run an install using external Postgres/Redis AWS resources
- Ensure the Postgres/Redis Threescale alerts are created only once the accompanying AWS resources are in an available state, and that they are **not** firing.
- Verify that the alerts are not firing every hour.

### CODE REVIEW

**Comment by david-martin** [comment]
/approve
This change makes sense.
Needs an lgtm from someone familiar with the alerts. @ciaranRoche can you help with that?

**Comment by ciaranRoche** [comment]
@david-martin @obrienrobert Just looking at these changes, should we be alerting during installation?  I am just thinking in the case a resource provision fails, the RHMI CR will just read `awaiting components` and we will have no alert to capture this failure from the aws resource provisioning side. What do you think?

**Comment by david-martin** [comment]
> we will have no alert to capture this failure from the aws resource provisioning side.

Agreed that there is a gap here.
I believe this gap can be filled separately by a dual approach:
- alerting on the RHMI CR if it isn't 'Ready' within a certain timeframe
- exposing metrics from CRO related to calls to AWS (e.g. http status & response times) and alerting if there are failures

I'm planning on writing up some enhancements related to this soon

**Pull request merged**
