### PR TITLE
removed a19 test case

### PR DESCRIPTION
**Pull request by pawelpaszki**
# Description
removed a19 test case

### CODE REVIEW

**Comment by pawelpaszki** [comment]
@aidenkeating - am I right in saying that this test case is obsolete?

**Comment by aidenkeating** [comment]
@pawelpaszki Is the reason this is obsolete because we're now using `/23` by default in the test cluster pipeline? If so, and we're testing against /23 clusters, then yes this is obsolete.

**Comment by pawelpaszki** [comment]
@aidenkeating - that's correct

**Comment by tonyxrmdavidson** [comment]
lgtm

**Pull request merged**
