### PR TITLE
Updating CPU requests and limits based on SRE report

### PR DESCRIPTION
**Pull request by matskiv**
# Description
Follow up on CPU throttling alerts that were [reported by SRE-P](https://app.slack.com/client/T027F3GAJ/CJCAUV38A/thread/CJCAUV38A-1592855711.317200)
cc @philbrookes @david-martin @grdryn 

JIRA: https://issues.redhat.com/browse/INTLY-8790 

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by david-martin** [comment]
@philbrookes can we run this change in a cluster for some time & see if the alert fires?

**Comment by philbrookes** [comment]
@maleck13 would it be possible to get this running on your long lived cluster until next week, maybe?

**Pull request merged**
