### PR TITLE
bump cro to v0.15.2

### PR DESCRIPTION
**Pull request by aidenkeating**
cro version bump to v0.15.2 (upgrade from v0.14.0)

ensure upgrade testing is performed on a cluster with settings like
```
Machine CIDR: 10.11.132.0/23
Service CIDR: 10.11.0.0/18
Pod CIDR: 10.11.64.0/18
Host Prefix: 23
```

### CODE REVIEW

**Comment by philbrookes** [comment]
those failure errors look pretty strange, if there is some kind of flake we can log here, please add it to https://issues.redhat.com/browse/INTLY-7197

**Comment by aidenkeating** [comment]
@philbrookes If this run fails I may redo this commit instead of cherry picking it. I don't see anything obvious in the commit, but just in case

**Comment by philbrookes** [comment]
@aidenkeating sure thing, the errors don't look like they're related to the work

**Comment by philbrookes** [comment]
/override ci/prow/e2e 
already passed earlier

**Pull request merged**
