### PR TITLE
[MGDAPI-2580] fix: upgrade not completing for n+1 when n+2 version available

### PR DESCRIPTION
**Pull request by KevFan**
# Issue link

https://issues.redhat.com/browse/MGDAPI-2580

# What

When version n is installed, and service affecting version n+1 is made available, olm will create an install plan for upgrade to version n+1. Now if version n+2 is made available and the install plan for n+1 is approved, there is a cyclical loop in this scenario preventing n+1 upgrade from completing successfully.

What happens is that when service affecting version n+2 if available, the `toVersion` in RHMI CR is reset by the subscription controller and this causes the CR to be stale when the installation controller updates the RHMI CR status.

# Verification steps

* Checkout this branch
* Configure cluster for OLM install for RHOAM 1.14.0
```
export INSTALLATION_TYPE=managed-api
make cluster/prepare/local
oc process -p INDEX_IMAGE=quay.io/kevfan/managed-api-service-index:1.14.0  -f ./config/olm/catalog-source-template.yml | oc apply -f - -n openshift-marketplace
```
* Go to operator hub and install RHOAM
* Deploy RHMI Cr to trigger olm install
```
oc project redhat-rhoam-operator
make deploy/integreatly-rhmi-cr.yml
```
* Wait for RHOAM to complete intallation
```
watch "oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq '.status.stage'"
```
* Once installed, patch catalog source with index for 1.14.1 upgrade
```
oc patch catalogsources rhmi-operators  -n openshift-marketplace  --type=json -p='[{"op": "replace", "path": "/spec/image", "value": "quay.io/kevfan/managed-api-service-index:1.14.1"}]'
```
* Verify install plan for 1.14.1 is created
```
 oc get installplans -n redhat-rhoam-operator 
```
* Patch catalog source with index for 1.15.0 upgrade
```
oc patch catalogsources rhmi-operators  -n openshift-marketplace  --type=json -p='[{"op": "replace", "path": "/spec/image", "value": "quay.io/kevfan/managed-api-service-index:1.15.0"}]'
```
* Approve install plan for 1.14.1 upgrade
  * NOTE: Install plan may be constantly deleted and re-created due to https://issues.redhat.com/browse/MGDAPI-3091
* Verify upgrade completes successfully 
```
watch "oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq '.status.version'"
```
* Verify install plan for 1.15.0 is created
```
 oc get installplans -n redhat-rhoam-operator 
```
* Approve install plan for 1.15.0 upgrade
* Verify upgrade completes successfully 
```
watch "oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq '.status.version'"
```

### CODE REVIEW

**Comment by psturc** [comment]
I verified the scenario described in this PR. Worked as expected.

@KevFan did you have a chance to verify the scenario described in [this PR](https://github.com/integr8ly/integreatly-operator/pull/1821#issue-897419424) with your code changes?

**Comment by KevFan** [comment]
> I verified the scenario described in this PR. Worked as expected.
> 
> @KevFan did you have a chance to verify the scenario described in [this PR](https://github.com/integr8ly/integreatly-operator/pull/1821#issue-897419424) with your code changes?

Did try, but haven't got that scenario to work before :see_no_evil:

**Comment by psturc** [comment]
@KevFan thanks. Any ideas what should we do about that - is it worth to create a ticket to investigate whether that scenario works and potentially create a fix for it?

**Comment by KevFan** [comment]
> @KevFan thanks. Any ideas what should we do about that - is it worth to create a ticket to investigate whether that scenario works and potentially create a fix for it?

Yes, I think so. I hit into this issue when trying to verify that was blocking me verifying the scenario :thinking: 
* https://issues.redhat.com/browse/MGDAPI-3084

**Pull request merged**
