### PR TITLE
MGDAPI-3257 - update keycloak-client

### PR DESCRIPTION
**Pull request by adam-cattermole**
# Issue link
Jira: [MGDAPI-3257](https://issues.redhat.com/browse/MGDAPI-3257)

# What
Update keycloak-client version to latest commit (Go update to 1.17).

# Verification steps
Unit and e2e tests are sufficient

### CODE REVIEW

**Comment by makslion** [comment]
from the [logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/integr8ly_integreatly-operator/2457/pull-ci-integr8ly-integreatly-operator-master-rhoam-e2e/1489187238423040000/artifacts/rhoam-e2e/test/build-log.txt) of e2e test - keycloak seems to be working fine and passing tests. Change looks good 

/lgtm

**Comment by adam-cattermole** [comment]
Released new version of keycloak-client to pull v0.1.7 - updated PR with this version and added in products.yaml.

/unhold

**Comment by makslion** [comment]
The merge blocker is gone. Still

/lgtm

**Pull request merged**
