### PR TITLE
Filter the command for ocm get clusters to only include managed/SRE

### PR DESCRIPTION
**Pull request by ciaran-byrne**
# Description
Added parameter on the 'ocm get' command for clusters, to filter by managed clusters only, otherwise all of the clusters in the world are included

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [ ] Verified independently on a cluster by reviewer (Alan Moran)

### CODE REVIEW

**Comment by ciaran-byrne** [comment]
Sanity checked in prod, of my own organisation where there is a single cluster; adding the parameter of 'true' gives a single (expected) result :
```
$ ocm get /api/clusters_mgmt/v1/clusters/ --parameter "search=managed='true'"
{
  "kind": "ClusterList",
  "page": 1,
  "size": 1,
  "total": 1,
  "items": [
    {
      "kind": "Cluster",
      "id": "1cqtmq0794i9ndsl5mmucsdbh255vcho",
      "href": "/api/clusters_mgmt/v1/clusters/1cqtmq0794i9ndsl5mmucsdbh255vcho",
      "name": "rhmi-eng-long-lived",
      "external_id": "4e6031d8-e7d2-4654-aaa4-7ad7693b6d17",
      "infra_id": "rhmi-eng-long-l-ldq8v",

```
and switching to 'false' returns zero clusters (expected)
$ ocm get /api/clusters_mgmt/v1/clusters/ --parameter "search=managed='false'"
```
{
  "kind": "ClusterList",
  "page": 0,
  "size": 0,
  "total": 0,
  "items": []
}
```

**Comment by matskiv** [comment]
I tested this in our ENG staging account, works as expected.

**Pull request merged**
