### PR TITLE
Enable to use self-signed certs

### PR DESCRIPTION
**Pull request by jjaferson**
Enables to use self-signed certs on managed installations

### CODE REVIEW

**Comment by jjaferson** [comment]
FYI: Waiting for a response from the service now ticket https://redhat.service-now.com/help?id=rh_ticket&table=incident&sys_id=a8aea5dddbfa4090ad88c170ba96194c

**Comment by philbrookes** [comment]
I think this PR should be closed now.

**Comment by david-martin** [comment]
@jjaferson @philbrookes Given that production clusters will have valid certs, I don't think we should change the default value in the auto-created CR (At least not for prod builds).
For stage build, I wonder if there's a better way by passing in some value from the selectorsyncset, or detecting automatically from within the operator.

**Pull request closed without merging**
