### PR TITLE
INTLY-8421 Delete alerts during uninstall

### PR DESCRIPTION
**Pull request by sergioifg94**
# Description

Refactor the alert reconciliation logic for all the products, and add logic
to delete the alerts if the RHMI instanced is marked for deletion.

## Verification steps

In order to verify this PR, follow these steps:

1. Install RHMI on a cluster
2. Once installation is complete, verify that the *alerts have been created
3. Uninstall RHMI (delete the RHMI CR)
4. Verify that the *alerts are deleted

\* The following is a table with the alerts reconciled for each namespace:
| Product | Namespace | Alerts |
| ---------- | ---------------- | -------- |
| AMQ Online | `redhat-rhmi-amq-online` | `rhmi-amq-online-slo`, `ksm-endpoint-alerts`, `ksm-amqonline-alerts` |
| Apicurito | `redhat-rhmi-apicurito` | `ksm-apicurito-alerts`, `ksm-endpoint-alerts` |
| Apicurito | `redhat-rhmi-apicurito-operator` | `ksm-endpoint-alerts` |
| Cloud Resources Operator | `redhat-rhmi-cloud-resources-operator` | `ksm-endpoint-alerts` |
| CodeReady | `redhat-rhmi-codeready-workspaces` | `ksm-endpoint-alerts`, `ksm-codeready-alerts` |
| CodeReady | `redhat-rhmi-codeready-workspaces-operator` | `ksm-endpoint-alerts` |
| Fuse | `redhat-rhmi-fuse` | `ksm-endpoint-alert`, `ksm-fuse-online-alerts` |
| Fuse | `redhat-rhmi-fuse-operator` | `ksm-endpoint-alerts` |
| Monitoring | `redhat-rhmi-middleware-monitoring-operator` | `backup-monitoring-alerts`, `ksm-alerts`, `ksm-monitoring-alerts`, `ksm-endpoint-alerts` |
| SSO | `redhat-rhmi-rhsso` | `ksm-endpoint-alerts` |
| SSO | `redhat-rhmi-rhsso-operator` | `ksm-endpoint-alerts` |
| User SSO | `redhat-rhmi-user-sso` | `ksm-endpoint-alerts` |
| User SSO | `redhat-rhmi-user-sso-operator` | `ksm-endpoint-alerts` |
| Solution Explorer | `redhat-rhmi-solution-explorer` | `ksm-endpoint-alerts`, ``ksm-solution-explorer-alerts` |
| Solution Explorer | `redhat-rhmi-solution-explorer-operator` | `ksm-endpoint-alerts` |
| 3scale | `redhat-rhmi-3scale` | `kms-endpoint-alerts`, `ksm-3scale-alerts` |
| 3scale | `redhat-rhmi-3scale-operator` | `ksm-endpoint-alerts` |
| UPS | `redhat-rhmi-ups` | `ksm-endpoint-alerts` |
| UPS | `redhat-rhmi-ups-operator` | `ksm-endpoint-alerts` |

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by MStokluska** [comment]
I have verified the functionality and it works as expected, alarms are created correctly and deleted without firing alarms when RHMI CR is deleted. Good job! To me, it looks good to merge!

**Comment by sergioifg94** [comment]
/hold
Blocked by [INTLY-8360](https://issues.redhat.com/browse/INTLY-8360)

**Comment by sergioifg94** [comment]
/unhold
Rebased from master

**Pull request merged**
