### PR TITLE
Add script to patch the csv with dev image and rhmi cr useClusterStorage during addon flow

### PR DESCRIPTION
**Pull request by austincunningham**
# Description

helper script that  during addon flow
- patches csv with a developer image 
- patches rhmi cr with useClusterStorage

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Verification
- build/push a development image e.g.
```bash
ORG=austincunningham OLM_TYPE=managed-api-service INSTALLATION_TYPE=managed-api make image/build
ORG=austincunningham OLM_TYPE=managed-api-service INSTALLATION_TYPE=managed-api make image/push
```
- export the vars of the script e.g.
```bash
export VERSION=v1.6.0
export ADDON_VERSION=v1.6.0
export ORG=austincunningham
```
- run the script (need to be logged in to oc for the cluster)
- Install RHOAM via the addon flow
```bash
./patch-image-csv.sh
clusterserviceversion.operators.coreos.com/managed-api-service.v1.6.0 patched
clusterserviceversion.operators.coreos.com/managed-api-service.v1.6.0 patched
Verificaton the CSV has been patched :
    containerImage: quay.io/austincunningham/managed-api-service:v1.6.0
                image: quay.io/austincunningham/managed-api-service:v1.6.0
 
Patching the RHMI CR when its created with useClusterStorage
rhmi.integreatly.org/rhoam patched
Verification USE_CLUSTER_STORAGE is set :
        f:useClusterStorage: {}
  useClusterStorage: "true"

```

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by MStokluska** [comment]
@austincunningham this is a great idea! I just wonder, would it be possible to make the script check for the presence of the csv and if present patch it? 
So the flow would be:
- trigger the script
- click on install addon
- the script reports completed

The reason for this is that I've hit some timing issues, this has to be run after the install is pressed, but before the operator pod is created. Unless? The operator pod is re-deployed after patching the csv? But I don't think this is the case.

**Comment by austincunningham** [comment]
> would it be possible to make the script check for the presence of the csv and if present patch it?
> So the flow would be:
> 
> * trigger the script
> * click on install addon
> * the script patches csv and reports completed

@MStokluska Yes it is possible , could also do the same for patching the rhmi CR, although may need an extra var for UseClusterStorage

**Comment by austincunningham** [comment]
@MStokluska updated the pr with your suggestions, have verified and works as expected.

**Comment by jackdelahunt** [comment]
- Ran the script with variables set
- Installed RHOAM via addon
- The addon used the image specified 
- Working as expected

/lgtm

**Comment by jackdelahunt** [comment]
> * Ran the script with variables set
> * Installed RHOAM via addon
> * The addon used the image specified
> * Working as expected
> 
> /lgtm

/lgtm

**Pull request merged**
