### PR TITLE
rhsso-next-7.5.0-patch-ownerref-admincredentials

### PR DESCRIPTION
**Pull request by austincunningham**
# Issue link
https://issues.redhat.com/browse/MGDAPI-2555

# What
patches credentials-rhsso and credentials-rhssouser with an ownerref from the Keycloak cr
Required for installation to complete with rhsso 7.5 images

# Verification steps
- Install the operator locally
- make sure that rhsso and user-sso installations complete and there routes are available

### CODE REVIEW

**Comment by KevFan** [comment]
Getting the following error when running the operator:
```
2021-09-23T09:14:03.091+0100    DEBUG   controller-runtime.manager.events       Warning {"object": {"kind":"RHMI","namespace":"redhat-rhoam-operator","name":"rhoam","uid":"07ad8fda-d464-4c0b-b429-995e75c1b1da","apiVersion":"integreatly.org/v1alpha1","resourceVersion":"391709"}, "reason": "ProcessingError", "message": "Failed to reconcile components:\nsecrets \"credential-rhsso\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```

Should this be run with the RHSSO 7.5 manifests ? :thinking:

**Comment by KevFan** [comment]
* Verified installation completes
* Verified ownerReference added to secrets
* Verified routes available
Screenshot from 2021-09-23 12-34-21

/lgtm

**Comment by austincunningham** [comment]
@pmccarthy as these prow is not running on the branch I am merging to, these prow jobs will never pass on this pr, can you force merge this PR to rhsso-next-7.5.0

**Comment by austincunningham** [comment]
@pmccarthy and @KevFan pushing a new commit removed the failing prow tests only checking tide now , need an `/lgtm` and `/approve` again

**Pull request merged**
