### PR TITLE
addressing feedback

### PR DESCRIPTION
**Pull request by laurafitzgerald**
various fixes around variable naming/usage, imports, comments and tes…t improvement

# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by matskiv** [comment]
I checked things that I commented on in original PR and those LGTM. Thanks for addressing them.

**Comment by KevFan** [comment]
Resolves comments made on the original PR so /lgtm :+1: 

`make test-cases/fix` would need to run to fix the prow test on test case formatting though :thinking:

**Comment by laurafitzgerald** [comment]
Thanks @KevFan @matskiv I've ran the command to fix the formatting. That's the only change in the force push.

**Pull request merged**
