### PR TITLE
Grafanadashboard resource templates added

### PR DESCRIPTION
**Pull request by obrienrobert**
## Additional Information

https://issues.jboss.org/browse/INTLY-4022

## Description

Ports all resources (below) from the create_grafanadashboards.yml file in the installer:

```
- endpointsdetailed.yml
- endpointsreport.yml
- endpointssummary.yml
- resources-by-namespace.yml
- resources-by-pod.yml
- cluster-resources.yml
```

## Verification

- Authenticate with Openshift
- Create the `integreatly` namespace
- Create the secrets for preflight checks:

```
# Execute from integreatly-operator dir
oc process -f ./deploy/s3-secrets.yaml -p INSTALLATION_NAMESPACE=integreatly -p AWS_ACCESS_KEY_ID=xxxx -p AWS_SECRET_ACCESS_KEY=xxxx -p AWS_BUCKET=xxxx-test -p AWS_REGION=eu-central-1 | oc create -f -
oc create secret generic github-oauth-secret --from-literal=clientId=xxxx --from-literal=secret=xxx -n integreatly
```

- Visit OperatorHub in the Openshift UI, search for integreatly and install it into the `integreatly` namespace

- Scale the replicas to 0 in the operator deployment in the `integreatly` namespace

- Run the operator locally: `operator-sdk up local --namespace "integreatly" --operator-flags "--products=monitoring"`

- Create instance of the installation CR, changing both the `masterURL` and `routingSubdomain` to suit your envrionment:

```
apiVersion: integreatly.org/v1alpha1
kind: Installation
metadata:
  name: example-installation
spec:
  type: workshop
  namespacePrefix: integreatly-
  routingSubdomain: apps.com
  masterUrl: https://someurl.apps.com
  selfSignedCerts: true
```

- Wait for reconcile of the monitoring product to complete

- In the `integreatly-middleware-monitoring` namespace, navigate to the grafana-dashboard: `Networking -> Routes -> grafana-route`

- Verify that a corresponding dashboard has been created for each of the resource templates listed in the description. At present, they will not display any data.

### CODE REVIEW

**Comment by davidkirwan** [comment]
```
INFO[0180] Reconciling the monitoring template endpointsdetailed was successful 
INFO[0180] Reconciling the monitoring template endpointsreport was successful 
INFO[0180] Reconciling the monitoring template endpointssummary was successful 
INFO[0181] Reconciling the monitoring template resources-by-namespace was successful 
INFO[0181] Reconciling the monitoring template resources-by-pod was successful 
INFO[0181] Reconciling the monitoring template cluster-resources was successful
```

Screenshot from 2019-11-13 13-35-47
Screenshot from 2019-11-13 13-36-28

**Comment by damienomurchu** [comment]
Changes look good, and have verified them on an OSD4 dev cluster. As we're including these templates as part of the integreatly-operator is there a proposed method to test them and ensure they've been included properly in the installation?

**Comment by davidkirwan** [comment]
@damienomurchu not yet, next batch of templates will include configurations for some of the services which will make it easy to verify the install to working dashboards etc. But at the moment it should be enough that they are appearing in Grafana etc.

like here:
Screenshot from 2019-11-13 13-36-28

**Comment by damienomurchu** [comment]
@davidkirwan thanks - lets chat on g-chat and keep the discussion in one place :)

**Pull request merged**
