### PR TITLE
Update n02-measure-downtime-during-rhmi-upgrade.md

### PR DESCRIPTION
**Pull request by wei-lee**
# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by b1zzu** [comment]
/lgtm 

But we have to update this document:
https://github.com/RHCloudServices/integreatly-help/blob/master/guides/manual-release-tests-selection.md#pre-upgrade-work
and remove the H21 from the Pre-upgrade Work section

we should also update the N04 and remove the H21 requirements, and update the H21 and remove the note about upgrades.. or more generic what should we do with the H21?
N04:https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/upgrade/n04-verify-customer-config-reconcile-upgrade-logic-and-trigger-t.md
H21: https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/products/h21-verify-all-products-using-the-workloadwebapp.md

**Comment by wei-lee** [comment]
@b1zzu I think we should remove H21. Looks like N02 is covering the upgrade already.

**Comment by b1zzu** [comment]
@wei-lee the idea of H21 is that it could be used also for a rhmi installation to easily test 3scale, sso, and amq, so I think is good to keep it, but we should clean it from all upgrade info

**Pull request merged**
