### PR TITLE
INTLY-7435 - e2e test verify 3Scale user promotion does not revert

### PR DESCRIPTION
**Pull request by KevFan**
# Description

Rebased off from https://github.com/integr8ly/integreatly-operator/pull/717

Automated e2e test for user promotion in 3scale does not get reverted by the operator

Jira:
* https://issues.redhat.com/browse/INTLY-7435

## Type of change

- [x] Test Automation

## Checklist
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by KevFan** [comment]
Successful run - [1](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/pr-logs/pull/integr8ly_integreatly-operator/803/pull-ci-integr8ly-integreatly-operator-master-e2e/3545)

**Comment by KevFan** [comment]
Fail due to throttling
/test e2e

**Comment by KevFan** [comment]
Successful run [2](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/pr-logs/pull/integr8ly_integreatly-operator/803/pull-ci-integr8ly-integreatly-operator-master-e2e/3576)
/test e2e

**Comment by KevFan** [comment]
Successful run - [3](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/integr8ly_integreatly-operator/803/pull-ci-integr8ly-integreatly-operator-master-e2e/3582)
Looks to be stable, failed runs were due to prow rather than the tests themselves

**Comment by damienomurchu** [comment]
/lgtm 
Code looks good. I wonder if we need this checked on each PR given the additional time waiting for the reconcile though

**Comment by KevFan** [comment]
> /lgtm
> Code looks good. I wonder if we need this checked on each PR given the additional time waiting for the reconcile though

I think it should be fine considering the timeouts for e2e test and functional tests, though I'm not sure did  the other tests add much wait time :thinking: :
https://github.com/integr8ly/integreatly-operator/blob/4aee81a07c15ee644c570b154045b1c22648fe07/Makefile#L152
https://github.com/integr8ly/integreatly-operator/blob/4aee81a07c15ee644c570b154045b1c22648fe07/Makefile#L162

Can bump the timeout if we do see issues from this test

**Comment by matskiv** [comment]
The time it takes is indeed a bit concerning - 6-7 minutes:
`--- PASS: TestIntegreatly/integreatly/H07_-_ThreeScale_User_Promotion (379.00s)`
`--- PASS: TestIntegreatly/integreatly/H07_-_ThreeScale_User_Promotion (368.53s)`
`--- PASS: TestIntegreatly/integreatly/H07_-_ThreeScale_User_Promotion (368.62s)`
I don't think there is anything wrong with this particular test, but it might be better to discuss this before merging.

**Pull request merged**
