### PR TITLE
MGDAPI-702: Support update of customer notification email

### PR DESCRIPTION
**Pull request by sergioifg94**
# Description

> Link to Jira: https://issues.redhat.com/browse/MGDAPI-702

Add support to reconcile the customer notification email from the add-on parameter Secret

## Verification steps

1. Prepare the cluster
    ```sh
    INSTALLATION_TYPE=managed-api make cluster/prepare/local
    ```
1. Create the parameters secret
    ```sh
    oc create secret generic addon-managed-api-service-parameters -n redhat-rhmi-operator \
      --from-literal=notification-email=test-customer@redhat.com
    ```
1. Install MGDAPI locally
    ```sh
    INSTALLATION_TYPE=managed-api make code/run
    ```

1. Verify the email address parameter is reconciled
    1. Check that the `.spec.alertingEmailAddress` is `test-customer@redhat.com`
    2. Check that the address is included in the `BUAndCustomer` and `SREAndCustomer` receivers in the Alert Manager configuration:
        1. Log in the alert manager
            >
            > You can find the route with:
            > ```sh
            > oc get route alertmanager-route -n redhat-rhmi-middleware-monitoring-operator
            >
        1. Go to `Status -> Config` and check the `to` fields for the receivers

1. Update the email address in the `addon-managed-api-service-parameters` Secret    

1. Repeat step 4, checking for the new email address instead
    > It might take a couple of minutes for the operator to reconcile this change

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by briangallagher** [comment]
verified as described above
/lgtm

**Comment by pmccarthy** [comment]
@sergioifg94  @briangallagher we'll need to cherry pick this over to `release-rhoam-v1.0` once merged

**Pull request merged**
