### PR TITLE
MGDAPI-2981 - bump: operator-sdk 1.21.0

### PR DESCRIPTION
**Pull request by KevFan**
# Issue link

https://issues.redhat.com/browse/MGDAPI-2981

# What

Bump operator sdk to 1.21.0

# Verification steps

##  Verify Upgrade
* Install 1.22.0 via OLM using index
```
INSTALLATION_TYPE=managed-api make cluster/prepare
oc apply -f - <<EOF
---             
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhmi-operators
  namespace: openshift-marketplace
spec:
  image: 'quay.io/kevfan/managed-api-service-index:1.22.0'
  sourceType: grpc
EOF
  ```
* Go to Operator Hub and install RHOAM
* Create RHMI CR
```
INSTALLATION_TYPE=managed-api IN_PROW=true make deploy/integreatly-rhmi-cr.yml
```
* Once installed, trigger upgrade
```
oc patch catalogsources rhmi-operators  -n openshift-marketplace  --type=json -p='[{"op": "replace", "path": "/spec/image", "value": "quay.io/kevfan/managed-api-service-index:1.23.0"}]'
```
* Verify operator upgrades successfully
* Uninstall operator using config map
```
oc apply -f - <<EOF
---             
kind: ConfigMap
apiVersion: v1
metadata:
  name: managed-api-service
  namespace: redhat-rhoam-operator
  labels:
    api.openshift.com/addon-managed-api-service-delete: "true"
EOF
```
* Verify RHMI CR is triggered for deletion
* Verify RHOAM uninstalls successfully

## Verify fresh installation
* Cleanup residual resources from uninstall
```
oc delete subscription managed-api-service -n redhat-rhoam-operator
oc delete configmap managed-api-service -n redhat-rhoam-operator
```
* Go to Operator Hub in UI and install RHOAM
* Create RHMI CR
```
INSTALLATION_TYPE=managed-api IN_PROW=true make deploy/integreatly-rhmi-cr.yml
```
* Verify install completes successfully
* Uninstall operator using config map
```
oc apply -f - <<EOF
---             
kind: ConfigMap
apiVersion: v1
metadata:
  name: managed-api-service
  namespace: redhat-rhoam-operator
  labels:
    api.openshift.com/addon-managed-api-service-delete: "true"
EOF
```
* Verify RHMI CR is triggered for deletion
* Verify RHOAM uninstalls successfully
* Cleanup residual resources from uninstall
```
oc delete subscription managed-api-service -n redhat-rhoam-operator
oc delete configmap managed-api-service -n redhat-rhoam-operator
```

### CODE REVIEW

**Comment by austincunningham** [comment]
code changes look good will try a verification of the upgrade

**Comment by KevFan** [comment]
Rebased against master to resolve conflicts

**Comment by KevFan** [comment]
Rebased against master

**Pull request merged**
