### PR TITLE
update webapp version to 2.27.0 and SP to 1.0.12

### PR DESCRIPTION
**Pull request by pb82**
# Description

update webapp to 2.27.0 and Solution patterns to v1.0.12

### CODE REVIEW

**Comment by grdryn** [comment]
/retest

Not sure if this will work, there seem to be prow issues atm

**Comment by pb82** [comment]
@grdryn Prow seems to be completely down, the link to the build even does not work

**Comment by grdryn** [comment]
@pb82 it's apparently that the routes aren't working after a router restart on that cluster. Which means that it can't receive the webhooks from GH, among other things probably

**Pull request merged**
