### PR TITLE
Intly 6954 slo dashboards

### PR DESCRIPTION
**Pull request by R-Lawton**
# Description
The following PR is to show the changes made to create a SLO dashboard in grafana.  [Jira](https://issues.redhat.com/browse/INTLY-6594)

Verification
1. Install integreatly from this branch
2. make a few alerts fire
3. verify the dashboard portrays this change.

Screenshot from 2020-04-08 17-56-32

### CODE REVIEW

**Comment by alanmoran** [comment]
The dashboard looks good to me. Nice work! /lgtm

**Comment by david-martin** [comment]
Will hold off on approval until sre have had a change to review.
Before then, @R-Lawton lets go ahead and add repeating rows below the summary panel, from a hardcoded list of namespaces & match on the `namespace` label of the alert.
I realise a number of alerts don't have a `namespace` label, but that can be addressed in a future change.

**Comment by R-Lawton** [comment]
Update has been made to the Dashboard please see screenshot above

**Pull request merged**
