### PR TITLE
MGDAPI-5833 Removed remaining OO code

### PR DESCRIPTION
**Pull request by carlkyrillos**
# Issue link
JIRA: [MGDAPI-5833](https://issues.redhat.com/browse/MGDAPI-5833)

# What
This PR removes the remaining references to OO including the OO uninstallation logic which can now be removed since RHOAM 1.38.0 has shipped to production.

# Verification steps
We need to verify that the RHOAM install and uninstall logic works for both fresh install and upgrade scenarios.

## Verify upgrade scenario
1. Checkout `rhoam-v1.38.0`
```bash
git checkout rhoam-v1.38.0
```
2. Prepare the cluster:
```bash
make cluster/prepare/local
```
3. Create the CatalogSource:
```bash
cat << EOF | oc create -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhoam-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/ckyrillo/managed-api-service-index:1.38.0
EOF
```
4. Create the RHOAM CR:
```bash
IN_PROW=false USE_CLUSTER_STORAGE=true make deploy/integreatly-rhmi-cr.yml
```
5. Login into the cluster and install RHOAM via OperatorHub
6. Verify that the installation completes without error
7. Update the CatalogSource to point to the upgrade image: `quay.io/ckyrillo/managed-api-service-index:1.39.0`
8. Verify that the upgrade completes without error
9. Clean up the cluster for the fresh install scenario
```bash
make cluster/cleanup
make cluster/cleanup/crds
```

## Verify fresh install scenario
1. Checkout this PR
2. Prepare the cluster:
```bash
make cluster/prepare/local
```
3. Create the CatalogSource:
```bash
cat << EOF | oc create -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhoam-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/ckyrillo/managed-api-service-index:1.40.0
EOF
```
4. Create the RHOAM CR:
```bash
IN_PROW=false USE_CLUSTER_STORAGE=true make deploy/integreatly-rhmi-cr.yml
```
5. Login into the cluster and install RHOAM via OperatorHub
6. Verify that the installation completes without error

### CODE REVIEW

**Comment by austincunningham** [comment]
- [x] Upgrade completed 
one issue that the version didn't update in the rhmi CR, and we didn't see a toVersion
```yaml
  version: 1.38.0
```
I presume this is because the version was not set in the operator code before building the image.

- [x] Install completed
same issue in the rhmi CR 
```yaml
  version: 1.38.0
```
Again I would say it's the same as above

**Comment by carlkyrillos** [comment]
> * [x]  Upgrade completed
>   one issue that the version didn't update in the rhmi CR, and we didn't see a toVersion
> 
> ```yaml
>   version: 1.38.0
> ```
> 
> I presume this is because the version was not set in the operator code before building the image.
> 
> * [x]  Install completed
>   same issue in the rhmi CR
> 
> ```yaml
>   version: 1.38.0
> ```
> 
> Again I would say it's the same as above

@austincunningham Yes sorry about that I think I missed that when building the images. Want me to rebuild them with the proper versions for a re-verification or do you think it's good to go as is?

**Comment by austincunningham** [comment]
@carlkyrillos I would say its fine , the version change is not part of the PR so no big deal it doesn't change 
/lgtm

**Pull request merged**
