### PR TITLE
removed test-containers-managed-api because it is no longer needed

### PR DESCRIPTION
**Pull request by martinhesko**
in [this PR](https://github.com/integr8ly/integreatly-operator/pull/2272) we agreed that this file will be generated dynamically and outside of our use it's no longer needed. This is the PR to remove that file.

### CODE REVIEW

**Comment by psturc** [comment]
I'm not sure if this change is required since our pipelines are no longer dependant on the content of integreatly-operator regarding running product tests.

Otherwise I think it would make sense to also include the change for deletion of [the make target](https://github.com/integr8ly/integreatly-operator/blob/7533de7ddccfb08fa5388b1fc47a817820f31da9/Makefile#L273-L277)

**Comment by martinhesko** [comment]
It's definitely not required but as Tomáš said in the previous PR: if it's not going to be used anymore anywhere and we have a different workflow for it now I think it makes sense to remove it.

**Comment by psturc** [comment]
ah, ok, I forgot about that. that's fine then

**Comment by KevFan** [comment]
@martinhesko Would you still like this PR to be merged ? If so, could you add the JIRA ticket number to the commits :pray:

**Comment by KevFan** [comment]
Bump ^^

**Comment by martinhesko** [comment]
@KevFan fixed and ready to merge :+1:

**Pull request merged**
