### PR TITLE
MGDAPI-4153 unto tmp fix for kc

### PR DESCRIPTION
**Pull request by makslion**
# Issue link
[MGDAPI-4153](https://issues.redhat.com/browse/MGDAPI-4153)

# What
It was proven that the fix is not applicable and extra information collection is not needed. 

# Verification steps
e2e passing should be sufficient.

### CODE REVIEW

**Comment by makslion** [comment]
what is happening with tide? :thinking: 

/retest

**Comment by makslion** [comment]
rebased 

/test rhoam-e2e

**Review by cecobask — APPROVED** [review]
/lgtm

**Pull request merged**
