### PR TITLE
Remove RHMI reference in user sso console link

### PR DESCRIPTION
**Pull request by Boomatang**
# Description

Remove RHMI reference from the user sso console link which is only used in managed-api installs.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by KevFan** [comment]
Verified :+1: 

image

/lgtm

**Comment by philbrookes** [comment]
is this going to upset RHMI installations?

**Comment by KevFan** [comment]
@philbrookes No, should not, this is exclusive to RHOAM, and ensure's it's deleted for RHMI also
* https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/rhssouser/reconciler.go#L1158-L1164
* https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/rhssouser/reconciler.go#L1193-L1205

**Pull request merged**
