### PR TITLE
MGDAPI-4859 - images: remove tracking OO custom prometheus index

### PR DESCRIPTION
**Pull request by KevFan**
# Issue link

https://issues.redhat.com/browse/MGDAPI-4859

# What

OO has swtiched to use the community prometheus index so we no longer need to track their own custom prometheus index

# Verification steps

* None required

### CODE REVIEW

**Comment by cecobask** [comment]
@KevFan I'm not sure if this affects anything, but I think the image should be removed from the file `bundles/managed-api-service/1.29.0/manifests/managed-api-service.clusterserviceversion.yaml` path `metadata.annotations.containerImages`. Other than that, I'm happy to lgtm.

**Comment by KevFan** [comment]
Thanks @cecobask 👍  Updated csv with the latest container images

**Review by cecobask — APPROVED** [review]
/lgtm

**Pull request merged**
