### PR TITLE
change to ubi minimal base image

### PR DESCRIPTION
**Pull request by briangallagher**
# Description
change to ubi minimal base image to reduce possible attach surface and CVE respins
[JIRA](https://issues.redhat.com/browse/INTLY-10574)

# Verify
Install RHMI and RHOAM 
After 3Scale installs delete one route and confirm it recovers.

Uninstall 
Verify during the uninstall a Silence Alert is created.
Verify Uninstall successful

### CODE REVIEW

**Comment by briangallagher** [comment]
@CathalOConnorRH Can you review?

**Comment by CathalOConnorRH** [comment]
Verified both installs on cluster and worked as expected. 
/lgtm

**Pull request merged**
