### PR TITLE
Fix e2e tests around IDP

### PR DESCRIPTION
**Pull request by jjaferson**
# Description

Fixes IDP issues causing flakiness in e2e tests

https://issues.redhat.com/browse/MGDAPI-557
https://issues.redhat.com/browse/MGDAPI-558

## Verification steps

1) Install the operator with the install type for rhoam
```bash
 INSTALLATION_TYPE=managed-api make cluster/prepare/local && INSTALLATION_TYPE=managed-api make code/run
```
2) Run the functional e2e tests
```bash
INSTALLATION_TYPE=managed-api make test/functional
```
3) Verify if all the IDP based e2e tests `IDP_BASED_TESTS` pass

### CODE REVIEW

**Comment by psturc** [comment]
I have run the tests using `quay.io/philbrookes/integreatly-operator-test-harness:idp-and-prow` image
results: https://gist.github.com/psturc/fb62744d63a0d6c87835342e49280a78

Note: before I ran the tests, I configured SSO IDP on the cluster, but after tests finished and I visited console logging page, the testing-idp provider was no longer there 🤷‍♂️

**Comment by jjaferson** [comment]
> I have run the tests using `quay.io/philbrookes/integreatly-operator-test-harness:idp-and-prow` image
> results: https://gist.github.com/psturc/fb62744d63a0d6c87835342e49280a78
> 
> Note: before I ran the tests, I configured SSO IDP on the cluster, but after tests finished and I visited console logging page, the testing-idp provider was no longer there

it looks like the `testing-idp` IDP wasn't created https://gist.github.com/psturc/fb62744d63a0d6c87835342e49280a78#file-single-az-rc1-test-output-log-L144

**Comment by KevFan** [comment]
Verified IDP tests passing :+1: 
/lgtm

**Pull request merged**
