### PR TITLE
MGDAPI-3476 / Uncommented test cases + Removed redundant code

### PR DESCRIPTION
**Pull request by den-rgb**
[MGDAPI-3476](https://issues.redhat.com/browse/MGDAPI-3476)

### CODE REVIEW

**Comment by austincunningham** [comment]
/lgtm
`ci/prow/multitenant-rhoam-e2e` are broken and not required to pass

**Comment by MStokluska** [comment]
@den-rgb @austincunningham can this go in or be closed? Are we blocked on anything here?

**Comment by austincunningham** [comment]
I would say this can merge. The feature branch needs a rebase to fix the MT e2e as that test is already fixed on master

**Comment by MStokluska** [comment]
Leaving lgtm on Austins behalf.
/lgtm
/approve

**Pull request merged**
