### PR TITLE
Operator-sdk bump to 1.7.2

### PR DESCRIPTION
**Pull request by MStokluska**
# Description
Operator-sdk bump to 1.7.2

# Updates
- finalizers renames to <component>.<org>/finalizer
- some dependencies updates
- minor change around make image/build docker command

# Verification
- need sanity check on the finalizers re-work (code)
- run the initial install from this branch (bump to sdk 1.7.2) on byoc cluster with cluster storage set to false
```
curl -Lso operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v1.7.2/operator-sdk_linux_amd64 && \
chmod +x operator-sdk && \
sudo mv operator-sdk /usr/local/bin
```
- verify that upgrade from master to this branch work as expected (via OLM), also on byoc cluster with cluster storage false
- verify uninstallation and confirm that everything deletes correctly (including AWS resources being correctly deleted)

### CODE REVIEW

**Comment by KevFan** [comment]
Looks good overall :+1: 

Have a just the following comments:

I think we need to update the operator-sdk version used in the CI also :thinking: 
* https://github.com/MStokluska/integreatly-operator/blob/MGDAPI-1484/openshift-ci/Dockerfile.tools#L4

Also can we update version specified in the `README` for conistency ?
* https://github.com/MStokluska/integreatly-operator/tree/MGDAPI-1484#prerequisites

**Comment by MStokluska** [comment]
> Looks good overall +1
> 
> Have just the following comments:
> 
> I think we need to update the operator-sdk version used in the CI also thinking
> 
>     * https://github.com/MStokluska/integreatly-operator/blob/MGDAPI-1484/openshift-ci/Dockerfile.tools#L4
> 
> 
> Also can we update the version specified in the `README` for consistency ?
> 
>     * https://github.com/MStokluska/integreatly-operator/tree/MGDAPI-1484#prerequisites

Thanks @KevFan , good point, updated now.

**Comment by KevFan** [comment]
With CCS cluster using external storage:
* Verified fresh RHOAM install from this branch
* Verified upgrade of master RHOAM to this branch via OLM
* Verified RHOAM uninstall
* Verified fresh RHMI install from this branch
* Verified upgrade of master RHMI to this branch via OLM
* Verified RHMI uninstall

Nice work :+1: 

/lgtm
/test e2e
/test rhoam-e2e

**Comment by MStokluska** [comment]
/retest 
github issues

**Pull request merged**
