### PR TITLE
update n07 test case

### PR DESCRIPTION
**Pull request by aidenkeating**
# Description

the current n07 test case is not correct.

update it to ensure that we clarify what we are testing for:

- that cro has lined up maintenance correctly
- forcing the maintenance in aws through a configmap change
- ensuring aws performed the maintenance successfully

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by aidenkeating** [comment]
@psturc @pawelpaszki Mind taking a look? I realise this case is basically being updated towards the end of the only test cycle it's really relevant for. But I still think an update makes sense for context/to avoid confusion

**Comment by psturc** [comment]
Just need to run `npm run prettier` to be able to merge.
Otherwise LGTM

**Comment by psturc** [comment]
Error from the test-cases-lint job:
```
warn: i10-align-docs-with-changes-to-Solution-Explorer-ui-text.md should be renamed to i10-align-docs-with-changes-to-solution-explorer-ui-text.md
error: some files are not named correctly, use --write to rename all of them
```
apparently someone forgot to run `npm run rename` in their PR and merged it anyway... :/

**Comment by mikenairn** [comment]
@aidenkeating @psturc Should this not be in the 2.5 branch? I don't suppose it really matters, but it fixes the test cases lint job so was thinking of cherry picking it back unless there is some reason we wouldn't want to do that?

**Pull request merged**
