### PR TITLE
Add new dashboard to tests "SLO SSO..."

### PR DESCRIPTION
**Pull request by matskiv**
# Description
Follow up on [MGDAPI-1610](https://issues.redhat.com/browse/MGDAPI-1610) and #1845
Adding new dashboard to the list in E03 test case.

### CODE REVIEW

**Comment by Boomatang** [comment]
Verified by checking the test logs. Did not see E03 failing.

/lgtm

**Comment by matskiv** [comment]
ci/prow/e2e failed on deprovision, but the e2e test passed

**Pull request merged**
