### PR TITLE
Rhmidoc 69

### PR DESCRIPTION
**Pull request by briandooley**
# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by briandooley** [comment]
@ldimaggi I've checked a couple of boxes in the above description. If I need to do anything else, please let me know.

**Comment by briandooley** [comment]
Added /lgtm to this as it appears this was missing.

**Comment by b1zzu** [comment]
@pb82 @trdoyle81 @tonyxrmdavidson @briandooley Hi guys, this PR has broken the `test-cases-lint` pipeline on master because it was been merged even if the `test-cases-lint` pipeline was failing on the PR, so please next time don't manually merge a PR without checking that all pipelines are passing before

**Comment by b1zzu** [comment]
I've created this PR: https://github.com/integr8ly/integreatly-operator/pull/1013 to fix the issues introduced here

**Pull request merged**
