### PR TITLE
Add 'Don't fail immediately' to the test Best Practices

### PR DESCRIPTION
**Pull request by b1zzu**
# Description

This best practice comes from the experience with many new tests we created which verify multiple resources in the loop and therefore is better to check all resource before failing and report multiple errors if needed

### CODE REVIEW

**Comment by b1zzu** [comment]
@sergioifg94 I had to rebase the PR so it needs to be approved again

**Comment by sergioifg94** [comment]
No problem @b1zzu 👍 
/lgtm

**Comment by b1zzu** [comment]
/test e2e
--

**Pull request merged**
