### PR TITLE
bump cro to 0.20.0

### PR DESCRIPTION
**Pull request by aidenkeating**
# Description

Bump CRO to version 0.20.0

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by ciaranRoche** [comment]
## Replicated error 
Upgrading from 2.4 -> 2.5 
image
## Upgrade to this branch
image
image
## Clusters in AWS different AZ's
`us-east-1e` is the AZ which does not currently support `t3`
image

**Comment by aidenkeating** [comment]
# 2.5.0 Upgrade

## Pre Upgrade

CRO metadata is 0.17.0

Screenshot 2020-08-07 at 23 59 48

CRO manifest version is 0.17.0

Screenshot 2020-08-07 at 23 44 31

t3.micro instances are used (this is expected with an install of 2.5.0)

Screenshot 2020-08-07 at 23 44 51

The first two AZs in a region are exclusively used for Elasticache nodes (this is expected with an install of 2.5.0, as from 2.5.0 onwards AZ selection is deterministic)

Screenshot 2020-08-07 at 23 45 14
Screenshot 2020-08-07 at 23 45 04

Redis resources are in a successful state already (this is expected with an install of 2.5.0)

Screenshot 2020-08-08 at 00 04 59 

Screenshot 2020-08-08 at 00 05 10

## Post Upgrade

CRO metadata is now 0.20.0

Screenshot 2020-08-08 at 00 25 07

CRO manifest is now 0.20.0

Screenshot 2020-08-08 at 00 17 45

Elasticache resources are in an available state still

Screenshot 2020-08-08 at 00 21 06


Redis resources are in a successful state still

Screenshot 2020-08-08 at 00 21 26
Screenshot 2020-08-08 at 00 21 20

No alerts are firing

screencapture-prometheus-route-redhat-rhmi-middleware-monitoring-operator-apps-hcd-collab-q4z8-s1-devshift-org-alerts-2020-08-08-00_37_13

**Comment by aidenkeating** [comment]
/approve

Tested from both 2.5.0 and 2.4.0

**Pull request merged**
