### PR TITLE
MGDAPI-5646 - consume CRO release v1.1.0

### PR DESCRIPTION
**Pull request by adam-cattermole**
# Issue link
[MGDAPI-5646](https://issues.redhat.com/browse/MGDAPI-5646)

# What
Upgrade CRO to v1.1.0

# Verification steps
Perform upgrade test

### CODE REVIEW

**Comment by austincunningham** [comment]
code changes look good to me

**Comment by adam-cattermole** [comment]
/hold

Needs to be skipped due to issue in CRO https://github.com/integr8ly/cloud-resource-operator/pull/682.

**Comment by adam-cattermole** [comment]
Repurposing for consuming v1.1.0

/unhold

**Comment by MStokluska** [comment]
Looks good to me, both fresh and upgrade scenario verified - all looks as expected.

/lgtm

**Pull request merged**
