### PR TITLE
ensure fuse online aws expected alerts are added

### PR DESCRIPTION
**Pull request by aidenkeating**
Key changes:
91ebbdc - Fuse Online AWS alerts

Verification:
- Run `make test/functional` against an RHMI cluster using AWS resources

### CODE REVIEW

**Comment by maleck13** [comment]
I am not familiar with the test but seeing Ciaran has okd I am happy to add a lgtm

**Comment by aidenkeating** [comment]
Manually adding the approved label as it didn't seem to pick up on the previous approval.

**Comment by matskiv** [comment]
Adding override to avoid blocking merging in case of retest fail
/override ci/prow/e2e

**Pull request merged**
