### PR TITLE
INTLY-7937 - upgrades pausing test case

### PR DESCRIPTION
**Pull request by matskiv**
# Description
A test case for https://issues.redhat.com/browse/INTLY-7937
To test SOP that was added https://github.com/RHCloudServices/integreatly-help/pull/614 

cc @grdryn @trepel FYI: this test case is for upcoming release. It needs to be executed on a pre-upgrade cluster, and will require cooperation with release coordinator due to need for changes in managed tenants.

### CODE REVIEW

**Comment by matskiv** [comment]
I added the requested changes, please review last commit :)

**Comment by matskiv** [comment]
@trepel Thanks for thee review. I am going to need that "/lgtm" again, after I fix lint issues 🙈

**Comment by trepel** [comment]
my bad, I thought it had passed.

**Pull request merged**
