### PR TITLE
INTLY-5589: Create dedicated-admins and realm-managers groups

### PR DESCRIPTION
**Pull request by sergioifg94**
Implement functionallity in RHSSO User operator to create a dedicated-admins group
with a realm-managers child group.
The dedicated-admins group has the manage-users and view-realm client roles,
and the realm-managers group has a manage-realm role for each role that is
created.
Implement functionallity to add the dedicated admin generated users from
Openshift to the dedicated-admins and realm-managers groups.

Refactor the logic to reconcile Keycloak groups based on a `keycloakGroupSpec`
struct that contains the desired status of the group.

## Verification

Running on a cluster, set up the SSO IdP
```sh
PASSWORD=Password1 ./scripts/setup-sso-idp.sh
```
Log in the User SSO as the `customer-admin01` user and check that (_Note: it might take a couple of minutes for the admin permissions to propagate after first login_):

- [ ] A group in the User SSO instance called `dedicated-admins` is created
  - [ ] The group has the `manage-users` role mapped to the `master-realm` client
  - [ ] The group has the `view-realm` role mapped to the `master-realm` client
  - [ ] A child group of the `dedicated-admins` group called `realm-managers` is created
    - [ ] The group has the `manage-realm` role mapped to the `master-realm` client
    - [ ] Create a new realm and, after reconciliation, the group has the all roles except `impersonation` mapped to the `<realm name>-realm` client
- [ ] The dedicated admin users from the Openshift IdP are members of the `dedicated-admins` and `realm-managers` groups in SSO

### CODE REVIEW

**Comment by philbrookes** [comment]
:eyes:

**Comment by philbrookes** [comment]
/lgtm
/approve
tested on my own cluster

**Comment by matskiv** [comment]
@sergioifg94 This bit from verification steps is wrong:
`The group has the manage-realm role mapped to the master-realm client`
dedicated-admins should NOT be able to manage master realm

**Comment by matskiv** [comment]
We also need to update installation controller to enqueue reconcile every X minutes to pick up new realms. @philbrookes wdyt?

**Comment by sergioifg94** [comment]
@matskiv 
> dedicated-admins should NOT be able to manage master realm

So the `manage-realm` role should be added to all realms **except master**?

**Comment by matskiv** [comment]
@sergioifg94 yes
Apologies, this is my bad, I didn't mention it in the JIRA description.

**Comment by matskiv** [comment]
Verified. Thanks for all the code changes @sergioifg94 
/unhold
/lgtm

**Pull request merged**
