### PR TITLE
[MGDAPI-3624] Bumped golang version 1.17 -> 1.18

### PR DESCRIPTION
**Pull request by bryankeane0**
# Issue link
[MGDAPI-3624](https://issues.redhat.com/browse/MGDAPI-3624)

# What
- Bumped golang version from 1.17 to 1.18

# Verification steps
- Tests passing and code review should suffice
- `ci/prow/vendor` won't pass until this PR is merged and the PR to `openshift/release` is auto-created by the ci-operator

### CODE REVIEW

**Comment by KevFan** [comment]
Changes looks good to me :+1: 

/lgtm

**Comment by MStokluska** [comment]
Removed approve label - @bryankeane0 can you fix the commit message please

**Comment by bryankeane0** [comment]
@MStokluska sorry about that, done 👍🏻

**Pull request merged**
