### PR TITLE
update the reviewers in OWNERS

### PR DESCRIPTION
**Pull request by austincunningham**
# Description

Update the reviewers in OWNERS to reflect the current team

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by pmccarthy** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as members of the integr8ly org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
> * jackdelahunt
>   
>   * User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
> * pstruc
>   
>   * User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.

Typo for psturc?

**Comment by austincunningham** [comment]
@matskiv can you stick the /lgtm on this again

**Pull request merged**
