### PR TITLE
Rhoam 1 4 0 test case updates

### PR DESCRIPTION
**Pull request by psturc**
# Description
https://issues.redhat.com/browse/MGDAPI-1407

### CODE REVIEW

**Comment by psturc** [comment]
ping @trepel

**Comment by trepel** [comment]
@psturc It looks ok to me, I just don't understand the combination of both `target` and `manual-selection`. If test case is tagged by `manual-selection` it won't be picked every three releases by `tools.sh plan...`. Is it intentional?

I think each test case tagged by `manual-selection` should contain some information about when it should be selected.

**Comment by psturc** [comment]
> @psturc It looks ok to me, I just don't understand the combination of both `target` and `manual-selection`. If test case is tagged by `manual-selection` it won't be picked every third release by `tools.sh plan...`. Is it intentional?
> 
> I think each test case tagged by `manual-selection` should contain some information about when it should be selected.

That is a good point, I don't know what I was thinking when creating these test cases :) Probably a copy-pasta issue

**Pull request merged**
