### PR TITLE
bump grafana version

### PR DESCRIPTION
**Pull request by briangallagher**
# Issue link
https://issues.redhat.com/browse/MGDAPI-2671

# What
Bump grafana version to 3.10.4 

# Verification steps
Install RHOAM from master
Then run this branch to simulate an upgrade
Verify that Grafana upgrades to 3.10.4
Verify that dashboards still exist and look correct

Automated tests will cover the install scenario

### CODE REVIEW

**Comment by KevFan** [comment]
On upgrade, I was not able to login into customer grafana with a `500` internal error. Checking the logs of the `auth-openshift` pods in `openshift-authentication` gives the following errors
```
##E0922 14:31:37.796271       1 access.go:177] osin: error=unauthorized_client, internal_error=<nil> get_client=client check failed, client_id=system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount
E0922 14:31:44.061603       1 access.go:177] osin: error=unauthorized_client, internal_error=<nil> get_client=client check failed, client_id=system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount
E0922 14:32:28.152626       1 access.go:177] osin: error=unauthorized_client, internal_error=<nil> get_client=client check failed, client_id=system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount
E0922 14:33:45.688138       1 access.go:177] osin: error=unauthorized_client, internal_error=<nil> get_client=client check failed, client_id=system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount
```

On fresh install, although the install complete on the RHMI CR, the grafana deployment pod was a in a `CrashLoop` with the following error in the `grafana-proxy` container
image
```
2021/09/22 15:03:03 provider.go:117: Defaulting client-id to system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount
2021/09/22 15:03:03 provider.go:122: Defaulting client-secret to service account token /var/run/secrets/kubernetes.io/serviceaccount/token
2021/09/22 15:03:03 provider.go:310: Delegation of authentication and authorization to OpenShift is enabled for bearer tokens and client certificates.
2021/09/22 15:03:03 main.go:138: Invalid configuration:
  unable to load OpenShift configuration: unable to retrieve authentication information for tokens: tokenreviews.authentication.k8s.io is forbidden: User "system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount" cannot create resource "tokenreviews" in API group "authentication.k8s.io" at the cluster scope
```

Wondering have you seen this ? :thinking:

**Comment by briangallagher** [comment]
> On upgrade, I was not able to login into customer grafana with a `500` internal error. Checking the logs of the `auth-openshift` pods in `openshift-authentication` gives the following errors
> 
> ```
> ##E0922 14:31:37.796271       1 access.go:177] osin: error=unauthorized_client, internal_error=<nil> get_client=client check failed, client_id=system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount
> E0922 14:31:44.061603       1 access.go:177] osin: error=unauthorized_client, internal_error=<nil> get_client=client check failed, client_id=system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount
> E0922 14:32:28.152626       1 access.go:177] osin: error=unauthorized_client, internal_error=<nil> get_client=client check failed, client_id=system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount
> E0922 14:33:45.688138       1 access.go:177] osin: error=unauthorized_client, internal_error=<nil> get_client=client check failed, client_id=system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount
> ```
> 
> On fresh install, although the install complete on the RHMI CR, the grafana deployment pod was a in a `CrashLoop` with the following error in the `grafana-proxy` container
> image
> 
> ```
> 2021/09/22 15:03:03 provider.go:117: Defaulting client-id to system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount
> 2021/09/22 15:03:03 provider.go:122: Defaulting client-secret to service account token /var/run/secrets/kubernetes.io/serviceaccount/token
> 2021/09/22 15:03:03 provider.go:310: Delegation of authentication and authorization to OpenShift is enabled for bearer tokens and client certificates.
> 2021/09/22 15:03:03 main.go:138: Invalid configuration:
>   unable to load OpenShift configuration: unable to retrieve authentication information for tokens: tokenreviews.authentication.k8s.io is forbidden: User "system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-serviceaccount" cannot create resource "tokenreviews" in API group "authentication.k8s.io" at the cluster scope
> ```
> 
> Wondering have you seen this ? 🤔

Sorry Kevin, I pushed the wrong version of the CSV. That should be working now.

**Comment by KevFan** [comment]
Verified upgrade works on pre-openshift 4.9 cluster :+1: 

However, trying to do an install on openshift 4.9 RC1, the grafana-operator is in a `CrashLoop` with the following error due of use of a removed API :thinking: :
```
{"level":"error","ts":1632412347.3018975,"logger":"cmd","msg":"manager exited non-zero","error":"no matches for kind \"Ingress\" in version \"extensions/v1beta1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/opt/app-root/src/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/workspace/cmd/manager/main.go:235\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:204"}
```

**Comment by briangallagher** [comment]
@KevFan The new Grafana image is now available. No code change required in this PR as the same tag was used. Can you retest please on 4.9

**Comment by briangallagher** [comment]
@KevFan I've just been informed an issue has been found, please hold off.

**Comment by briangallagher** [comment]
@KevFan This is ready for review again.

**Comment by KevFan** [comment]
@briangallagher Cool, I'll take a look :+1:  

Looks like this needs a rebase :thinking: 

Another thing is I wonder do we need to update the oauth proxy version also ? :thinking: 
* https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/grafana/reconciler.go#L284
* It was updated in Observability Operator due to an issue 
  * https://github.com/redhat-developer/observability-operator/pull/82/files

**Comment by KevFan** [comment]
@briangallagher Looks like the csv has some differences with the midstream. Seeing the following error on 4.9 cluster in the grafana operator logs. This permissions looks to be missing from the csv in this PR but it present in the the midstream csv :thinking: 
```
E1005 15:08:00.052040       1 reflector.go:138] go/pkg/mod/k8s.io/client-go@v0.20.6/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:redhat-rhoam-customer-monitoring-operator:grafana-operator" cannot list resource "ingresses" in API group "networking.k8s.io" in the namespace "redhat-rhoam-customer-monitoring-operator"
```

**Comment by KevFan** [comment]
* Verified installation succeeding on 4.9 cluster and able to access grafana
* Verified upgrade from master to this branch on 4.8 cluster and able to access grafana

/lgtm

**Pull request merged**
