### PR TITLE
replacing container_name with container

### PR DESCRIPTION
**Pull request by R-Lawton**
# Description
Fixing dashboards not displaying correctly due to a old metric label being used.  https://issues.redhat.com/browse/INTLY-6401

### CODE REVIEW

**Comment by david-martin** [comment]
/lgtm
/approve

Just looks like a few places where queries weren't updated yet.

**Comment by R-Lawton** [comment]
@david-martin This sis a bit starnge it merged the pr even though the e2e tests "havent passed" but in reality they have passed if you click into the details of it and it passed on the cluster. Its like it knows everything passed but not displaying it

**Comment by david-martin** [comment]
@R-Lawton That's odd.
If I click on the green ✔️ beside the commit above, it shows all CI jobs as passed

**Comment by R-Lawton** [comment]
this is what i see 
Screenshot from 2020-03-23 09-34-00

**Pull request merged**
