### PR TITLE
MGDAPI-3797 - gosec: remove G204 from exclusion list

### PR DESCRIPTION
**Pull request by KevFan**
# Issue link

https://issues.redhat.com/browse/MGDAPI-3797

# What

G204 doesn't seem to trigger any warnings when removed from the exclusion list

Places where we use the command execution are:
* 3scale Pod
  * https://github.com/integr8ly/integreatly-operator/blob/077981a7bea3dffad9109714e22bef0a17e1fa78/pkg/products/threescale/reconciler.go#L1131
  * https://github.com/integr8ly/integreatly-operator/blob/077981a7bea3dffad9109714e22bef0a17e1fa78/pkg/resources/podHelper.go#L17-L62 
* APICase Self Managed Test
  * https://github.com/integr8ly/integreatly-operator/blob/a2e962fff2feb7163f70c75f0b6af1e4255db6be/test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go#L506-L516 
  * https://github.com/integr8ly/integreatly-operator/blob/a2e962fff2feb7163f70c75f0b6af1e4255db6be/test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go#L784-L785
  * https://github.com/integr8ly/integreatly-operator/blob/a2e962fff2feb7163f70c75f0b6af1e4255db6be/test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go#L211-L212
  * https://github.com/integr8ly/integreatly-operator/blob/a2e962fff2feb7163f70c75f0b6af1e4255db6be/test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go#L473-L488
  * https://github.com/integr8ly/integreatly-operator/blob/a2e962fff2feb7163f70c75f0b6af1e4255db6be/test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go#L784-L785
  * https://github.com/integr8ly/integreatly-operator/blob/a2e962fff2feb7163f70c75f0b6af1e4255db6be/test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go#L223-L224

# Verification steps

* Passing GoSec prow job should be sufficient

### CODE REVIEW

**Comment by Boomatang** [comment]
I think you need to look at this PR again. Running the gosec tool on this branch gives the following result
```
221:[/home/jimfitz/go/src/github.com/integr8ly/integreatly-operator/test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go:507] - G204 (CWE-78): Subprocess launched with variable (Confidence: HIGH, Severity: MEDIUM)
```

**Comment by KevFan** [comment]
> I think you need to look at this PR again. Running the gosec tool on this branch gives the following result
> 
> ```
> 221:[/home/jimfitz/go/src/github.com/integr8ly/integreatly-operator/test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go:507] - G204 (CWE-78): Subprocess launched with variable (Confidence: HIGH, Severity: MEDIUM)
> ```

@Boomatang Sure, is there a version of gosec your using ? Doesn't seem to be giving me the same result on v2.11.0  :shrug:

**Comment by Boomatang** [comment]
@KevFan That could be the problem, The version I am running is dev. Let me work out how to update and I will run it again.

**Comment by Boomatang** [comment]
Yap that looks to have being the issue. 
/lgtm

**Pull request merged**
