### PR TITLE
Removing amq-online-enmasse-console-rules alert test

### PR DESCRIPTION
**Pull request by obrienrobert**
# Description
https://issues.redhat.com/browse/INTLY-7157

Removal of the `redhat-rhmi-amq-online-enmasse-console-rules.yaml` alerts exist test

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Verification
- Execute the functional tests against a cluster using this branch - you may have to comment out some of the other test cases in order to solely test the `alerts_exist` test case (please ask if unsure) 
- Confirm that the test **does not** fail with the following message:
```
File Name: redhat-rhmi-amq-online-enmasse-console-rules.yaml
Missing Rules: []
Unexpected Rules: []
Status: File expected but not found
```

### CODE REVIEW

**Comment by obrienrobert** [comment]
@davidffrench would it be possible for you to take a look at this, if you have time, please?

**Comment by matskiv** [comment]
```
 {"command":"git fetch https://github.com/integr8ly/integre...d URL returned error: 504\n","time":"2020-04-23T14:00:23Z"}
{"component":"clonerefs","error":"one or more of the recor..."msg":"Failed to clone refs","time":"2020-04-23T14:00:23Z"} 
```
There seems to be some connectivity issue between PROW and GH.

**Pull request merged**
