### PR TITLE
set version based on install type

### PR DESCRIPTION
**Pull request by philbrookes**
# Description
Updated logic around updating version number in RHMI CR.

Cleaned  up logic at end of main reconcile as it was getting confusing to read.

Testing I performed locally:
- installing: toVersion: 0.1.0, version: ""
- Installed: toVersion: "", Version: 0.1.0
- Slow Upgrade pending: toVersion: 0.2.0, Version: 0.1.0
- Slow Upgrade complete: toVersion: "", Version: 0.2.0
- Fast Upgrade pending: --- too fast ---
- Fast Upgrade complete: toVersion: "", Version: 0.3.0

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by sergioifg94** [comment]
:eyes:

**Review by sergioifg94 — APPROVED** [review]
/lgtm

**Review by briangallagher — COMMENTED** [review]
Steps confirmed

**Comment by philbrookes** [comment]
Failed before getting to the e2e tests.

/retest

**Pull request merged**
