### PR TITLE
3scale update to 0.8.3+0.1645735250.p

### PR DESCRIPTION
**Pull request by fh-automatron**
Update 3scale manifest to 0.8.3+0.1645735250.p 

This is an automatically generated branch to track the '0.8.3+0.1645735250.p' version of the '3scale' OLM manifests.
This branch will be automatically updated with any changes related to this version until it finally GAs. 

Changes required to fix installation issues should be applied to this branch following the usual [PR Workflow](https://github.com/integr8ly/delorean/blob/master/docs/integrealy-ci/prow-pr-workflow.md)

More details about the Early Warning System that generated this can be found [here](https://github.com/integr8ly/delorean/tree/master/docs/ews)

## To verify
- Install RHOAM via olm from this index image: ```quay.io/mstoklus/integreatly-index:1.18.2```
- Once installed, setup workload web app on your cluster
- Update catalog source to point to a new index - ```quay.io/mstoklus/integreatly-index:1.19.0```
- Approve the upgrade
- Wait for upgrade to complete and check the total downtime in 3scale (should not be longer than 2mins)
- Confirm upgrade completed successfully. 

## Type of change

- [X] Product Update

## Checklist
- [ ] Older product manifests (N-2) have been removed
- [ ] Operator and Product Versions are updated correctly
- [ ] Go Modules are updated if required

### CODE REVIEW

**Comment by MStokluska** [comment]
Server unable to handle requests 
/test rhoam-e2e

**Comment by KevFan** [comment]
Verified upgrade completed successfully 

Screenshot from 2022-03-22 12-38-51
Screenshot from 2022-03-22 12-38-43

**Comment by KevFan** [comment]
Verified fresh installation completing successfully

/test rhoam-e2e

**Comment by MStokluska** [comment]
@laurafitzgerald @KevFan I've updated the deployment name in the CSV to match our test case in https://github.com/integr8ly/integreatly-operator/blob/master/test/e2e/suite_test.go#L164
We had two options here, either update the test case or update the CSV - since we are updating the CSV anyway, I decided to change the CSV value.

Good spot @laurafitzgerald !

**Pull request merged**
