### PR TITLE
MGDAPI-10370 Update RHSSO operator to v12.0.1

### PR DESCRIPTION
**Pull request by CathalOConnorRH**
## Description
Bump RHSSO operator version to v12.0.1 and operand to 7.4-16

## Verification
1. Install RHOAM/RHMI from this branch and verify operand and operator versions match the above version number.
2. Ensure RHSSO has started correctly as there is a change to the authdelay jar in this PR and it must be added to the classpath.
3. Verify version 1.0.2 of the authdelay.jar has been downloaded in the extensions container of the keycloak pod

### CODE REVIEW

**Comment by philbrookes** [comment]
Can I just confirm that upgrades of this operator were also tested? Don't see it in the verification steps.

**Comment by briangallagher** [comment]
> Can I just confirm that upgrades of this operator were also tested? Don't see it in the verification steps.

I didn't test that. I'll do that now and report back

**Comment by briangallagher** [comment]
@philbrookes Confirming upgrades work as expected

**Pull request merged**
