### PR TITLE
Revert "update amo to v1.1.6"

### PR DESCRIPTION
**Pull request by davidffrench**
This reverts commit 40173ddcd7b62fa104aa477baa841c7750fb0da6.

Reverting https://github.com/integr8ly/integreatly-operator/pull/706

### CODE REVIEW

**Comment by davidffrench** [comment]
@philbrookes This needs to be merged before the final release of 2.2.0 is cut in the morning using the release pipeline.

cc @david-martin @philbrookes

**Comment by david-martin** [comment]
/approve

Reverting until 2.2.0 cut.
Will reopen then cc @pb82  @obrienrobert

**Pull request merged**
