### PR TITLE
MGDAPI-1044 - Rescale 3scale DC if failed

### PR DESCRIPTION
**Pull request by KevFan**
# Description

Jira:
* https://issues.redhat.com/browse/MGDAPI-1044

# Verification
* Install RHOAM from master
* Manually cause system-app dc to fail
  * Rollout new dc 
    ```
    oc rollout latest dc/system-app -n redhat-rhoam-3scale
    ```
  * Delete the rolled out `system-app-4-pre-hook` pod before it completes
    ```
    oc delete pods system-app-4-pre-hook -n redhat-rhoam-3scale
    ```
  * Verify `system-app-deploy` pod is an error state 
    ```
     oc get pods system-app-4-deploy -n redhat-rhoam-3scale
    ```
  * Verify `system-app` deployment config has a 'False' condition due to ReplicationController failed progressing
    ```
     oc get dc system-app -n redhat-rhoam-3scale -o json | jq '.status.conditions'
    ```
* Checkout this branch and run operator
* Verify a new system-app deployment is rolled out due to failed condition in log
```
WARN[2021-03-10T15:56:35Z] 3scale dc in a failed condition, rolling out new deployment  dc=system-app product=3scale
```
* Verify rollout completes successfully 
```
oc get pods -n redhat-rhoam-3scale | grep system-app
```
* Verify RHOAM CR is in complete state
```
oc get rhmi rhoam -o json | jq '.status.stage'
```
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by Boomatang** [comment]
As a side note you don't have to use `jq` to get the status. `oc` has  a json path which can be used `oc get RHMI rhoam -n redhat-rhoam-operator -o jsonpath={.status.stage}`

**Comment by Boomatang** [comment]
I did not manage to see the log but the install did fix it's can come back to a working state.
/lgtm

**Comment by KevFan** [comment]
Thanks @Boomatang :+1: 
/test e2e
/test rhoam-e2e

**Pull request merged**
