### PR TITLE
release 1.11.0

### PR DESCRIPTION
**Pull request by philbrookes**
- moved monitoring to it's own stage, ahead of all the products.

### CODE REVIEW

**Comment by pawelpaszki** [comment]
looks ok. I will approve after the e2e test will eventually pass

**Comment by mikenairn** [comment]
/hold

Release will be re-created after https://github.com/integr8ly/integreatly-operator/pull/175 and https://github.com/openshift/release/pull/5801 are merged. At which point the e2e test would be expected to pass.

**Comment by philbrookes** [comment]
Well, I've just verified this on my own cluster, and it's fine, so I'm inclined to merge this despite the failing e2e test.

**Comment by pawelpaszki** [comment]
+1 on that. let's merge it

**Pull request merged**
