### PR TITLE
9500 cr version on upgrade

### PR DESCRIPTION
**Pull request by briangallagher**
# Description
An RHMI CR has a Version field and a ToVersion field. The ToVersion field is set during upgrade. Post upgrade, the version field is set to ToVersion. On automatic upgrades (meaning the InstallPlan is auto approved) the logic to set ToVersion is done during Subscription Reconcile. 
This code change caters for the manual (meaning the InstallPlan is manually approved) scenario. 

## How to verify
Install and then upgrade RHMI manually and automatically. Verify that the version field on the CR is set to the correct version before and after the upgrade.
```
oc -n redhat-rhmi-operator get rhmi rhmi -o yaml | grep ersion
```

### Manually
See [deploying RHMI with bundle format](https://github.com/integr8ly/integreatly-operator/blob/master/README.md#deploying-to-a-cluster-with-olm-and-the-bundle-format) on how to install and then upgrade

### Automatically 
Follow the same procedure as above but do not approve the install plan. Instead, adjust `rhmiconfig` cr to force an automatic install. Set:
```spec.upgrade.notBeforeDays = 1```
```spec.upgrade.waitForMaintenance = false```

Wait for upgrade, see:
```status.upgrade.scheduled.for```

### CODE REVIEW

**Comment by MStokluska** [comment]
it looks good to merge, tested the functionality on a cluster and it works as expected. Great job!
/lgtm

**Comment by philbrookes** [comment]
/override ci/prow/e2e
Verified locally by @MStokluska

**Pull request merged**
