### PR TITLE
update Fuse on Openshift to 7.6

### PR DESCRIPTION
**Pull request by briangallagher**
# Description
Upgrade Fuse on OpenShift to version 7.6.
Fuse on OpenShift does not have an operator and installation and reconciliation are done in a unique way. 
The install in the RHMI operator is essentially as documented here:
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.6/html-single/fuse_on_openshift_guide/index#install-fuse-on-openshift4

# How to Verify

- Install RHMI
- Verify that all templates are installed as documented in above reference.
- Verify that the samples operator has skipped the templates:
- oc get configs.samples.operator.openshift.io -n openshift-cluster-samples-operator -o yaml

### CODE REVIEW

**Comment by davidffrench** [comment]
👀

**Comment by briangallagher** [comment]
@davidffrench 

I should have made this clearer. 

I created the file lists from the files that exist in the repository.
The tags used below are as specified in the documentation.

For Spring Boot 2 Templates:
https://github.com/jboss-fuse/application-templates/tree/application-templates-2.1.0.fuse-sb2-760039-redhat-00001/quickstarts

For Console Templates
https://github.com/jboss-fuse/application-templates/tree/application-templates-2.1.0.fuse-760043-redhat-00001

For Quick Start Templates
https://github.com/jboss-fuse/application-templates/tree/application-templates-2.1.0.fuse-760043-redhat-00001

With regard to the 3 additional templates on cluster, not mentioned in docs:
I'm not sure where these come from as they are not in the list in the [fuseonopenshift reconciler](https://github.com/briangallagher/integreatly-operator/blob/d17cdbcbb97c8189901de65992609b4ccbaf67c8/pkg/products/fuseonopenshift/reconciler.go#L50-L93).
Is it possible something else is adding these? We append rather than overwrite those fields. 

With regard to the missed skipped Templates on cluster, mentioned in docs:
This file does not exist in the repo (See Spring Boot 2 above) so I can only assume docs are wrong? 

WDYT?

**Comment by davidffrench** [comment]
> @davidffrench
> 
> I should have made this clearer.
> 
> I created the file lists from the files that exist in the repository.
> The tags used below are as specified in the documentation.
> 
> For Spring Boot 2 Templates:
> https://github.com/jboss-fuse/application-templates/tree/application-templates-2.1.0.fuse-sb2-760039-redhat-00001/quickstarts
> 
> For Console Templates
> https://github.com/jboss-fuse/application-templates/tree/application-templates-2.1.0.fuse-760043-redhat-00001
> 
> For Quick Start Templates
> https://github.com/jboss-fuse/application-templates/tree/application-templates-2.1.0.fuse-760043-redhat-00001
> 
> With regard to the 3 additional templates on cluster, not mentioned in docs:
> I'm not sure where these come from as they are not in the list in the [fuseonopenshift reconciler](https://github.com/briangallagher/integreatly-operator/blob/d17cdbcbb97c8189901de65992609b4ccbaf67c8/pkg/products/fuseonopenshift/reconciler.go#L50-L93).
> Is it possible something else is adding these? We append rather than overwrite those fields.
This is very possible, I believe you are right and I don't it is something we need to worry about but would be nice to ask the Fuse Online team to see what they say.

> 
> With regard to the missed skipped Templates on cluster, mentioned in docs:
> This file does not exist in the repo (See Spring Boot 2 above) so I can only assume docs are wrong?
> 
> WDYT?
Very likely a docs issue here. Definitely want to reach out to Fuse Online and see if it is. You can get them on the syndesis chat which looks like you are already in. 

Once we have answers back on these, this is good to merge.

**Comment by briangallagher** [comment]
question asked, waiting on reply

**Comment by briangallagher** [comment]
@davidffrench  @philbrookes  I've reached out by email and chat and I've received no replies. I think we can push this through. 
I think the potential impact of the above issue is very small.

**Comment by philbrookes** [comment]
@briangallagher agreed, let's get this merged.

**Pull request merged**
