### PR TITLE
MGDAPI-2160 - adding update to config map for redis service updates + CRO bump to v0.28.0

### PR DESCRIPTION
**Pull request by laurafitzgerald**
# Description
JIRA: https://issues.redhat.com/browse/MGDAPI-2160
Adding first steps to update the cloud-resources-aws-strategies config map redis type with a serviceUpdates entry where a list of strings can be added which cro would then apply.
Integreatly-operator will ad a list f hard-coded service versions to CRO config map. It should also preserve versions added manually.

## Verification steps
- Install RHOAM onto a cluster with clusterStorage = false
- Check the cloud-resources-aws-strategies config map in redhat-rhoam-operator NS - redis config for production should contain:
`"serviceUpdates": ["elasticache-20210615-002"]`
- Verify that CRO v0.28.0 was installed
- Verify that CRO pod doesn't crash (0 restarts)
- Check logs of the CRO pod - there should not be any errors related to Redis provisioning or reconciliation

_Description updated by @matskiv on Fri July 2nd._

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by austincunningham** [comment]
## Verified
- Config map cloud-resources-aws-strategies updated
```yaml
data:
  _network: '{"production":{"createStrategy":{"CidrBlock":""}}}'
  blobstorage: '{ "production": { "createStrategy": {}, "deleteStrategy": {} } }'
  postgres: >-
    {"development":{"region":"","createStrategy":{},"deleteStrategy":{},"serviceUpdates":null},"production":{"region":"","createStrategy":{"AllocatedStorage":null,"AutoMinorVersionUpgrade":null,"AvailabilityZone":null,"BackupRetentionPeriod":null,"CharacterSetName":null,"CopyTagsToSnapshot":null,"DBClusterIdentifier":null,"DBInstanceClass":null,"DBInstanceIdentifier":null,"DBName":null,"DBParameterGroupName":null,"DBSecurityGroups":null,"DBSubnetGroupName":null,"DeletionProtection":null,"Domain":null,"DomainIAMRoleName":null,"EnableCloudwatchLogsExports":null,"EnableIAMDatabaseAuthentication":null,"EnablePerformanceInsights":null,"Engine":null,"EngineVersion":null,"Iops":null,"KmsKeyId":null,"LicenseModel":null,"MasterUserPassword":null,"MasterUsername":null,"MaxAllocatedStorage":null,"MonitoringInterval":null,"MonitoringRoleArn":null,"MultiAZ":null,"NcharCharacterSetName":null,"OptionGroupName":null,"PerformanceInsightsKMSKeyId":null,"PerformanceInsightsRetentionPeriod":null,"Port":null,"PreferredBackupWindow":"03:01-04:01","PreferredMaintenanceWindow":"thu:02:00-thu:03:00","ProcessorFeatures":null,"PromotionTier":null,"PubliclyAccessible":null,"StorageEncrypted":null,"StorageType":null,"Tags":null,"TdeCredentialArn":null,"TdeCredentialPassword":null,"Timezone":null,"VpcSecurityGroupIds":null},"deleteStrategy":{},"serviceUpdates":null}}
  redis: >-
    {"development":{"createStrategy":{},"deleteStrategy":{},"region":"","serviceUpdates":null},"production":{"createStrategy":{"AtRestEncryptionEnabled":null,"AuthToken":null,"AutoMinorVersionUpgrade":null,"AutomaticFailoverEnabled":null,"CacheNodeType":null,"CacheParameterGroupName":null,"CacheSecurityGroupNames":null,"CacheSubnetGroupName":null,"Engine":null,"EngineVersion":null,"GlobalReplicationGroupId":null,"KmsKeyId":null,"MultiAZEnabled":null,"NodeGroupConfiguration":null,"NotificationTopicArn":null,"NumCacheClusters":null,"NumNodeGroups":null,"Port":null,"PreferredCacheClusterAZs":null,"PreferredMaintenanceWindow":"thu:02:00-thu:03:00","PrimaryClusterId":null,"ReplicasPerNodeGroup":null,"ReplicationGroupDescription":null,"ReplicationGroupId":null,"SecurityGroupIds":null,"SnapshotArns":null,"SnapshotName":null,"SnapshotRetentionLimit":null,"SnapshotWindow":"03:01-04:01","Tags":null,"TransitEncryptionEnabled":null,"UserGroupIds":null},"deleteStrategy":{},"region":"","serviceUpdates":["elasticache-20210615-002"]}}
```

- CRO v0.28.0 installed

``` yaml
  stages:
    bootstrap:
      name: bootstrap
      phase: completed
    cloud-resources:
      name: cloud-resources
      phase: completed
      products:
        cloud-resources:
          host: ''
          name: cloud-resources
          operator: 0.28.0
          status: completed
          version: 0.28.0
```
- No CRO operator pod restarts, or events
- Redis are created for 3scale, and no errors in the  CRO logs regarding redis creation or reconcile

@matskiv  No applyImmediately flag set in the redis CR, presume we are not doing this as part of the patch release ? 
```bash
time="2021-07-02T14:50:57Z" level=info msg="there are elasticache service update actions: 0 available"
```

**Comment by matskiv** [comment]
> No applyImmediately flag set in the redis CR, presume we are not doing this as part of the patch release ?
yes, that's correct. CRO will apply updates based on the `serviceUpdates` field or `applyImmediately` (only critical security updates). For now we will use only the `serviceUpdates` option.

**Comment by CathalOConnorRH** [comment]
verifed for RHMI, no issues. Looks good.

**Pull request merged**
