### PR TITLE
MGDAPI-2101 - OSD Trial Quota Support

### PR DESCRIPTION
**Pull request by KevFan**
# Description

Read `trial-quota` addon paramter and use that as quota value if normal quota value is not present

Order of prefernce is as follows for quota value:

1. `addon-managed-api-service` addon param
2. `trial-quota` addon param
3. `QUOTA` environment variable

Jira:
* https://issues.redhat.com/browse/MGDAPI-2101

### Verify install correct with trial quota parameter
* Provision Cluster
  *  (Optional) OSD Trial Cluster
* Checkout this branch 
* Run install using `trial-quota` addon parameter
```
make cluster/prepare/local
# Delete normal quota addon parameter and apply trial quota addon parameter
oc delete secret addon-managed-api-service-parameters -n redhat-rhoam-operator
make cluster/prepare/quota/trial
# Run operator
make code/run
```
* Verify installation completes sucessfully and uses the `0` config
```
oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq -r '.status'
```

image

### Verify preference of normal addon quota over trial addon quota
* Apply normal quota addon parameter to addon secret
```
# Append normal quota parameter secret - with a value of 1 - base64 encoded
oc get secret addon-managed-api-service-parameters -n redhat-rhoam-operator -o json | jq '.data += {"addon-managed-api-service": "MQ=="}' | oc apply -f -
```
* Verify quota change is picked up and uses `1` quota value and completes successfully
```
oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq -r '.status'
```

image

## Test Case 
Putting potential test case here as it can not be created before release is created as otherwise the PR would fail on the test-cases prow job

* https://gist.github.com/KevFan/1aeb07e6b924ce45ccc26e2157925625

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by matskiv** [comment]
Additional commits LGTM 👍

**Comment by KevFan** [comment]
Rebased against master due to conflicts 

/test e2e
/test rhoam-e2e

**Comment by jjkiely** [comment]
Verification: 
Install completed successfully with the 0  quota option 
```shell 
oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq -r '.status' 
```
```json
{
  "lastError": "",
  "preflightMessage": "preflight checks passed",
  "preflightStatus": "successful",
  "quota": "0",
  "stage": "complete",
  "stages": {
    "authentication": {
      "name": "authentication",
      "phase": "completed",
      "products": {
        "rhsso": {
          "host": "https://keycloak-edge-redhat-rhoam-rhsso.apps.chfan2.5fco.s1.devshift.org",
          "name": "rhsso",
          "operator": "14.0.0",
          "status": "completed",
          "version": "7.4"
        }
      }
    },
    "bootstrap": {
      "name": "bootstrap",
      "phase": "completed"
    },
    "cloud-resources": {
      "name": "cloud-resources",
      "phase": "completed",
      "products": {
        "cloud-resources": {
          "host": "",
          "name": "cloud-resources",
          "operator": "0.27.1",
          "status": "completed",
          "version": "0.27.1"
        }
      }
    },
    "monitoring": {
      "name": "monitoring",
      "phase": "completed",
      "products": {
        "middleware-monitoring": {
          "host": "",
          "name": "middleware-monitoring",
          "operator": "1.6.0",
          "status": "completed",
          "version": "1.6.0"
        },
        "monitoring-spec": {
          "host": "",
          "name": "monitoring-spec",
          "status": "completed",
          "version": "1.0"
        }
      }
    },
    "products": {
      "name": "products",
      "phase": "completed",
      "products": {
        "3scale": {
          "host": "https://3scale-admin.apps.chfan2.5fco.s1.devshift.org",
          "name": "3scale",
          "operator": "0.7.0",
          "status": "completed",
          "version": "2.10.0"
        },
        "grafana": {
          "host": "https://grafana-route-redhat-rhoam-customer-monitoring-operator.apps.chfan2.5fco.s1.devshift.org",
          "name": "grafana",
          "operator": "3.10.2",
          "status": "completed",
          "version": "3.10.2"
        },
        "marin3r": {
          "host": "",
          "name": "marin3r",
          "operator": "0.7.0",
          "status": "completed",
          "version": "0.7.0"
        },
        "rhssouser": {
          "host": "https://keycloak-redhat-rhoam-user-sso.apps.chfan2.5fco.s1.devshift.org",
          "name": "rhssouser",
          "operator": "14.0.0",
          "status": "completed",
          "version": "7.4"
        }
      }
    }
  },
  "version": "1.8.0"
}
 ```

Quota updated to "1" after patching the normal quota parameter
```shell 
oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq -r '.status'
```
```json
{
  "lastError": "",
  "preflightMessage": "preflight checks passed",
  "preflightStatus": "successful",
  "quota": "1",
  "stage": "complete",
  "stages": {
    "authentication": {
      "name": "authentication",
      "phase": "completed",
      "products": {
        "rhsso": {
          "host": "https://keycloak-edge-redhat-rhoam-rhsso.apps.chfan2.5fco.s1.devshift.org",
          "name": "rhsso",
          "operator": "14.0.0",
          "status": "completed",
          "version": "7.4"
        }
      }
    },
    "bootstrap": {
      "name": "bootstrap",
      "phase": "completed"
    },
    "cloud-resources": {
      "name": "cloud-resources",
      "phase": "completed",
      "products": {
        "cloud-resources": {
          "host": "",
          "name": "cloud-resources",
          "operator": "0.27.1",
          "status": "completed",
          "version": "0.27.1"
        }
      }
    },
    "monitoring": {
      "name": "monitoring",
      "phase": "completed",
      "products": {
        "middleware-monitoring": {
          "host": "",
          "name": "middleware-monitoring",
          "operator": "1.6.0",
          "status": "completed",
          "version": "1.6.0"
        },
        "monitoring-spec": {
          "host": "",
          "name": "monitoring-spec",
          "status": "completed",
          "version": "1.0"
        }
      }
    },
    "products": {
      "name": "products",
      "phase": "completed",
      "products": {
        "3scale": {
          "host": "https://3scale-admin.apps.chfan2.5fco.s1.devshift.org",
          "name": "3scale",
          "operator": "0.7.0",
          "status": "completed",
          "version": "2.10.0"
        },
        "grafana": {
          "host": "https://grafana-route-redhat-rhoam-customer-monitoring-operator.apps.chfan2.5fco.s1.devshift.org",
          "name": "grafana",
          "operator": "3.10.2",
          "status": "completed",
          "version": "3.10.2"
        },
        "marin3r": {
          "host": "",
          "name": "marin3r",
          "operator": "0.7.0",
          "status": "completed",
          "version": "0.7.0"
        },
        "rhssouser": {
          "host": "https://keycloak-redhat-rhoam-user-sso.apps.chfan2.5fco.s1.devshift.org",
          "name": "rhssouser",
          "operator": "14.0.0",
          "status": "completed",
          "version": "7.4"
        }
      }
    }
  },
  "version": "1.8.0"
  ```
  
  Test case looks good to me too except that "Evaluation" isn't spelled correctly.
  
 Overall seems to work perfectly /lgtm

**Comment by KevFan** [comment]
Thanks @jjkiely, I've updated the test case in the gist to fix the typo. Good catch :+1:

**Comment by KevFan** [comment]
Prow jobs failed due to pod pending timeout

/retest

**Pull request merged**
