### PR TITLE
Updating SendGrid test case with production references

### PR DESCRIPTION
**Pull request by pmccarthy**
# Description
Updating SendGrid test case (C16)to include steps for checking Production prometheus alerts. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Review by aidenkeating — APPROVED** [review]
Looks good 👍

**Comment by pmccarthy** [comment]
@aidenkeating would you mind adding `lgtm` to this again please?

**Pull request merged**
