### PR TITLE
Delete test case A20 because obsolete

### PR DESCRIPTION
**Pull request by b1zzu**
# Description

The test case A20 is testing a requirement that has been removed

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by trdoyle81** [comment]
My argument for keeping test cases is pertinent to one-off or version specific test cases (eg for bug fixes) and retaining the ability to rerun the test case in the future if needed (if a bug reoccured for example). However, In this case, the feature requirement has removed and therefore the test case should also be deleted (imo).

**Review by trdoyle81 — APPROVED** [review]

**Comment by b1zzu** [comment]
Good points @trepel, for the link we can fix it by using the commit sha instant of the branch name when generating the jira tasks

**Pull request merged**
