### PR TITLE
Mgdapi 3256 go 1.16 -> 1.17

### PR DESCRIPTION
**Pull request by makslion**
# Issue link
[MGDAPI-3256](https://issues.redhat.com/browse/MGDAPI-3256)

# What
Updating go version. 
This PR would also include the fix of tests that is already on master. This is done to ensure that all tests are passed on the future branch. 

# Verification steps
Review the code. 
Passing tests should be sufficient.

### CODE REVIEW

**Comment by makslion** [comment]
with #2249 merged to the feature branch I expect images to be passing. 
The `ci/prow/vendor` still will be failing as prow is configured to use 1.16 on master. However, that test is passed on the feature branch where prow uses go1.17

**Comment by makslion** [comment]
For the person that will be approving this PR. 
The `branch-ci-integr8ly-integreatly-operator-MGDAPI-3256-working-images` fails because the feature branch has uppercase letters and `ci/prow/vendor ` fails because prow is [configured](https://github.com/openshift/release/blob/master/ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml#L2-L5) for a go1.16 on master and the config will be updated automatically by a bot once this PR will be merged. 
You could see all the tests being happy on the last [PR](https://github.com/integr8ly/integreatly-operator/pull/2449) to the feature branch

**Comment by makslion** [comment]
Branch was rebased against master. The same failing checks are expected as mentioned in [this](https://github.com/integr8ly/integreatly-operator/pull/2452#issuecomment-1033906523) comment. And if AWS will be merciful - e2e should also pass.

**Comment by laurafitzgerald** [comment]
/override vendor 

` it fails because prow is configured to use go1.16 and that configuration will be updated automatically once the PR is merged`

**Comment by briangallagher** [comment]
/override branch-ci-integr8ly-integreatly-operator-MGDAPI-3256-working-images

**Pull request merged**
