### PR TITLE
MGDAPI-5663 - keycloak: v7.6.2-4

### PR DESCRIPTION
**Pull request by KevFan**
# Issue link

https://issues.redhat.com/browse/MGDAPI-5663

# What

* Bump Keycloak Operator to v7.6.2-4

# Verification steps

## Verify Upgrade
* Checkout master
* Install RHOAM
```
export LOCAL=false  
make cluster/prepare/local                                                                               
make code/run 
```
* Allow for installation to complete
* Deploy webload-web app
  * https://github.com/integr8ly/workload-web-app#rhoam-clusters
* Stop running the operator
* Checkout this branch 
* Re-run the operator
```
export LOCAL=false                                                                                     
make code/rerun 
```
* Verify keycloak operator upgrades thats places and installation completes
```
 watch "echo RHSSO; oc get csv -n redhat-rhoam-rhsso-operator; oc get pods -n redhat-rhoam-rhsso; echo "";echo "USER SSO"; oc get csv -n redhat-rhoam-user-sso-operator; oc get pods -n redhat-rhoam-user-sso; echo ""; echo "RHMI CR"; oc get rhmi rhoam -n redhat-rhoam-operator -o jsonpath='{.status.stage}'"
```
* Visit the workload web app grafana dashboard and confirm any downtime measures 
image

### CODE REVIEW

**Comment by carlkyrillos** [comment]
MGDAPI-5663-workload-app


Reviewed the changed files and confirmed that there was no downtime during the keycloak operator upgrade.

However, the operator image version for `rhsso` and `rhssouser` is still `7.6.2-3` (see screenshot), should it be `7.6.2-4` @KevFan 

MGDAPI-5663-rhoam-status

**Comment by KevFan** [comment]
Thanks @carlkyrillos. Yes, I've updated the operator version to `7.6.2-4` now 👍

**Comment by carlkyrillos** [comment]
Reviewed latest changes which fixed version mismatch, already completed verification steps
/lgtm

**Pull request merged**
