### PR TITLE
MGDAPI-227

### PR DESCRIPTION
**Pull request by martinhesko**
# Description
Added a new script that will be used to deploy hyperfoil on an EC2 instance

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by trepel** [comment]
reviewing. I haven't verified fully yet. I tried only running the command from the script in sequence, I did not try to run the script itself, but it seems it is working.
Waiting with lgtm to see if this script is indeed the way to go. Other investigations around running Hyperfoil controller on Jenkins slave directly are in progress.

**Comment by philbrookes** [comment]
If this is still relevant, please re-open.

**Pull request closed without merging**
