### PR TITLE
Support uninstallation by namespace label for MGDAPI addon

### PR DESCRIPTION
**Pull request by sergioifg94**
# Description

Update and refactor logic in namespace controller to check for the label set for the MGDAPI add-on when the add-on is deleted, which triggers the service uninstall.

## Verification steps

1. Install MGDAPI from this PR
2. Wait for the installation to complete
3. Patch the `redhat-rhmi-operator` namespace object, adding the following label:
    ```yaml
    api.openshift.com/addon-managed-api-service-delete: 'true'
    ```
4. Verify that the uninstall process begins

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by KevFan** [comment]
Verified 
/lgtm

**Comment by sergioifg94** [comment]
Thanks @KevFan if it keeps failing I'm going to rebase and hopefully that fixes it

**Pull request merged**
