### PR TITLE
fix: backup-restore script typo

### PR DESCRIPTION
**Pull request by psturc**
# Description
Seen when working on https://issues.redhat.com/browse/MGDAPI-267

### CODE REVIEW

**Review by sergioifg94 — CHANGES_REQUESTED** [review]
I was aware of this typo, but I thought it had already been fixed.

Looks good, just needs to be updated in the first function invocation: https://github.com/integr8ly/integreatly-operator/pull/1225/files#diff-6d48514803dd9bb39c85d864718b7311R46

**Comment by psturc** [comment]
thanks for review, it should be fixed now

**Comment by sergioifg94** [comment]
There's another error that @MStokluska brought to my attention. In [this line](https://github.com/psturc/integreatly-operator/blob/patch-6/test/scripts/backup-restore/postgres.sh#L171), it's `dump_after.sql` instead of `database_after.sql`

Seems like this test might still be a bit flaky anyways, so I'll try to verify it and ensure it works well

**Pull request merged**
