### PR TITLE
INTLY-6747 Add cluster monitoring label to federate ns

### PR DESCRIPTION
**Pull request by david-martin**
# Description
https://issues.redhat.com/browse/INTLY-6747
Follow up on #607 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by pb82** [comment]
@david-martin change looks good. At some point we might consider directly passing in a list of labels instead of flags. But this should get the job done.

**Comment by david-martin** [comment]
Looks correct
```
oc describe ns redhat-rhmi-middleware-monitoring-federate |grep -A 5 Labels
Labels:       integreatly=true
              integreatly.org/installation-uid=e0d14db7-ead1-4cb4-8484-f617155e2b52
              openshift.io/cluster-monitoring=true
```

**Comment by david-martin** [comment]
Verified in prom.

RHMI Prom:
```
ALERTS{alertname="DeadMansSwitch",alertstate="firing",severity="none"}
```

Cluster prom:

```



ALERTS{alertname="DeadMansSwitch",alertstate="firing",endpoint="upstream",job="prometheus-service",namespace="redhat-rhmi-middleware-monitoring-operator",pod="prometheus-application-monitoring-0",prometheus="redhat-rhmi-middleware-monitoring-operator/application-monitoring",prometheus_replica="prometheus-application-monitoring-0",service="prometheus-service",severity="none"} | 1
ALERTS{alertname="UsingDeprecatedAPIExtensionsV1Beta1",alertstate="firing",client="syndesis-operator/v0.0.0 (linux/amd64) kubernetes/$Format",code="200",component="apiserver",contentType="application/json",endpoint="https",group="extensions",instance="10.0.142.246:6443",job="apiserver",namespace="default",resource="daemonsets",scope="namespace",service="kubernetes",severity="warning",verb="LIST",version="v1beta1"} | 1
ALERTS{alertname="UsingDeprecatedAPIExtensionsV1Beta1",alertstate="firing",client="syndesis-operator/v0.0.0 (linux/amd64) kubernetes/$Format",code="200",component="apiserver",contentType="application/json",endpoint="https",group="extensions",instance="10.0.142.246:6443",job="apiserver",namespace="default",resource="deployments",scope="namespace",service="kubernetes",severity="warning",verb="LIST",version="v1beta1"} | 1
ALERTS{alertname="UsingDeprecatedAPIExtensionsV1Beta1",alertstate="firing",client="syndesis-operator/v0.0.0 (linux/amd64) kubernetes/$Format",code="200",component="apiserver",contentType="application/json",endpoint="https",group="extensions",instance="10.0.142.246:6443",job="apiserver",namespace="default",resource="networkpolicies",scope="namespace",service="kubernetes",severity="warning",verb="LIST",version="v1beta1"} | 1
ALERTS{alertname="UsingDeprecatedAPIExtensionsV1Beta1",alertstate="firing",client="syndesis-operator/v0.0.0 (linux/amd64) kubernetes/$Format",code="200",component="apiserver",contentType="application/json",endpoint="https",group="extensions",instance="10.0.142.246:6443",job="apiserver",namespace="default",resource="replicasets",scope="namespace",service="kubernetes",severity="warning",verb="LIST",version="v1beta1"} | 1
ALERTS{alertname="Watchdog",alertstate="firing",severity="none"}


```

**Comment by david-martin** [comment]
OCM showing the federated alert
image

**Comment by david-martin** [comment]
/retest

Test flake already logged

**Pull request merged**
