### PR TITLE
MGDAPI-1028 - Add cluster infra id as part of alert email subject

### PR DESCRIPTION
**Pull request by KevFan**
# Description

For CSSRE, it would nice to have the cluster id as part of the subject field in the emails sent by alertmanager to help them filter the alerts per cluster

Jira:
* https://issues.redhat.com/browse/MGDAPI-822
## Short Verification
* Checkout this branch and install RHOAM
```
export INSTALLATION_TYPE=managed-api
make cluster/prepare/local
make code/run
```
* Check alertmanager config in `alertmanager-application-monitoring` secret in `redhat-rhoam-middleware-monitoring-operator` namespace and verify that the your cluster infra id is used as part of the reciever email_configs

Screenshot from 2021-01-07 14-42-40
* Check config is loaded properly and reflected in alertmanager status page

Screenshot from 2021-01-07 14-42-10

## Longer Verification
* Install as per above
* Update the RHOAM CR alerting emails addresses to your own email address
* Update `redhat-rhoam-smtp` with valid credentials (reach out if verifying to get credentials)
* Once smtp credential have been reconciled to alertmanager. Trigger alerts to fire
  * Scale down RHSSO operator and RHSSO stateful set
  ```
  oc scale deployment keycloak-operator --replicas=0 -n redhat-rhoam-rhsso-operator
  oc scale statefulset keycloak --replicas=0 -n redhat-rhoam-rhsso
  ```
* Verify alert email contains the cluster infra id as part of email subject once received

image

- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by MStokluska** [comment]
Verified it, good job @KevFan, this is the email I got from the alert manager: 
image

If this is what @alanmoran was looking for then it's /lgtm

**Comment by MStokluska** [comment]
/lgtm

Sorry, my multiline lgtm did not work in previous comment!

**Review by alanmoran — APPROVED** [review]

**Pull request merged**
