### PR TITLE
3scale update to 0.11.3-mas

### PR DESCRIPTION
**Pull request by fh-automatron**
Update 3scale bundle to 0.11.3-mas

This is an automatically generated branch to track the '0.11.3-mas' version of the '3scale' bundles.
This branch will be automatically updated with any changes related to this version until it finally GAs.

Changes required to fix installation issues should be applied to this branch following the usual [PR Workflow](https://github.com/integr8ly/delorean/blob/master/docs/integrealy-ci/prow-pr-workflow.md)

More details about the Early Warning System that generated this can be found [here](https://github.com/integr8ly/delorean/tree/master/docs/ews)

## Type of change

- [X] Product Update

## Checklist
- [ ] Operator and Product Versions are updated correctly
- [ ] Go Modules are updated if required

### Installation
- checkout this branch
- install locally with  the follow commands
```bash
make cluster/prepare/local
make code/run
```
- once the install is finished confirm that 3scale in on version mas-0.11.3
```bash
oc get rhmi rhoam -oyaml | yq '.status.stages.installation.products.3scale'
host: https://3scale-admin.apps.aucunnin.b96o.s1.devshift.org
name: 3scale
operator: 0.11.3-mas
status: completed
version: 2.13.0
```

### Upgrade
- Prepare the cluster
```bash
INSTALLATION_TYPE=managed-api LOCAL=false make cluster/prepare/local
INSTALLATION_TYPE=managed-api LOCAL=false USE_CLUSTER_STORAGE=true make deploy/integreatly-rhmi-cr.yml
```

- Install master via the following catalogsource
```bash
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhmi-operators 
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/austincunningham/managed-api-service-index:1.34.0
EOF
```
- Install RHOAM via the operator hub and wait for the install to finish
- Start the upgrade by updating the image in the catalogSource to `quay.io/austincunningham/managed-api-service-index:1.35.0` 
```bash
oc edit catalogsource rhmi-operators --namespace openshift-marketplace
```
- you will need to approve the upgrade of rhoam. 
- The upgrade should proceed and once complete confirm that the 3scale operator is upgraded
```bash
oc get rhmi rhoam -oyaml | yq '.status.stages.installation.products.3scale'
host: https://3scale-admin.apps.aucunnin.b96o.s1.devshift.org
name: 3scale
operator: 0.11.3-mas
status: completed
version: 2.13.0
```

### CODE REVIEW

**Comment by austincunningham** [comment]
ci/prow/manifest  fails because of the mirrormapping file. 
/test rhoam-e2e multitenant-rhoam-e2e

**Comment by adam-cattermole** [comment]
This is expected for pre-release images - once the image is GA'd EWS will commit a new update to this branch with the public images and the tests _should_ pass - I'll watch out for this

**Comment by carlkyrillos** [comment]
Reviewed changes and completed verification steps without issue
/lgtm

**Pull request merged**
