### PR TITLE
fix: tests: A18, A25

### PR DESCRIPTION
**Pull request by psturc**
# Description

Fix (workaround) for a flaky tests A18 and A25
https://issues.redhat.com/browse/MGDAPI-395
https://issues.redhat.com/browse/MGDAPI-394

## A18
This test sometimes fails on an error:
```
    TestIntegreatly/Integreatly_Happy_Path_Tests/A18_-_Verify_RHMI_Config_CRs_Successful: rhmi_config.go:310: Expected error to be nil. Got Operation cannot be fulfilled on rhmiconfigs.integreatly.org "test-rhmi-config": the object has been modified; please apply your changes to the latest version and try again
```
that happens between the mutations of RHMIconfig CR

### Fix description
I've put the `verifyRHMIConfigValidation` function calls inside `wait.Poll` method to keep retrying the mutation until it finally passed without an error.

## A25
This test was failing on multi-az cluster due to hardcoded number of route tables a cluster VPC should have

### Fix description
Fixed by determining the number of route tables by summing up number of AZs the cluster is using (1 private route table per AZ) + 1 public route table

Screenshot 2020-10-27 at 15 10 39

# Verification
```
go clean -testcache && MULTIAZ=true go test -v ./test/functional -run="//(^A18)|(^A25)"
```
(already tested against single-az and multi-az cluster)

### CODE REVIEW

**Comment by KevFan** [comment]
Looks good, I think it would be good to also add a poll at:
* https://github.com/integr8ly/integreatly-operator/blob/master/test/common/rhmi_config.go#L222-L247

as looks like to fail at this point also :thinking: 
* https://search.ci.openshift.org/?search=Error+updating+RHMIConfig+instance%3A+Operation+cannot+be+fulfilled+on+rhmicon&maxAge=336h&context=1&type=build-log&name=integr8ly-integreatly-operator-master-e2e&maxMatches=5&maxBytes=20971520&groupBy=job

The changes should fix flake at  https://search.ci.openshift.org/?search=Expected+error+to+be+%22Forbidden%22&maxAge=336h&context=1&type=build-log&name=integr8ly-integreatly-operator-master-e2e&maxMatches=5&maxBytes=20971520&groupBy=job but may still fail without the above poll :thinking:

**Comment by psturc** [comment]
@KevFan  thanks for your review, I'll address this in a next commit and will also include https://github.com/integr8ly/integreatly-operator/pull/1267 into this PR

**Pull request merged**
