### PR TITLE
MGDAPI-3208 Revert "MGDAPI-3192"

### PR DESCRIPTION
**Pull request by austincunningham**
Reverts integr8ly/integreatly-operator#2329

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@austincunningham we don't need e2e tests to pass on master anymore. Tbh I thought they were removed from the config recently by @psturc

**Comment by psturc** [comment]
> @austincunningham we don't need e2e tests to pass on master anymore. Tbh I thought they were removed from the config recently by @psturc

That PR is still up https://github.com/openshift/release/pull/24203 (due to issue around operator image we were discussing on Friday)

**Comment by austincunningham** [comment]
@laurafitzgerald needed to reword the commit message anyway will not run the rhmi e22 again

/test rhoam-e2e

**Comment by carlkyrillos** [comment]
Compared reverted files to the changes introduced in #2329 and confirmed that all code changes were reverted. PR passed all automated checks.

/lgtm

**Pull request merged**
