### PR TITLE
Automate backup and restore for rhsso

### PR DESCRIPTION
**Pull request by MStokluska**
# Description
I've used a script recently created by @sergioifg94 to also automate rhsso Postgres backup and restore.
Addresses ticket https://issues.redhat.com/browse/INTLY-9981

# Verification steps
## Pre-requisites:
  - BYOC cluster
  - The AWS CLI configured with the credentials for the cluster

## Perform the following steps
- Install RHMI with `useClusterStorage` set to false
- Wait for installation to complete
- Create the testing IdP

```
 PASSWORD=Password1 ./scripts/setup-sso-idp.sh
```
Perform the J07 test and verify that it's completed successfully

### CODE REVIEW

**Comment by briangallagher** [comment]
@MStokluska Might be worth putting a note to say this SOP will not work with managed-3scale (managed-api) install type.
And maybe provide an alternative approach. (such as creating a temp postgres).

Also, the table names are singular (client and realm as appose to clients and realms)

**Comment by MStokluska** [comment]
@briangallagher thanks a lot for the review, I've updated the instructions to include a temporary throwaway postgres instance.

**Pull request merged**
