### PR TITLE
MGDAPI-4456 Fix installation stage watches for J03

### PR DESCRIPTION
**Pull request by Boomatang**
# Issue link

https://issues.redhat.com/browse/MGDAPI-4456

# What

Fix watches on installation stages

# Verification steps

Test on both managed-api and multitenant-managed-api.

* Install the operator for the installation type
* Follow the test case for [J03B](https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md)
* Expected result: test case should pass for insatallation type.

Repeated above steps for each installation type.

### CODE REVIEW

**Comment by KevFan** [comment]
Looks like there is a finalizer on `DiscoveryService` in the `redhat-rhoam-3scale` namespace that is preventing it from being deleted

image

It's deleted once the marin3r operator is restored but probably good to manually delete the finalizer which might make the test complete slightly faster since the 3scale namespace can be restored sooner 🤔

**Comment by Boomatang** [comment]
This is a bit out of scope for the Jira, but I can see the improvement that it cause and you found the underlining resource with the issue. So I will do some updates here.

**Comment by Boomatang** [comment]
The termination of the 3scale namespace is happening much faster with the finalizers being removed on the discovery service. It has not made much of a speed improvement but what it has done is made the logs line up more with what is actually happening to the namespaces.

**Pull request merged**
