### PR TITLE
Intly 4153 monitoring unit tests

### PR DESCRIPTION
**Pull request by david-martin**
https://issues.jboss.org/browse/INTLY-4153

These tests are mostly based on the mobilesecurityservice unit tests, but adapted for monitoring where necessary

### CODE REVIEW

**Comment by david-martin** [comment]
> Coverage decreased (-0.8%) to 59.237%

This makes no sense. There are no new files, other than a test file that covers code that wasn't covered before.
I'm going to look into this.

**Comment by david-martin** [comment]
> Coverage increased (+1.3%) to 61.39%

That's better.

/assign @damienomurchu
/assign @StevenTobin

**Comment by davidkirwan** [comment]
```
src/github.com/integr8ly/integreatly-operator (INTLY-4153_monitoring_unit_tests)$ make test/unit
...
=== RUN   TestReconciler_config
=== RUN   TestReconciler_config/test_error_on_failed_config
=== RUN   TestReconciler_config/test_namespace_is_set_without_fail
=== RUN   TestReconciler_config/test_subscription_phase_with_error_from_mpm
--- PASS: TestReconciler_config (0.00s)
    --- PASS: TestReconciler_config/test_error_on_failed_config (0.00s)
    --- PASS: TestReconciler_config/test_namespace_is_set_without_fail (0.00s)
    --- PASS: TestReconciler_config/test_subscription_phase_with_error_from_mpm (0.00s)
=== RUN   TestReconciler_reconcileCustomResource
=== RUN   TestReconciler_reconcileCustomResource/Test_reconcile_custom_resource_returns_success_on_successful_create
time="2019-11-21T12:15:24Z" level=info msg="Reconciling Monitoring Components"
time="2019-11-21T12:15:24Z" level=info msg="The operation result for monitoring middleware-monitoring was created"
=== RUN   TestReconciler_reconcileCustomResource/Test_reconcile_custom_resource_returns_failed_on_unsuccessful_create
time="2019-11-21T12:15:24Z" level=info msg="Reconciling Monitoring Components"
--- PASS: TestReconciler_reconcileCustomResource (0.00s)
    --- PASS: TestReconciler_reconcileCustomResource/Test_reconcile_custom_resource_returns_success_on_successful_create (0.00s)
    --- PASS: TestReconciler_reconcileCustomResource/Test_reconcile_custom_resource_returns_failed_on_unsuccessful_create (0.00s)
=== RUN   TestReconciler_fullReconcile
=== RUN   TestReconciler_fullReconcile/test_successful_reconcile
time="2019-11-21T12:15:24Z" level=info msg="Phase: completed ReconcileNamespace"
time="2019-11-21T12:15:24Z" level=info msg="reconciling subscription integreatly-monitoring from channel integreatly in namespace: middleware-monitoring"
time="2019-11-21T12:15:24Z" level=info msg="integreatly-monitoring has an upgrade installplan above the maximum allowed version"
time="2019-11-21T12:15:24Z" level=info msg="Phase: completed ReconcileSubscription"
time="2019-11-21T12:15:24Z" level=info msg="Reconciling Monitoring Components"
time="2019-11-21T12:15:24Z" level=info msg="The operation result for monitoring middleware-monitoring was created"
time="2019-11-21T12:15:24Z" level=info msg="Phase: completed reconcileComponents"
time="2019-11-21T12:15:24Z" level=info msg="Phase: completed reconcileComponents"
time="2019-11-21T12:15:24Z" level=info msg="monitoring installation is reconciled successfully"
--- PASS: TestReconciler_fullReconcile (0.00s)
    --- PASS: TestReconciler_fullReconcile/test_successful_reconcile (0.00s)
=== RUN   TestReconciler_testPhases
=== RUN   TestReconciler_testPhases/test_namespace_terminating_returns_phase_in_progress
time="2019-11-21T12:15:24Z" level=info msg="Phase: in progress ReconcileNamespace"
=== RUN   TestReconciler_testPhases/test_subscription_creating_returns_phase_in_progress
time="2019-11-21T12:15:24Z" level=info msg="Phase: completed ReconcileNamespace"
time="2019-11-21T12:15:24Z" level=info msg="reconciling subscription integreatly-monitoring from channel integreatly in namespace: middleware-monitoring"
time="2019-11-21T12:15:24Z" level=info msg="Phase: in progress ReconcileSubscription"
=== RUN   TestReconciler_testPhases/test_components_creating_returns_phase_in_progress
time="2019-11-21T12:15:24Z" level=info msg="Phase: completed ReconcileNamespace"
time="2019-11-21T12:15:24Z" level=info msg="reconciling subscription integreatly-monitoring from channel integreatly in namespace: middleware-monitoring"
time="2019-11-21T12:15:24Z" level=info msg="Phase: in progress ReconcileSubscription"
--- PASS: TestReconciler_testPhases (0.00s)
    --- PASS: TestReconciler_testPhases/test_namespace_terminating_returns_phase_in_progress (0.00s)
    --- PASS: TestReconciler_testPhases/test_subscription_creating_returns_phase_in_progress (0.00s)
    --- PASS: TestReconciler_testPhases/test_components_creating_returns_phase_in_progress (0.00s)
PASS
coverage: 4.1% of statements in ./pkg/...
ok  	github.com/integr8ly/integreatly-operator/pkg/controller/installation/products/monitoring	0.053s	coverage: 4.1% of statements in ./pkg/...
...
```

**Comment by damienomurchu** [comment]
Looks good, all tests including e2e tests passing

/lgtm
/approve

**Comment by david-martin** [comment]
rebasing and fixing failing test

**Pull request merged**
