### PR TITLE
udpate keycloak operator to 9.0.2 (INTLY-6775)

### PR DESCRIPTION
**Pull request by briangallagher**
# Description
Update the Keycloak operator to 9.0.2 to pull in CVE
https://issues.redhat.com/browse/INTLY-6775

## How to Verify
- Install RHMI and verify user and cluster sso success
- Run setup-htpass-idp.sh and verify users customer-admin and test-user get added to Keycloak
- Log into a number of products via sso such as 3Scale
- Verify operator versions are updated to 9.0.2

### CODE REVIEW

**Comment by davidffrench** [comment]
/lgtm

Code changes look good.

**Comment by KevFan** [comment]
Verified on OSD cluster :+1:

**Comment by davidffrench** [comment]
After checking the cluster, an older Keycloak image is still used.  The tag on this line https://github.com/integr8ly/keycloak-operator-rhmi/blob/all-branches/pkg/model/constants.go#L17 will need to be updated to `1.0-31`.

**Comment by briangallagher** [comment]
> After checking the cluster, an older Keycloak image is still used. The tag on this line https://github.com/integr8ly/keycloak-operator-rhmi/blob/all-branches/pkg/model/constants.go#L17 will need to be updated to `1.0-31`.

thanks @davidffrench  [master still references 1.0-15](https://github.com/keycloak/keycloak-operator/blob/3519447612f1169fe07e699ceecc8b954232997f/pkg/model/constants.go#L17). Why is this required?

**Comment by davidffrench** [comment]
@briangallagher This is the specific Keycloak image tag. This is required to get the latest Image which will include the CVE fix - https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/redhat-sso-7/sso73-openshift

**Comment by briangallagher** [comment]
thanks @davidffrench I've updated that and push a new image

**Comment by davidffrench** [comment]
Thanks @briangallagher

**Pull request merged**
