### PR TITLE
MGDAPI-3311 add addon flow install check

### PR DESCRIPTION
**Pull request by MStokluska**
# Issue link
https://issues.redhat.com/browse/MGDAPI-3311

# What
Block install if addon flow + missing envar

# Verification steps
Review code and confirm e2e passed

### CODE REVIEW

**Comment by MStokluska** [comment]
No MTR_RECONCILED envar from subsConfig in MTR:
image

**Comment by MStokluska** [comment]
After the merge of MR to MTR updating the subscription configuration

image

**Comment by KevFan** [comment]
Code looks good to me and e2e has passed 

/lgtm

**Pull request merged**
