### PR TITLE
Adding templating support to monitoring reconciler

### PR DESCRIPTION
**Pull request by davidkirwan**
## JIRA: 
- https://issues.jboss.org/browse/INTLY-4076

## Description:
Add templating support to the Integreatly Operator to allow the monitoring reconciler to apply monitoring configuration.

## Verification:
- Authenticate with Openshift
- Create ``integreatly`` namespace
- Create the secrets for preflight checks:
```
# Execute from integreatly-operator dir
oc process -f ./deploy/s3-secrets.yaml -p INSTALLATION_NAMESPACE=integreatly -p AWS_ACCESS_KEY_ID=xxxx -p AWS_SECRET_ACCESS_KEY=xxxx -p AWS_BUCKET=xxxx-test -p AWS_REGION=eu-central-1 | oc create -f -
oc create secret generic github-oauth-secret --from-literal=clientId=xxxx --from-literal=secret=xxx -n integreatly
```
- Visit OperatorHub in the Openshift UI, search for integreatly and install it into the ``integreatly`` namespace. Scale the replicas to 0 in the operator deployment in the ``integreatly`` namespace.
- Run the operator locally: ``operator-sdk up local --namespace "integreatly" --operator-flags "--products=monitoring"``
- Create instance of the installation CR eg:
```
apiVersion: integreatly.org/v1alpha1
kind: Installation
metadata:
  name: example-installation
spec:
  type: workshop
  namespacePrefix: integreatly-
  routingSubdomain: apps.com
  masterUrl: https://someurl.apps.com
  selfSignedCerts: true
```
- Wait for reconcile of the monitoring product to complete
- Check the secrets ``test-secret`` and ``test-secret-2`` have been created in the ``integreatly-middleware-monitoring`` namespace, and that they are owned by the Installation CR in the ``integreatly`` namespace.

Screenshot from 2019-11-08 13-43-29

Screenshot from 2019-11-08 13-45-51

### CODE REVIEW

**Comment by davidkirwan** [comment]
I'd like to leave the test-secret and test-secret-2 files in place, as they'll be act as placeholders for the next step in https://issues.jboss.org/browse/INTLY-3513

**Comment by obrienrobert** [comment]
I successfully completed an install of the operator via CodeReady Containers, and verified that both secrets were created.

**Comment by damienomurchu** [comment]
Verified by running the operator locally with these changes against an OSD4 dev cluster, and confirm secrets are created with the owner reference set as intended. 

Only concern I have is merging this with the test secrets, as this may get included in a release, so would remove them. Happy to approve after that, unless there's a compelling reason we should merge this in with the test secrets.

**Comment by damienomurchu** [comment]
/lgtm
/approve

PR looks good, just waiting on e2e tests to pass.

**Pull request merged**
