### PR TITLE
Improved ec2 deploy script error handling

### PR DESCRIPTION
**Pull request by trepel**
# Description

Updated error handling of EC2 deploy (and remove) script. It fails with non-zero return code early now.

It also prints info about entities that have been already created for manual clean up (not ideal, but better than nothing).

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Verification steps

Verified in Jenkins already:
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Public/job/trepel-ec2-deploy/57/ (success)
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Public/job/trepel-ec2-deploy/58/ (early failure, duplicate key)

corresponding removal:
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/ManagedAPI/job/ec2-remove/98

### CODE REVIEW

**Comment by matskiv** [comment]
@trepel I have two suggestions: 
- lets create a key pair just before creating an instance, so we are much less likely to need to clean it up manually.
- and check AMI before creating security group, so we don't need to cleanup sg if AMi step fails

**Comment by trepel** [comment]
Smart, will do that @matskiv

**Comment by trepel** [comment]
@matskiv I reordered the commands so that commands that actually create something are after commands that just get something for later use. Great point Oleg.
Successful build:
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Public/job/trepel-ec2-deploy/62

Could you please have another look once you have time?

**Pull request merged**
