### PR TITLE
Intly 5499 resource dashboards dont work

### PR DESCRIPTION
**Pull request by R-Lawton**
https://issues.redhat.com/browse/INTLY-5499

### Verification
1. Install integreatly using my branch
2. Navigate to Grafana dashboards
3. Ensure that resource usage by namespace and resource usuage by pod look like the following:
Screenshot from 2020-03-06 15-21-51

Screenshot from 2020-03-06 15-21-24

### CODE REVIEW

**Comment by dimitraz** [comment]
:eyes:

**Comment by david-martin** [comment]
/approve
Looking as expected. Nice work 👍 

Will leave lgtm to @dimitraz

**Pull request merged**
