### PR TITLE
New test categories, JustBeforeEach block

### PR DESCRIPTION
**Pull request by psturc**
# Description
https://issues.redhat.com/browse/MGDAPI-557

# Notes
* added a [function for checking whether RHMI is in `complete` stage](https://github.com/integr8ly/integreatly-operator/pull/1637/files#diff-a1556415a07423ac2a86e09105c4ba0d40c6f61c735e82ace37ebde0c280de77R362), that runs before each test
* separated [couple of tests into different categories](https://github.com/integr8ly/integreatly-operator/pull/1637/files#diff-8f8e8391123badb84e94a7a900be5015ccb9f3a10251c1447d83c07ad6c86ac2R91-R100)

### CODE REVIEW

**Comment by psturc** [comment]
ping @Boomatang

**Comment by Boomatang** [comment]
If the "rhoam-e2e" pass I am happy with this. Should we also run this against the rhmi e2e. Just to be sure?
.lgtm

**Pull request merged**
