### PR TITLE
[WIP] codeready-workspaces update to 2.1.1

### PR DESCRIPTION
**Pull request by fh-automatron**
Created automatically by jenkins

### CODE REVIEW

**Comment by matskiv** [comment]
We might be able to just close this and go to 2.2.0, but needs investigation, see:
https://github.com/integr8ly/integreatly-operator/pull/841#pullrequestreview-426322069

**Comment by Boomatang** [comment]
As part of the JIRA ticket https://issues.redhat.com/browse/INTLY-7934 I have check this PR out with running manual tests on both the an initial install and upgrade. Also I have created a PR against this branch with an update to the versions been used, #871 . Once this PR is updated with the version changes I would be happy to merge this PR.

**Pull request merged**
