### PR TITLE
Self managed apicast

### PR DESCRIPTION
**Pull request by jjaferson**
# Description
Adds rate limit back to the backend listener in 3scale and expose the BACKEND_PUBLIC_URL env var in system app

### CODE REVIEW

**Comment by trepel** [comment]
This looks good to me. I am going to install from this PR and do a on-cluster validations. I would like that somebody with more golang coding practise to do the eye review of the code

**Comment by philbrookes** [comment]
this code looks OK, once it's validated that it passes the self managed test case, I'm happy to approve

**Comment by laurafitzgerald** [comment]
I've done some verification on the branch. 
Installed it to my cluster
I saw the below logs for updating the env vars `APICAST_BACKEND_ROOT_ENDPOINT`, `BACKEND_ROUTE` and `BACKEND_PUBLIC_URL` in the operator logs
```
INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=APICAST_BACKEND_ROOT_ENDPOINT envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=true product=3scale
INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=APICAST_BACKEND_ROOT_ENDPOINT envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=true product=3scale
INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=APICAST_BACKEND_ROOT_ENDPOINT envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=true product=3scale
INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=BACKEND_ROUTE envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:service_endpoint,Optional:nil,}}" foundVariable=true product=3scale
INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=BACKEND_ROUTE envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:service_endpoint,Optional:nil,}}" foundVariable=true product=3scale
INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=BACKEND_ROUTE envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:service_endpoint,Optional:nil,}}" foundVariable=true product=3scale
INFO[2021-06-11T10:33:37+01:00] adding env variable to system app             envVarName=BACKEND_PUBLIC_URL envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=false product=3scale
INFO[2021-06-11T10:33:37+01:00] adding env variable to system app             envVarName=BACKEND_PUBLIC_URL envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=false product=3scale
INFO[2021-06-11T10:33:37+01:00] adding env variable to system app             envVarName=BACKEND_PUBLIC_URL envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=false product=3scale
```
The system-app deploymentconfig had the following envs present
```

            - name: APICAST_BACKEND_ROOT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: backend-listener
                  key: route_endpoint

            - name: BACKEND_ROUTE
              valueFrom:
                secretKeyRef:
                  name: backend-listener
                  key: service_endpoint

            - name: BACKEND_PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  name: backend-listener
                  key: route_endpoint
```

I'm not familiar with the secrets but the contained a route and service for back end listner

@jjaferson is there steps to verify the rate limiting functionality?

As aside I noticed the following error in during the 3scale stage but I'm not sure it's related to this change. It resolved itself after a little bit of time so I think we can address it later

```product installation errors : failed installation of 3scale: Operation
    cannot be fulfilled on deploymentconfigs.apps.openshift.io
    "apicast-production": the object has been modified; please apply your
    changes to the latest version and try again```

**Comment by philbrookes** [comment]
@laurafitzgerald the error at the end of your comment is a fairly frequent event in openshift, I don't think that is anything to be worried about unless it's happening a lot.

**Comment by jjaferson** [comment]
> I've done some verification on the branch.
> Installed it to my cluster
> I saw the below logs for updating the env vars `APICAST_BACKEND_ROOT_ENDPOINT`, `BACKEND_ROUTE` and `BACKEND_PUBLIC_URL` in the operator logs
> 
> ```
> INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=APICAST_BACKEND_ROOT_ENDPOINT envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=true product=3scale
> INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=APICAST_BACKEND_ROOT_ENDPOINT envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=true product=3scale
> INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=APICAST_BACKEND_ROOT_ENDPOINT envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=true product=3scale
> INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=BACKEND_ROUTE envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:service_endpoint,Optional:nil,}}" foundVariable=true product=3scale
> INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=BACKEND_ROUTE envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:service_endpoint,Optional:nil,}}" foundVariable=true product=3scale
> INFO[2021-06-11T10:33:37+01:00] updating env variable to system app           envVarName=BACKEND_ROUTE envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:service_endpoint,Optional:nil,}}" foundVariable=true product=3scale
> INFO[2021-06-11T10:33:37+01:00] adding env variable to system app             envVarName=BACKEND_PUBLIC_URL envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=false product=3scale
> INFO[2021-06-11T10:33:37+01:00] adding env variable to system app             envVarName=BACKEND_PUBLIC_URL envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=false product=3scale
> INFO[2021-06-11T10:33:37+01:00] adding env variable to system app             envVarName=BACKEND_PUBLIC_URL envVarValue="{nil nil nil &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:backend-listener,},Key:route_endpoint,Optional:nil,}}" foundVariable=false product=3scale
> ```
> 
> The system-app deploymentconfig had the following envs present
> 
> ```
> 
>             - name: APICAST_BACKEND_ROOT_ENDPOINT
>               valueFrom:
>                 secretKeyRef:
>                   name: backend-listener
>                   key: route_endpoint
> 
>             - name: BACKEND_ROUTE
>               valueFrom:
>                 secretKeyRef:
>                   name: backend-listener
>                   key: service_endpoint
> 
>             - name: BACKEND_PUBLIC_URL
>               valueFrom:
>                 secretKeyRef:
>                   name: backend-listener
>                   key: route_endpoint
> ```
> 
> I'm not familiar with the secrets but the contained a route and service for back end listner
> 
> @jjaferson is there steps to verify the rate limiting functionality?
> 
> As aside I noticed the following error in during the 3scale stage but I'm not sure it's related to this change. It resolved itself after a little bit of time so I think we can address it later
> 
> ```
>     cannot be fulfilled on deploymentconfigs.apps.openshift.io
>     "apicast-production": the object has been modified; please apply your
>     changes to the latest version and try again```
> ```

thanks for verifying Laura, it looks good

**Comment by philbrookes** [comment]
This is the test I'd expect we see passing with this work: https://issues.redhat.com/browse/MGDAPI-1851

**Comment by trepel** [comment]
Yes, that one passed, the deployment of self-managed apicast works as described now. No workaround required. I made a few requests using both self-managed apicast and managed apicasts and both requests were rate-limited OK.

**Comment by philbrookes** [comment]
awesome. I'm happy to approve whenever this gets an lgtm then!

**Comment by laurafitzgerald** [comment]
Verified against self managed apicast deployed in it's own namespace in the cluster.
Screenshot 2021-06-11 at 12 41 16
Resulting Grafana Dashboard with rejected requests
Screenshot 2021-06-11 at 12 40 59

**Comment by trepel** [comment]
Thanks to everyone involved in verification. I think we can lgtm and approve once all the checks succeed.

**Comment by laurafitzgerald** [comment]
The e2e tests passed
```
[1m[32mRan 31 of 34 Specs in 3170.187 seconds[0m
[1m[32mSUCCESS![0m -- [32m[1m31 Passed[0m | [91m[1m0 Failed[0m | [33m[1m0 Pending[0m | [36m[1m3 Skipped[0m
--- PASS: TestAPIs (3181.85s)
PASS
ok  	github.com/integr8ly/integreatly-operator/test/e2e	3181.900s```
the prow job failed on cluster deprovision so I think we can go ahead and merge this.
/approve
/lgtm

**Pull request merged**
