### PR TITLE
Bump Keycloak operator version to 12.0.3

### PR DESCRIPTION
**Pull request by vmuzikar**
# Description
https://issues.redhat.com/browse/INTLY-10442
Probably should be merged after https://github.com/keycloak/keycloak-operator/pull/313.

Steps to test the changes:
1. Install RHOAM  from master using the Integreatly operator.
2. Verify that Keycloak operator 12.0.1 was installed. Use e.g.:
```
oc get rhmis rhoam -n redhat-rhoam-operator -o=jsonpath="{.status.stages.products.products.rhssouser.operator}"
oc get deployments keycloak-operator -n redhat-rhoam-rhsso-operator -o=jsonpath="{.spec.template.spec.containers[0].image}"
```
3. Stop the operator and run it again from this PR.
4. Verify Keycloak operator was updated to 12.0.3 using the steps from 2.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by vmuzikar** [comment]
I think we're good to go with this. https://github.com/keycloak/keycloak-operator/pull/313 was approved and the dependent PR for the OLM catalog (https://github.com/operator-framework/community-operators/pull/3162, https://github.com/operator-framework/community-operators/pull/3163) were merged.

**Comment by briangallagher** [comment]
@vmuzikar I compared the csv files from 12.0.1 and 12.0.3 and I think we might need this: 
https://github.com/integr8ly/integreatly-operator/blob/3b1daecd65b90efe67ec724c9398ee00b0b1e551/manifests/integreatly-rhsso/12.0.1/keycloak-operator.v12.0.1.clusterserviceversion.yaml#L271

Everything else looks good

**Comment by vmuzikar** [comment]
@briangallagher Thanks for the review! I think podmonitors were removed some time ago and therefore [they're missing even from the 12.0.1 CSV in the upstream repo](https://github.com/keycloak/keycloak-operator/blob/b0582f6c156e4a45d16b8b885f06fc904034b552/deploy/olm-catalog/keycloak-operator/12.0.1/keycloak-operator.v12.0.1.clusterserviceversion.yaml#L266-L268).

**Comment by vmuzikar** [comment]
jFTR – here's the PR that removed podmonitors: https://github.com/keycloak/keycloak-operator/pull/243

**Comment by briangallagher** [comment]
@vmuzikar Cathal added some code to remove podmonitors, https://github.com/integr8ly/integreatly-operator/blob/c3dcf4c1ae2ab9f2f2369f99d5ad8da4a40d33e0/pkg/products/rhssocommon/reconciler.go#L543:565

This was a clean up operation and can eventually be removed, but we'll need it for the next release of RHOAM

**Comment by vmuzikar** [comment]
@briangallagher  Ok, re-added the `podmonitors`. Thanks for clarifying.

**Comment by briangallagher** [comment]
@vmuzikar We need to change something small. In the CSV the product SSO image needs to be 7.4-16

In the CSV file change: 
registry.redhat.io/rh-sso-7/sso74-openshift-rhel8:7.4-8.1604567634
to 
registry.redhat.io/rh-sso-7/sso74-openshift-rhel8:7.4-16

**Comment by vmuzikar** [comment]
@briangallagher Done.

**Comment by CathalOConnorRH** [comment]
verifed on cluster, 
` image: 'registry.redhat.io/rh-sso-7/sso74-openshift-rhel8:7.4-16'` 
/lgtm

**Pull request merged**
