### PR TITLE
Increase limits for marin3r and observability operator in Multi Tenant RHOAM

### PR DESCRIPTION
**Pull request by Boomatang**
# Issue link

https://issues.redhat.com/browse/MGDAPI-5758

# What

Increase the memory limits on marin3r and observability operator in Multi Tenant RHOAM

# Verification steps

* Install the current version of Multi tenanted RHAOM
* Record the memory limits on the operator for marin3r and observability. (Command below can be used to do this outside the UI)
* Run the operator version from this branch.
* Check the resource memory limits for both again.
* Expected the limits should increase.
    * marin3r goes to 800Mi
    * observability goes to 1000Mi

Check marin3r resources
```
kubectl get pods $(kubectl get pod -l 'control-plane=controller-manager' -n sandbox-rhoam-marin3r-operator --no-headers=true | awk '{print $1}') -o jsonpath='{range .spec.containers[*]}{"Container Name: "}{.name}{"\n"}{"Memory: "}{.resources.limits.memory}{"\n"}{end}' -n sandbox-rhoam-marin3r-operator
```

Check observability operator resources
```
kubectl get pods $(kubectl get pod -l 'control-plane=controller-manager' -n sandbox-rhoam-observability-operator --no-headers=true | awk '{print $1}') -o jsonpath='{range .spec.containers[*]}{"Container Name: "}{.name}{"\n"}{"memory: "}{.resources.limits.memory}{"\n"}{end}' -n sandbox-rhoam-observability-operator
```

### CODE REVIEW

**Comment by KevFan** [comment]
Any thoughts on setting the limits using the `Subscription` via `SubscriptionConfig` instead in https://github.com/integr8ly/integreatly-operator/blob/master/pkg/resources/marketplace/manager.go#L68-L78 ? 🤔 

`SubscriptionConfig` allows for setting many fields including setting resource requirements for the Operator Pod
```
	mutateSub := func() error {
		sub.Spec = &operatorsv1alpha1.SubscriptionSpec{
			InstallPlanApproval:    approvalStrategy,
			Channel:                t.Channel,
			Package:                t.Package,
			CatalogSource:          catalogSourceReconciler.CatalogSourceName(),
			CatalogSourceNamespace: catalogSourceReconciler.CatalogSourceNamespace(),
			Config: &operatorsv1alpha1.SubscriptionConfig{
				Selector:     nil,
				NodeSelector: nil,
				Tolerations:  nil,
				Resources:    nil,
				EnvFrom:      nil,
				Env:          nil,
				Volumes:      nil,
				VolumeMounts: nil,
				Affinity:     nil,
			},
		}
		return nil
	}
```

I know this approach would probably require a lot more changes / refactor and we already directly edit csvs already in the many areas of the code, but I feel using the `SubscriptionConfig` is probably the nicer / cleaner approach 🤔

**Comment by Boomatang** [comment]
Closing this PR in favour of https://github.com/integr8ly/integreatly-operator/pull/3247

**Pull request closed without merging**
