### PR TITLE
update to AMO 1.5.1 to fix grafana operator not updating issue

### PR DESCRIPTION
**Pull request by briangallagher**
# Description
update to AMO 1.5.1 to fix the following issue.
Updating the Grafana Operator version within AMO does not update when it is already installed
The AMO operator was updated to continuously reconcile the grafana and prom operators. 
AMO PR with details [here](https://github.com/integr8ly/application-monitoring-operator/pull/158)

# Verify
Install the operator based on RHOAM V1.1.0 tag
Verify that AMO is 1.5.0 and Grafana is 3.6.0
Verify Prom, Grafana and AlertManager working as expected

Stop the Operator and checkout this branch
Run Operator
Verify that AMO is 1.5.1 and Grafana is 3.8.1
Verify Prom, Grafana and AlertManager working as expected

### CODE REVIEW

**Comment by briangallagher** [comment]
@CathalOConnorRH Can you review?

**Comment by CathalOConnorRH** [comment]
> @CathalOConnorRH Can you review?

sure
/assign @CathalOConnorRH

**Comment by CathalOConnorRH** [comment]
Verified on cluster, 
/lgtm

**Pull request merged**
