### PR TITLE
MGDAPI-513 3scale version bump

### PR DESCRIPTION
**Pull request by CathalOConnorRH**
# Description
Update 3scale version 

To validate, install managed-api and confirm successful completion of install and that the 3scale operator reports the correct version of 0.6.1

### CODE REVIEW

**Comment by KevFan** [comment]
Verified :+1:  
/lgtm

**Comment by philbrookes** [comment]
/override ci/prow/e2e
/override ci/prow/rhoam-e2e

Already passed multiple times.

**Comment by philbrookes** [comment]
/override ci/prow/e2e
/override ci/prow/rhoam-e2e

Already passed multiple times.

**Comment by psturc** [comment]
@CathalOConnorRH @philbrookes 
Sorry for getting back on this after merge, but should the [3scale product version](https://github.com/integr8ly/integreatly-operator/blob/5a51e24cfdd3d2ca8a5ec55ddb5f422ce0e71101/pkg/apis/integreatly/v1alpha1/rhmi_types.go#L72) be updated as well ( to `2.9.1`)?

**Pull request merged**
