### PR TITLE
MGDAPI-6073 remove nooba/mcg from rhoam code base

### PR DESCRIPTION
**Pull request by austincunningham**
# Issue link

MGDAPI-6073

# What

remove nooba/mcg from rhoam code base

# Verification steps
## Non CCS
- deploy rhoam locally
```bash
INSTALLATION_TYPE=managed-api LOCAL=false make cluster/prepare/local
INSTALLATION_TYPE=managed-api LOCAL=false USE_CLUSTER_STORAGE=true make deploy/integreatly-rhmi-cr.yml
INSTALLATION_TYPE=managed-api LOCAL=false make code/run
```
- uninstall rhoam locally

## CCS
- build an operator image or use `quay.io/austincunningham/managed-api-service:v1.39.0`
```bash
export ORG=<your_user>
OLM_TYPE=managed-api-service INSTALLATION_TYPE=managed-api make image/build
OLM_TYPE=managed-api-service INSTALLATION_TYPE=managed-api make image/push
```
- deploy via the addon flow
- patch the csv with the operator image and set use cluster storage to false in the rhmi CR. 
You can do the steps above manually or use the script https://github.com/integr8ly/integreatly-operator/blob/master/scripts/patch-image-csv.sh

### CODE REVIEW

**Comment by MStokluska** [comment]
Think we could also remove from https://github.com/integr8ly/integreatly-operator/blob/master/products/installation.yaml#L77 and re run bundle builder to remove from container images

**Comment by austincunningham** [comment]
> Think we could also remove from https://github.com/integr8ly/integreatly-operator/blob/master/products/installation.yaml#L77 and re run bundle builder to remove from container images

agree , but won't the bundle be rebuilt when we release 1.39 ?

**Comment by carlkyrillos** [comment]
@austincunningham Do we need to remove the nooba/mcg related tests or will that be done in a followup ticket?

**Comment by austincunningham** [comment]
> @austincunningham Do we need to remove the nooba/mcg related tests or will that be done in a followup ticket?

@carlkyrillos  It would be good to remove them all now. Let me take a look see If I can find them all.

**Comment by carlkyrillos** [comment]
I completed the verification steps and everything is working as expected but I noticed one last reference to `mcg`. Can this [block](https://github.com/austincunningham/integreatly-operator/blob/MGDAPI-6073/controllers/rhmi/types_test.go#L80-L88) be removed? @austincunningham

**Comment by austincunningham** [comment]
> I completed the verification steps and everything is working as expected but I noticed one last reference to `mcg`. Can this [block](https://github.com/austincunningham/integreatly-operator/blob/MGDAPI-6073/controllers/rhmi/types_test.go#L80-L88) be removed? @austincunningham

@carlkyrillos yea it can be take out, it doesn't show up on my string searches in goland but does in vscode :thinking:

**Comment by carlkyrillos** [comment]
Reviewed changed files and completed the verification steps
/lgtm

**Pull request merged**
