### PR TITLE
MGDAPI-4429 update testcase c18

### PR DESCRIPTION
**Pull request by austincunningham**
# Issue link

MGDAPI-4429 

# What

Update the test case with the findings of this comment https://issues.redhat.com/browse/MGDAPI-4429?focusedCommentId=20758467&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20758467

### CODE REVIEW

**Comment by austincunningham** [comment]
@trepel if you have time for a review

**Comment by trepel** [comment]
Thanks! I just read through it and it looks good to me.

/lgtm

**Comment by KevFan** [comment]
No need to check for code coverage for test case update (failing because PR is behind master) so overriding

/override codecov/project

**Pull request merged**
