### PR TITLE
Release 2.7.1

### PR DESCRIPTION
**Pull request by R-Lawton**
cherry-picking changes from the following PRs https://github.com/integr8ly/integreatly-operator/pull/1254 https://github.com/integr8ly/integreatly-operator/pull/1245
Note: To fix unit tests other changes were needed. The changes were gotten from master
The changes were in the following files
* https://github.com/integr8ly/integreatly-operator/pull/1258/commits/07c820f355100a7ad960c5e4ef4db0c437e6ceb0#diff-f413bc7fd3fa6efb8fb475051aae40798cbf62d154215151c93b983b8395fa45
* https://github.com/integr8ly/integreatly-operator/pull/1258/commits/07c820f355100a7ad960c5e4ef4db0c437e6ceb0#diff-e69eb4521e26722c83abc4bbd07f0b4ef996fbd886106fd5d79e56db05943dde
* https://github.com/integr8ly/integreatly-operator/pull/1258/commits/959a9187502ad8be1083ac1650ab9a1497bf4607#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52
* https://github.com/integr8ly/integreatly-operator/pull/1258/commits/959a9187502ad8be1083ac1650ab9a1497bf4607#diff-9bf439dbd481bde896fcefdae058258971e1838f0d2e2528ce3e0d8119281374

### CODE REVIEW

**Review by pb82 — APPROVED** [review]
LGTM

**Comment by Rajagopalan-Ranganathan** [comment]
discussed with @R-Lawton , the changes are tested and working.

**Pull request merged**
