### PR TITLE
fixed linting issues and added rhmi operator resources limits check

### PR DESCRIPTION
**Pull request by pawelpaszki**
# Description
fixed linting issues and added rhmi operator resources limits check

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by damienomurchu** [comment]
/lgtm 
/verify

Looks good to me, and verified locally. Approving as changes just confined to test-cases folder.

**Comment by tonyxrmdavidson** [comment]
lgtm

**Pull request merged**
