### PR TITLE
Bump the AMO operator version to 1.2.1

### PR DESCRIPTION
**Pull request by Rajagopalan-Ranganathan**
# Description
JIRA Link: https://issues.redhat.com/browse/INTLY-8046

The second pod during upgrade is fixed in AMO operator
version 1.2.1 , the version is being bumped here to include the latest changes.
Note that a similar changes are made to Grafana operator as well which are incorporated
in AMO version 1.2.1.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by HubertStefanski** [comment]
Seeing an issue with a missing pod in the grafana-operator deployment when running integreatly locally
image

Grafana deployment CR :arrow_down: 
image

The logs for the `grafana-operator` pod don't show anything unusual from my point of view though :thinking: 
image

Other than that, AMO and Grafana Operator appear to have the correct versions `1.2.1` and `3.4.0` respectively

**Comment by Rajagopalan-Ranganathan** [comment]
> Seeing an issue with a missing pod in the grafana-operator deployment when running integreatly locally
> image
> 
> Grafana deployment CR arrow_down
> image
> 
> The logs for the `grafana-operator` pod don't show anything unusual from my point of view though thinking
> image
> 
> Other than that, AMO and Grafana Operator appear to have the correct versions `1.2.1` and `3.4.0` respectively
> 
> _**Edit:**_ Re-ran with a clean installation, problem seems to be persistent.

Seeing the same issue from my end as well. Looks like the pod is running fine, but doesnt flip to ready state, @pb82 @david-martin , would this be related to the rmeoval of readiness probe from deployment yaml or code?

**Comment by Rajagopalan-Ranganathan** [comment]
> > Seeing an issue with a missing pod in the grafana-operator deployment when running integreatly locally
> > image
> > Grafana deployment CR arrow_down
> > image
> > The logs for the `grafana-operator` pod don't show anything unusual from my point of view though thinking
> > image
> > Other than that, AMO and Grafana Operator appear to have the correct versions `1.2.1` and `3.4.0` respectively
> > _**Edit:**_ Re-ran with a clean installation, problem seems to be persistent.
> 
> Seeing the same issue from my end as well. Looks like the pod is running fine, but doesnt flip to ready state, @pb82 @david-martin , would this be related to the rmeoval of readiness probe from deployment yaml or code?

following this link: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ 
```The kubelet uses readiness probes to know when a container is ready to start accepting traffic. A Pod is considered ready when all of its containers are ready. One use of this signal is to control which Pods are used as backends for Services. When a Pod is not ready, it is removed from Service load balancers.``` i am not sure if i understand it correctly, but looks like readiness probe in the yaml file must be there. @pb82 @david-martin @grdryn @HubertStefanski

**Comment by Rajagopalan-Ranganathan** [comment]
> > Seeing an issue with a missing pod in the grafana-operator deployment when running integreatly locally
> > image
> > Grafana deployment CR arrow_down
> > image
> > The logs for the `grafana-operator` pod don't show anything unusual from my point of view though thinking
> > image
> > Other than that, AMO and Grafana Operator appear to have the correct versions `1.2.1` and `3.4.0` respectively
> > _**Edit:**_ Re-ran with a clean installation, problem seems to be persistent.
> 
> Seeing the same issue from my end as well. Looks like the pod is running fine, but doesnt flip to ready state, @pb82 @david-martin , would this be related to the rmeoval of readiness probe from deployment yaml or code?

Ok, looks like the grafana-operator has still readiness probe defined in the yaml and once removed it moved to the ready state. @pb82 can you check if the version 3.4.0 has been built and tagged correctly?

**Comment by Rajagopalan-Ranganathan** [comment]
@HubertStefanski @pb82  - made changes to AMO operator and fixed the readiness probe issue there with the same release tag. Verified that grafana operator pod enters ready state.

**Comment by david-martin** [comment]
/approve

Nice work @Rajagopalan-Ranganathan @HubertStefanski

**Pull request merged**
