### PR TITLE
INTLY-9467 Skip errors in web app notification due to no kind found

### PR DESCRIPTION
**Pull request by sergioifg94**
# Description
> Link to JIRA:  https://issues.redhat.com/browse/INTLY-9467

## Verification steps

1. Begin an RHMI installation through OLM
2. Before the installation finishes (make sure the WebApp CRD does not exist yet) simulate an upcoming upgrade
3. Verify that the upgrade is scheduled successfully in the RHMIConfig status
4. Edit the RHMIConfig upgrade spec to make it approve the upgrade
5. Verify that no error logs are shown in the operator Pod and the upgrade is approved

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by MStokluska** [comment]
Verified it on a cluster, there are no WepApp errors logged, RHMIConfig is updated accordingly and upgrade was successful.  
Great job!
/lgtm

**Comment by philbrookes** [comment]
/override ci/prow/e2e
verified manually by @MStokluska test is failing on flake addressed here: https://issues.redhat.com/browse/INTLY-9596

**Pull request merged**
