### PR TITLE
Added linking of destructive tasks as blockers in JIRA

### PR DESCRIPTION
**Pull request by martinhesko**
# Description
When there are destructive tasks in a test run link all non-destructive tasks as blockers

my changes were tested on [This JIRA](https://issues.redhat.com/browse/MGDAPI-2000) with `./tools.sh jira --epic MGDAPI-2000 --product rhoam --environment osd-fresh-install` command and changing a few non-destructive issues in the `osd-fresh-install` environment to destructive to verify that destructive issues are being chained together properly

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by psturc** [comment]
@martinhesko test case linter has some issues with the following lines
```
ERROR: 207:24  only-arrow-functions  non-arrow functions are forbidden
ERROR: 208:41  triple-equals         == should be ===
ERROR: 242:34  triple-equals         == should be ===
```
fixing those and rerunning `npm run prettier && npm run lint` should resolve the issue.

I verified the functionality, so I'm ok to approve this once the lint issues are resolved.

**Comment by martinhesko** [comment]
my bad, didn't run lint, should be good to merge now

**Pull request merged**
