### PR TITLE
MGDAPI-5090 ensure rhoam pod priority is reconciled after installation

### PR DESCRIPTION
**Pull request by cecobask**
# Issue link
https://issues.redhat.com/browse/MGDAPI-5090

# What
Refactored the A27/A28 E2E test which deal with RHOAM reconciling the pod priority specified in the RHMI CR spec to the relevant resources. For background information why this was implemented refer to this JIRA: https://issues.redhat.com/browse/MGDAPI-4655

# Verification steps
- Provision an OSD cluster
- Install RHOAM from this branch
- Run the A27/A28 E2E test
- Ensure it passes

### CODE REVIEW

**Comment by Fiona-Waters** [comment]
Followed the verification steps and can confirm that the test passed. Code looks good. /lgtm

**Comment by trepel** [comment]
I did a super quick review and it looks good to me too

/approve

**Pull request merged**
