### PR TITLE
MGDAPI-3796: G107 Url provided to HTTP request as taint input

### PR DESCRIPTION
**Pull request by kryanbeane**
# Issue link
[MGDAPI-3796](https://issues.redhat.com/browse/MGDAPI-3796)

# What
- Changed how URLs are constructed with parameters in two tests

# Verification steps
- Run `make gosec/exclude` from this branch and make sure there are no issues reported by gosec

### CODE REVIEW

**Comment by kryanbeane** [comment]
changing commit message from `MGDAPI-3796: ....` to MGDAPI-3796 ...` to try fix commit check

**Comment by Fiona-Waters** [comment]
No issues reported by gosec when running make gosec/exclude from this pr. 
image

/lgtm

**Pull request merged**
