### PR TITLE
MGDAPI-2890 - Upgrade keycloak-operator to v17.0.0

### PR DESCRIPTION
**Pull request by adam-cattermole**
# Issue link
[MGDAPI-2890](https://issues.redhat.com/browse/MGDAPI-2890)

# What
- Added manifests from keycloak-operator v17.0.0
- Removed hard-coded replacement of JDK images

# Verification steps
- Verify upgrading RHOAM using this branch installs keycloak-operator v17.0.0
  - quay.io/acatterm/managed-api-service-index:1.19.0 (built from master)
  - quay.io/acatterm/managed-api-service-index:1.25.0 (built from this PR) 
- Check keycloak images are replaced with latest version - see these images from the catalog - [keycloak](https://catalog.redhat.com/software/containers/rh-sso-7/sso75-openshift-rhel8/611418806e1e42ca4d6decf1?push_date=1646841023000&architecture=amd64&tag=all), [init-container](https://catalog.redhat.com/software/containers/rh-sso-7/sso7-rhel8-init-container/6160610d5ac6c12504902068?tag=all)

### CODE REVIEW

**Review by Boomatang — APPROVED** [review]
This looks good.
I ran the verification steps and the images were updated. Also ran the IDP e2e tests these pasted as expected
/lgtm

**Comment by laurafitzgerald** [comment]
@adam-cattermole if we have time, we should bump the version of keycloak operator in go.mod 
I've checked locally and there are some api changes for the newer version

**Comment by adam-cattermole** [comment]
Good shout, I missed this - I'll have a look into updating it.

**Comment by adam-cattermole** [comment]
I've updated the keycloak-operator module and the one [api change here](https://github.com/integr8ly/integreatly-operator/pull/2583/files#diff-ea0e91bd9f2b961ab416fa3821815794ee1f0a283090fff9c72af19d81a42b72L478-R452) (setting insecure SSL boolean to false as this was the default behaviour prior to the option being added).

**Comment by laurafitzgerald** [comment]
@adam-cattermole do you intend to do further verification on this change or is it ready to be merged? the code changes look fine to me.

**Comment by adam-cattermole** [comment]
> @adam-cattermole do you intend to do further verification on this change or is it ready to be merged? the code changes look fine to me.

I'll ensure that the API update didn't affect anything by running through a quick install / uninstall and I'll ping when ready.

Latest commit is just a rebase on master.

**Comment by adam-cattermole** [comment]
@laurafitzgerald I'm happy for it to be merged now.

Coverage % dropped because a function that is already tested now has fewer lines of code. Should be overridden.

**Pull request merged**
