### PR TITLE
Fix openapi generation; add tool dependencies for consistency

### PR DESCRIPTION
**Pull request by grdryn**
----

# Description

- openapi generation didn't get added correctly after updating to operator-sdk 0.15.x
- PagerDutySecret field had bad tag that failed an openapi rule
- Tool dependencies are cool

## Type of change

- [?] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by matskiv** [comment]
@grdryn this looks pretty cool 👍 
Please resolve the conflicts and I'll approve. :)

**Comment by grdryn** [comment]
Thanks for the review @matskiv :)

I've rebased now, and crossing my fingers that the tests all pass again! :crossed_fingers:

**Pull request merged**
