### PR TITLE
MGDAPI-2070: change images for 3scale and Envoy

### PR DESCRIPTION
**Pull request by austincunningham**
# Description

MGDAPI-2070 change images for 3scale and Envoy
## Type of change

Image changes

## Verification
- checkout this branch
- install rhoam locally
- confirm 3scale is up and running and check the following containers to see if they have the correct images
  - apicast-production-3 pod, apicast-production container has this image  registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:6ea21688678d40ec75e3a309721209eab16978e7d96941df05500e7214b5dd1d
image
  - system-app pod, (system-master, system-provider, system-developer) containers have this image registry.redhat.io/3scale-amp2/system-rhel7@sha256:d02e84ca7835e317bbbc2a702ec84cd67cf37ea86b78485f937a1685ea3563f8
image
  - system-memcache pod memcache container have this image registry.redhat.io/3scale-amp2/memcached-rhel7@sha256:abb74220a349f3d4b5aac8a28bd5c1ca5e1b141434c05f8b8c58a91edfdeaa55
image
  - zync pod, zync container have this image registry.redhat.io/3scale-amp2/zync-rhel7@sha256:130f5b62e04eddb55f7a8d677b8c87c8fde9d1553dce122b11c2caeb549e5819
image

- Check that envoy-sidecar are present on apicasts and have the an image tag 2.0.6-1
image

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by jackdelahunt** [comment]
/lgtm

- Created a cluster
- Installed rhoam locally
- Install completed as expected
- Container images updated checklist
    - api-cast-production pod updated ✅
    - system-app updated ✅
    - system-memcache updated ✅
    - zync updated ✅
    - envoy-sidecar updated ✅

**Comment by philbrookes** [comment]
@austincunningham is this still a WIP, or is it ready to merge now?

**Comment by austincunningham** [comment]
@philbrookes still a wip

**Pull request merged**
