### PR TITLE
automatest test to check for aws s3 blob resources

### PR DESCRIPTION
**Pull request by briangallagher**
# Description
automatest test to check for aws s3 blob resources

### CODE REVIEW

**Comment by psturc** [comment]
@briangallagher @Boomatang I've got one cluster running atm, so I can give it a look and verify

**Comment by psturc** [comment]
I installed RHMI from master and when I run the test I get this error:
```
=== RUN   TestIntegreatly/Integreatly_Happy_Path_Tests/F04_-_Verify_AWS_s3_blob_storage_resources_exist
    TestIntegreatly/Integreatly_Happy_Path_Tests/F04_-_Verify_AWS_s3_blob_storage_resources_exist: aws_s3_resources_exist.go:26: test cro blob storage exists failed with the following errors : [
        backups-blobstorage-rhmi blobStorage cr does not contain a resource id annotation: annotations for backups-blobstorage-rhmi can not be nil
        threescale-blobstorage-rhmi blobStorage cr does not contain a resource id annotation: no resource identifier found for resource threescale-blobstorage-rhmi]
```
Is there a specific branch of integreatly-operator I should test this with?

**Comment by psturc** [comment]
/lgtm
/approve
verified locally

**Comment by b1zzu** [comment]
Do not forget to mark the test-case as automated: https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/high-availability/f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md

**Pull request merged**
