### PR TITLE
MGDAPI-4650 edited test to use it with Gitlab, because SOPs were moved there

### PR DESCRIPTION
**Pull request by Stellar-9**
# Issue link
[https://issues.redhat.com/browse/MGDAPI-4650](url)

# What
Changes done to c08b test. It should reflect recent changes to the SOPs. They were moved from Github to the Gitlab

# Verification steps
Run locally or in pipelines

### CODE REVIEW

**Comment by MStokluska** [comment]
Please update the commit message to start with MGDAPI-<JIRA NO>, other than this, it looks good, a follow up is required to expose gitlab token in ci/cd.

**Comment by MStokluska** [comment]
/lgtm 
Confirmed test passing locally with the use of GITLAB token from CICD

**Comment by KevFan** [comment]
Code coverage failing due to PR is behind master - overriding

/override codecov/project

**Pull request merged**
