### PR TITLE
added note for test case C07

### PR DESCRIPTION
**Pull request by jhellar**
# Description

Added note for C07 test case regarding fix that will be made in future.

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by pawelpaszki** [comment]
@jhellar - looks good. did you run `npm run lint`?

**Comment by jhellar** [comment]
@pawelpaszki `npm run lint` found some issues but in other test cases, should I push them as well?

**Comment by pawelpaszki** [comment]
That would be nice @jhellar. Thanks

**Comment by david-martin** [comment]
/lgtm
Thanks @jhellar

**Pull request merged**
