### PR TITLE
MGDAPI-1030 Grafana version Bump

### PR DESCRIPTION
**Pull request by CathalOConnorRH**
# Description
Bump of Grafana to take in changes from MGDAPI-1030 

# Verifcation Steps: 
Install from this branch and verify operator version is 3.8.1 and that the grafana CR only updated as status changes happen rather than on every reconciliation

## Type of change
Bump of Grafana to take in changes from MGDAPI-1030 

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by KevFan** [comment]
Verified that grafana CR is updated only on staus changes for customer grafana :+1: 

AMO grafana still faces the issue until new version is used with this change:
* https://github.com/integr8ly/application-monitoring-operator/pull/157

/lgtm

**Comment by CathalOConnorRH** [comment]
@KevFan Thanks Kevin, PR opened to address AMO issue https://github.com/integr8ly/integreatly-operator/pull/1558

**Pull request merged**
