### PR TITLE
remove echo to fix rhoam e2e tests

### PR DESCRIPTION
**Pull request by CathalOConnorRH**
# Description
Remove echo line from makefile to run rhoam e2e tests.

### CODE REVIEW

**Comment by philbrookes** [comment]
I'm trying to fix this in my PR too, I suspect this failure is due to this missing line:
https://github.com/integr8ly/integreatly-operator/pull/1356/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R198

**Comment by CathalOConnorRH** [comment]
closing as Phil has these changes in his PR

**Pull request closed without merging**
