### PR TITLE
test: a25: remove updating cidr range from test

### PR DESCRIPTION
**Pull request by psturc**
# Issue
https://issues.redhat.com/browse/MGDAPI-3011
https://issues.redhat.com/browse/MGDAPI-2309

# What
This test fails frequently in our pipelines on following error:
```
    Update Cidr Block in AWS Strategy Map errors:
    	failed to update aws strategy map: Operation cannot be fulfilled on configmaps "cloud-resources-aws-strategies": the object has been modified; please apply your changes to the latest version and try again
```

This is caused by the the unsuccessful attempt to update `cloud-resources-aws-strategies` configmap by the test. The object has changed because rhmi-operator updated the configmap first. It can be fixed by fetching the configmap content just before the update, but there's still a slight chance that rhmi-operator might still be able update it between get & update actions and cause the error again.

I rather decided to remove the flaky "verifyCidrBlockUpdate" part from the test, because it's not a scenario any customer could hit, because they are not able to modify "cloud-resources-aws-strategies" configmap.

# To verify
```
go clean -testcache && MULTIAZ=true BYPASS_STORAGE_TYPE_CHECK=true WATCH_NAMESPACE=redhat-rhoam-operator go test -v ./test/functional -timeout=80m -ginkgo.focus="A25" -ginkgo.v -ginkgo.progress -ginkgo.trace
```

### CODE REVIEW

**Comment by psturc** [comment]
Hi @Boomatang I'd like to get your opinion on removing this part of the test from "A25"

**Comment by Boomatang** [comment]
I go agree that check was adding flakiness to the test. It is my personal opinion that some tests are trying to test to much and do give a clear reason for failure or test components with no direct link to the others in the test case. So I am all for create clean test.

In this case should there be steps some steps added to the written test case so this may be checked manual from time to time.  Or maybe a new test case written which would only be for this, then if it is tried to be automated in the future again it would be adding back in the flakiness to this test but a new one. 

https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/installation/a25-verify-standalone-rhmi-vpc-exists-and-is-configured-properly.md

Go to get my hands on a mutli-az cluster and run the verification step now

**Comment by laurafitzgerald** [comment]
this change looks fine for me. happy to have this test removed. It may be the case that it's covered in cro also. The config map in question is specific to cro
/lgtm

**Comment by psturc** [comment]
I checked cloud-resource-operator repo, but couldn't find such e2e test.
I just removed the step from the manual test case.

**Pull request merged**
