### PR TITLE
uninstallation stages

### PR DESCRIPTION
**Pull request by philbrookes**
# Description
Add stages for uninstallation, and have monitoring uninstall last.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Verification
Run installation on a cluster.
Delete CR.
See that monitoring is uninstalled after everything else is gone.

### CODE REVIEW

**Comment by trdoyle81** [comment]
Verified monitoring uninstalled last
https://gist.github.com/trdoyle81/3348771b6ab0596fcb9af8f88a312dfc#file-verifyintly8360-L359

**Comment by philbrookes** [comment]
/override ci/prow/e2e
/override ci/prow/format
/override ci/prow/images
/override ci/prow/manifest
/override ci/prow/unit
/override ci/prow/vendor

already passed.

**Pull request merged**
