### PR TITLE
style: updating icons

### PR DESCRIPTION
**Pull request by MStokluska**
# Description
Update Integreatly upstream icons with the approved Red Hat RHMI icons. Addresses [https://issues.redhat.com/browse/INTLY-8456](https://issues.redhat.com/browse/INTLY-8456).

## Why

Currently, the RHMI operator uses an outdated icon for Application Monitoring Operator and Cloud Resource Operator. Tutorial Web App Operator has no icon set.

## Type of change

- Bug fix/Graphical (non-breaking change which fixes an issue)

### Short:
- Deploy RHMI Operator via OLM or Locally
- Install the `RHMI Operator` via `Operator Hub` or locally, new icons should visible at this stage
- Navigate to `Installed Operators` tab on OpenShift
- Set `Project` to `all projects`
- Look for a new icon for `Application Monitoring Operator`, `Cloud Resource Operator` and `Tutorial Web App Operator`

##### OLM:
- Set `ORG ?= ` to your organization name on [Quay.io](quay.io)
- Execute `make image/build/push` to build and push the image to [Quay.io](quay.io)
-  In `integreatly-operator/deploy/olm-catalog/integreatly-operator/integreatly-operator-LATEST_VERSION/integreatly-operator.LATEST_VERSION.clusterserviceversion.yaml` edit line `containerImage` and `image` to match your repo on [Quay.io](quay.io) 
- Push csv to your registry with `make push/csv REPO=<your_organization_name> QUAY_USERNAME=<your_user_name> QUAY_PASSWORD=<password>`
- Change Application and Repository on [Quay.io](quay.io) to public
- Create an `Operator Source` YAML file called `operator-source.yml`
- Copy/Paste the following into the YAML file and edit the `ORG_NAME` to match your organization name : 
```YAML
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: rhmi
  namespace: openshift-marketplace
spec:
  authorizationToken: {}
  displayName: RHMI Operators
  endpoint: 'https://quay.io/cnr'
  publisher: Integreatly Publisher
  registryNamespace: ORG_NAME
  type: appregistry
```
- Execute command `oc create -f operator-source.yml`
- Create Operator namespace and setup secrets by executing: `make cluster/prepare/project && make cluster/prepare/smtp && make cluster/prepare/dms && make cluster/prepare/pagerduty`
- In OpenShift navigate to `Operator Hub` and install `RHMI Operator`
- In `Installed Operators` tab, select `All projects` and look for new icons of `Application Monitoring`, `Cloud Resource Operator` and `Tutorial Web App Operator`

##### Locally:
- Create `RHMI` Custom Resource with : `oc create -f deploy/crds/examples/rhmi.cr.yaml`
- Execute `make code/run` to run the `RHMI Operator` locally.

### CODE REVIEW

**Comment by CathalOConnorRH** [comment]
verified on cluster. Good work. 
/lgtm

**Comment by philbrookes** [comment]
no need for e2e tests on this PR, no code changes.

**Pull request merged**
