### PR TITLE
[WIP] amq-online update to 1.5.0

### PR DESCRIPTION
**Pull request by fh-automatron**
Update amq-online manifest to 1.5.0 

This is an automatically generated branch to track the '1.5.0' version of the 'amq-online' OLM manifests.
This branch will be automatically updated with any changes related to this version until it finally GAs. 

Changes required to fix installation issues should be applied to this branch following the usual [PR Workflow](https://github.com/integr8ly/delorean/blob/master/docs/integrealy-ci/prow-pr-workflow.md)

More details about the Early Warning System that generated this can be found [here](https://github.com/integr8ly/delorean/tree/master/docs/ews)

## Type of change

- [X] Product Update

## Checklist
- [ ] Older product manifests (N-2) have been removed
- [ ] Operator and Product Versions are updated correctly
- [ ] Go Modules are updated if required

### CODE REVIEW

**Comment by b1zzu** [comment]
E2E Test Resume:

```
**FAIL: TestIntegreatly/integreatly/C04_-_Verify_Alerts_exist (2.72s)**
alerts_exist.go:703: Found missing or too many alerts
```

maybe the new version of AMQ is adding new alerts 

the test doesn't print the missing tests because:
* the e2e tests are not executed with the `-v` flag
* the Alerts tests should use `t.Log` instead of `fmt.Print`



```
FAIL: TestIntegreatly/integreatly/H03_-_Verify_3scale_CRUDL_permissions (306.00s)
            openshift_auth.go:58: Performing OpenShift HTTP client setup with URL https://console-openshift-console.apps.ci-op-dks6dqzj-4750b.origin-ci-int-aws.dev.rhcloud.com/auth/login
            authdelay_first_broker_login.go:133: Attempting to open threescale login page with url: https://3scale-admin.apps.ci-op-dks6dqzj-4750b.origin-ci-int-aws.dev.rhcloud.com/p/login
            authdelay_first_broker_login.go:180: browser URL /auth/realms/openshift/login-actions/first-broker-login?client_id=3scale&tab_id=OYfYQ5H3mIY
            authdelay_first_broker_login.go:181: does browser URL contains p/admin/dashboard or p/admin/onboarding/wizard/intro false
            authdelay_first_broker_login.go:180: browser URL /auth/realms/openshift/login-actions/first-broker-login?client_id=3scale&tab_id=OYfYQ5H3mIY
skipped 114 lines unfold_more
            authdelay_first_broker_login.go:181: does browser URL contains p/admin/dashboard or p/admin/onboarding/wizard/intro false
            authdelay_first_broker_login.go:180: browser URL /auth/realms/openshift/login-actions/first-broker-login?client_id=3scale&tab_id=OYfYQ5H3mIY
            authdelay_first_broker_login.go:181: does browser URL contains p/admin/dashboard or p/admin/onboarding/wizard/intro false
            authdelay_first_broker_login.go:180: browser URL /auth/realms/openshift/login-actions/first-broker-login?client_id=3scale&tab_id=OYfYQ5H3mIY
            authdelay_first_broker_login.go:181: does browser URL contains p/admin/dashboard or p/admin/onboarding/wizard/intro false
            3scale_crudl.go:38: Account was not provisioned: timed out waiting for the condition
```
It's a know flaky tests: https://issues.redhat.com/browse/INTLY-8433

**Comment by mikenairn** [comment]
/close 

Replaced by https://github.com/integr8ly/integreatly-operator/pull/978

**Pull request closed without merging**
