### PR TITLE
add instructions for how to request OCP4 clusters on PSI

### PR DESCRIPTION
**Pull request by wei-lee**
# Description
https://issues.redhat.com/browse/DEL-270

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by mikenairn** [comment]
/lgtm
/approve

Approving since it's just docs updates. I requested the required LDAP access, but wasn't able to actually run the pipeline yet.

I think there might be some benefit to scripting/adding to the cli the ability to trigger the Jenkins jobs to create/destroy the clusters, but having the doc initially seems like a good first step.

**Comment by matskiv** [comment]
I verified the process, all worked.
Just a thought, would it be better to add this into help repo instead?

**Comment by jasonmadigan** [comment]
@wei-lee not sure docs like this should have a home in a public repo. A link is fine (maybe to integreatly-help?)

**Comment by wei-lee** [comment]
@jasonmadigan ok, will do.

**Pull request closed without merging**
