### PR TITLE
Bump CRO to 0.30.0

### PR DESCRIPTION
**Pull request by matskiv**
# Description
JIRA: https://issues.redhat.com/browse/MGDAPI-2278

Bumping CRO to pick up new implementation of Elasticache service update logic.

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@matskiv as part of this pr can we change back the setting of applyImmediately to false for each of the redis as it now doesn't do anything. So don't want that to be confusing in the future.

**Comment by matskiv** [comment]
@laurafitzgerald good point, will do

**Comment by austincunningham** [comment]
@matskiv I don't see the go mod sum or vendor change, we should bump these also

**Comment by matskiv** [comment]
@austincunningham I've done that now and added it to the first commit - hence the force push. 
FYI: nothing besides go.mod changed, even after `make vendor/fix`, because code that we vendor in wasn't changed. :)

**Comment by austincunningham** [comment]
I will just install rhoam to confirm that cro v0.30.0 is installed, not much else I can do to verifiy

**Comment by austincunningham** [comment]
## Verified the installation
```yaml
    cloud-resources:
      name: cloud-resources
      phase: completed
      products:
        cloud-resources:
          host: ''
          name: cloud-resources
          operator: 0.30.0
          status: completed
          version: 0.30.0
```
once the unit test is fixed can give an lgtm

**Comment by austincunningham** [comment]
Ran some of the e2e-rhoam test locally [ F01, F03, A21,A25] all Passed 
```bash
➜  integreatly-operator git:(MGDAPI-2278) INSTALLATION_TYPE=managed-api TEST=F01 make test/e2e/single
go clean -testcache && go test ./test/functional -ginkgo.focus="F01.*" -test.v -ginkgo.v -ginkgo.progress -timeout=80m
time="2021-07-13T12:30:17+01:00" level=info msg="calling reset on all prometheus gauge vectors" custom_metrics=StartGaugeVector
=== RUN   TestAPIs
STEP: bootstrapping test environment
I0713 12:30:19.094131 1860226 request.go:635] Throttling request took 1.048377407s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/cloudcredential.openshift.io/v1?timeout=32s
I0713 12:30:29.386923 1860226 request.go:635] Throttling request took 1.001067191s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/authorization.openshift.io/v1?timeout=32s
Running Suite: Functional Test Suite
====================================
Random Seed: 1626175817
Will run 1 of 51 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
integreatly managed-api Functional 
  F01 - Verify AWS rds resources exist and are in expected state
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
[BeforeEach] integreatly
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:17
[JustBeforeEach] integreatly
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:22
[It] F01 - Verify AWS rds resources exist and are in expected state
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
I0713 12:30:41.349815 1860226 request.go:635] Throttling request took 1.047310295s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/samples.operator.openshift.io/v1?timeout=32s

• [SLOW TEST:8.814 seconds]
integreatly
/home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:10
  managed-api Functional
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:73
    F01 - Verify AWS rds resources exist and are in expected state
    /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
------------------------------
SSSSSSSSSSTEP: tearing down the test environment

Failed to create JUnit directory: /test-run-results/junit-integreatly-operator.xml
        mkdir /test-run-results: permission deniedFailed to create JUnit report file: /test-run-results/junit-integreatly-operator.xml
        open /test-run-results/junit-integreatly-operator.xml: no such file or directory
Failed to generate JUnit report data:
        invalid argument
Ran 1 of 51 Specs in 8.814 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 50 Skipped
--- PASS: TestAPIs (26.65s)
PASS
ok      github.com/integr8ly/integreatly-operator/test/functional       26.687s
➜  integreatly-operator git:(MGDAPI-2278) INSTALLATION_TYPE=managed-api TEST=F03 make test/e2e/single
go clean -testcache && go test ./test/functional -ginkgo.focus="F03.*" -test.v -ginkgo.v -ginkgo.progress -timeout=80m
time="2021-07-13T12:31:33+01:00" level=info msg="calling reset on all prometheus gauge vectors" custom_metrics=StartGaugeVector
=== RUN   TestAPIs
STEP: bootstrapping test environment
I0713 12:31:35.292043 1860651 request.go:635] Throttling request took 1.04954512s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/user.openshift.io/v1?timeout=32s
I0713 12:31:45.810002 1860651 request.go:635] Throttling request took 1.044235868s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/events.k8s.io/v1beta1?timeout=32s
Running Suite: Functional Test Suite
====================================
Random Seed: 1626175893
Will run 1 of 51 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
integreatly managed-api Functional 
  F03 - Verify AWS elasticache resources exist and are in expected state
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
[BeforeEach] integreatly
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:17
[JustBeforeEach] integreatly
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:22
[It] F03 - Verify AWS elasticache resources exist and are in expected state
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
I0713 12:31:57.819602 1860651 request.go:635] Throttling request took 1.048366252s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/cloudcredential.openshift.io/v1?timeout=32s

• [SLOW TEST:8.817 seconds]
integreatly
/home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:10
  managed-api Functional
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:73
    F03 - Verify AWS elasticache resources exist and are in expected state
    /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
------------------------------
SSSSSSSSSTEP: tearing down the test environment

Failed to create JUnit directory: /test-run-results/junit-integreatly-operator.xml
        mkdir /test-run-results: permission deniedFailed to create JUnit report file: /test-run-results/junit-integreatly-operator.xml
        open /test-run-results/junit-integreatly-operator.xml: no such file or directory
Failed to generate JUnit report data:
        invalid argument
Ran 1 of 51 Specs in 8.818 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 50 Skipped
--- PASS: TestAPIs (27.11s)
PASS
ok      github.com/integr8ly/integreatly-operator/test/functional       27.146s
➜  integreatly-operator git:(MGDAPI-2278) INSTALLATION_TYPE=managed-api TEST=A21 make test/e2e/single
go clean -testcache && go test ./test/functional -ginkgo.focus="A21.*" -test.v -ginkgo.v -ginkgo.progress -timeout=80m
time="2021-07-13T12:33:09+01:00" level=info msg="calling reset on all prometheus gauge vectors" custom_metrics=StartGaugeVector
=== RUN   TestAPIs
STEP: bootstrapping test environment
I0713 12:33:11.320552 1861182 request.go:635] Throttling request took 1.048851612s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/batch/v1?timeout=32s
I0713 12:33:21.890844 1861182 request.go:635] Throttling request took 1.046748542s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
Running Suite: Functional Test Suite
====================================
Random Seed: 1626175989
Will run 1 of 51 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
integreatly managed-api Functional 
  A21 - Verify AWS maintenance and backup windows
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
[BeforeEach] integreatly
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:17
[JustBeforeEach] integreatly
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:22
[It] A21 - Verify AWS maintenance and backup windows
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
I0713 12:33:33.698863 1861182 request.go:635] Throttling request took 1.042229135s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/flowcontrol.apiserver.k8s.io/v1alpha1?timeout=32s

• [SLOW TEST:45.494 seconds]
integreatly
/home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:10
  managed-api Functional
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:73
    A21 - Verify AWS maintenance and backup windows
    /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
------------------------------
SSSSSSSSTEP: tearing down the test environment

Failed to create JUnit directory: /test-run-results/junit-integreatly-operator.xml
        mkdir /test-run-results: permission deniedFailed to create JUnit report file: /test-run-results/junit-integreatly-operator.xml
        open /test-run-results/junit-integreatly-operator.xml: no such file or directory
Failed to generate JUnit report data:
        invalid argument
Ran 1 of 51 Specs in 45.494 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 50 Skipped
--- PASS: TestAPIs (63.50s)
PASS
ok      github.com/integr8ly/integreatly-operator/test/functional       63.541s
➜  integreatly-operator git:(MGDAPI-2278) INSTALLATION_TYPE=managed-api TEST=A25 make test/e2e/single
go clean -testcache && go test ./test/functional -ginkgo.focus="A25.*" -test.v -ginkgo.v -ginkgo.progress -timeout=80m
time="2021-07-13T12:34:25+01:00" level=info msg="calling reset on all prometheus gauge vectors" custom_metrics=StartGaugeVector
=== RUN   TestAPIs
STEP: bootstrapping test environment
I0713 12:34:26.387595 1861625 request.go:635] Throttling request took 1.000647159s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/packages.operators.coreos.com/v1?timeout=32s
I0713 12:34:36.900958 1861625 request.go:635] Throttling request took 1.041023263s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/autoscaling/v2beta1?timeout=32s
Running Suite: Functional Test Suite
====================================
Random Seed: 1626176065
Will run 1 of 51 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
integreatly managed-api Functional 
  A25 - Verify standalone RHMI VPC exists and is configured properly
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
[BeforeEach] integreatly
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:17
[JustBeforeEach] integreatly
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:22
[It] A25 - Verify standalone RHMI VPC exists and is configured properly
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
I0713 12:34:48.948103 1861625 request.go:635] Throttling request took 1.042953053s, request: GET:https://api.mw-collab-byoc.76il.s1.devshift.org:6443/apis/authorization.k8s.io/v1?timeout=32s

• [SLOW TEST:129.631 seconds]
integreatly
/home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:10
  managed-api Functional
  /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:73
    A25 - Verify standalone RHMI VPC exists and is configured properly
    /home/austincunningham/repo-integr8ly/integreatly-operator/test/functional/integreatly_test.go:76
------------------------------
SSSSSSSTEP: tearing down the test environment

Failed to create JUnit directory: /test-run-results/junit-integreatly-operator.xml
        mkdir /test-run-results: permission deniedFailed to create JUnit report file: /test-run-results/junit-integreatly-operator.xml
        open /test-run-results/junit-integreatly-operator.xml: no such file or directory
Failed to generate JUnit report data:
        invalid argument
Ran 1 of 51 Specs in 129.631 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 50 Skipped
--- PASS: TestAPIs (147.79s)
PASS
ok      github.com/integr8ly/integreatly-operator/test/functional       147.819s
```

**Comment by pmccarthy** [comment]
@jessesarn @briangallagher @philbrookes Just a heads up on this, should a new service update become available at some point in the near future, we will need to cherry pick this over to the RHMI 2.9 base branch so that it gets included in the patch release. If RHMI 2.10 is released before the next service update then no action is required as the change will be included by default.

**Comment by jessesarn** [comment]
ack, will do.  Thanks @pmccarthy

**Pull request merged**
