### PR TITLE
Rhoam 1 1 0 update test cases

### PR DESCRIPTION
**Pull request by psturc**
# Description
* update test cases metadata based on test cases related to 1.1.0 release
* [add a32 test case](https://github.com/integr8ly/integreatly-operator/commit/c73cc9ef16df5ef26d32f3ff68e6fd9b4b035583)

### CODE REVIEW

**Comment by psturc** [comment]
Hi @R-Lawton @MStokluska, would you have a minute to take a look at [a32 test case](https://github.com/integr8ly/integreatly-operator/commit/c73cc9ef16df5ef26d32f3ff68e6fd9b4b035583)? It was added as a follow-up test case based on https://issues.redhat.com/browse/MGDAPI-1022 and https://issues.redhat.com/browse/MGDAPI-1026
thanks

**Comment by MStokluska** [comment]
> Hi @R-Lawton @MStokluska, would you have a minute to take a look at [a32 test case](https://github.com/integr8ly/integreatly-operator/commit/c73cc9ef16df5ef26d32f3ff68e6fd9b4b035583)? It was added as a follow-up test case based on https://issues.redhat.com/browse/MGDAPI-1022 and https://issues.redhat.com/browse/MGDAPI-1026
> thanks

Hey @psturc so in terms of changes to sso route it looks good to merge to me. I am not 100% certain about the resources part!

**Comment by psturc** [comment]
I updated the test cases recently. Does it looks ok to you, @R-Lawton, @MStokluska ?

**Comment by R-Lawton** [comment]
> I updated the test cases recently. Does it looks ok to you, @R-Lawton, @MStokluska ?

yup the cpu part looks good

**Pull request merged**
