### PR TITLE
MGDAPI-3562 update test a25 to be compatible with byovpc clusters

### PR DESCRIPTION
**Pull request by cecobask**
# Issue link
https://issues.redhat.com/browse/MGDAPI-3562

# What
Updated [test A25](https://github.com/integr8ly/integreatly-operator/blob/52a4634ee77e24ab8cbedfa6943cb2338227e8b4/test/functional/aws_standalone_vpc.go#L132) so it will pass when run against RHOAM installed on BYOVPC cluster

# Verification steps
- Provision an AWS BYOVPC CCS cluster, as well as regular AWS CCS cluster
- Install RHOAM on both clusters
- Run the A25 functional test against both clusters and confirm they both pass

### CODE REVIEW

**Comment by Boomatang** [comment]
Failing ci/prow/scripts is being addressed in https://github.com/integr8ly/integreatly-operator/pull/3083 and is unrelated to changes made here.

**Comment by trepel** [comment]
the code looks good to me. I still need to run the test against byovpc cluster.

**Comment by trepel** [comment]
@cecobask The test failed for me on byovpc ccs cluster with the error described in the ticket. I think that the `verifyClusterRouteTables` needs to be skipped (or updated not to throw an error) for byovpc clusters (there are no such route tables in such case).

**Comment by cecobask** [comment]
@trepel, do you mind saving that cluster for me to investigate tomorrow? I ran it on a BYOVPC cluster too, but it didn't fail 😕

**Comment by trepel** [comment]
test passed on both non-byovpc and non-byovpc clusters. Eye review done as well

/lgtm

**Pull request merged**
