### PR TITLE
MGDAPI-3743 - Update kc-client

### PR DESCRIPTION
**Pull request by adam-cattermole**
# Issue link
[MGDAPI-3743](https://issues.redhat.com/browse/MGDAPI-3743)

# What
Update kc-client to v0.1.8

# Verification steps
It should be sufficient that e2e tests pass, possibly worth install / uninstall from this branch also.

### CODE REVIEW

**Comment by MStokluska** [comment]
I've verified that the installation works, I do not think there's a need for running an upgrade scenario.
Code changes make sense too.
Good job!
/lgtm

**Comment by KevFan** [comment]
@adam-cattermole Looks like a rebase is required :technologist:

**Comment by adam-cattermole** [comment]
Thanks Kev didn't spot this

**Pull request merged**
