### PR TITLE
[Intly-7395] Adds alerts around the rhmi_status metric

### PR DESCRIPTION
**Pull request by jjaferson**
# Description

Adds 3 alerts around the `rhmi_status` metric: 

- **RHMIInstallationControllerIsNotReconciling**
  Fires if the rhmi operator hasn't reconciled successfully in an interval of 15m over the past 1h.

- **RHMIInstallationControllerStoppedReconciling**
  Fires if the rhmi operator hasn't reconciled successfully in an interval of 30m over the past 2h.

- **RHMIOperatorInstallCompleted**
  Fires if the rhmi operator is not in its complete stage in the past 2h.
  * This rule is created in the prometheus of the `openshift-monitoring` 

https://issues.redhat.com/browse/INTLY-7395

## Verification steps

1. Install the operator via OLM
2. Verify if RHMIOperatorInstallCompleted alert is present and firing:
    - Go to Deployments, in the `redhat-rhmi-operator` namespace and click on `rhmi-operator`
    - Scale down to 0 the pod count by clicking on the down arrow
    - Go to `openshift-monitoring` namespace and look for prometheusroles `rhmi-installation-alerts`
    - Change the threshold of the metric `RHMIInstallationCompleted` to 1m 
    - In the left hand side menu, go to Monitoring >> Alerting and select only Firing in the filter bar
    - Verify if the `RHMIInstallationCompleted` shows up in the list

3. Verify if RHMIInstallationControllerIsNotReconciling and RHMIInstallationControllerStoppedReconciling are present and firing:
    - Find route for Prometheus in `redhat-rhmi-middleware-monitoring-operator` namespace
    - Open its URL
    - Go to the Alerts tab and look for `RHMIInstallationControllerIsNotReconciling` or `RHMIInstallationControllerStoppedReconciling`
     - Click on the `expr`
     - In the query page change the **15m** to **1m** and click on the excute buttom `rhmi_status{stage="complete"} and on(namespace) rate(controller_runtime_reconcile_total{controller="installation-controller"}[1m]) == 0`
      - Verify if the `rhmi_status` metric is returned

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] This change requires a documentation update 
- [x] I have added a test case that will be used to verify my changes

### CODE REVIEW

**Comment by R-Lawton** [comment]
Just documenting what was discussed in the call. RHMIOperatorInstallDelayed needs to be followed up for the reasoning of the ==1

**Comment by jjaferson** [comment]
flake e2e test reported here https://issues.redhat.com/browse/INTLY-7197

/retest

**Pull request merged**
