### PR TITLE
Relaxing EC2 PublicIP check

### PR DESCRIPTION
**Pull request by trepel**
# Description

It seems the PublicIP check is too strict and the script fails even if the publicIP is correct.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Verification Steps
eye review, run the script. I will attach the log from Jenkins in a minute

### CODE REVIEW

**Comment by trepel** [comment]
Successful build using this PR:
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Public/job/trepel-ec2-deploy/69

**Review by austincunningham — APPROVED** [review]
/lgtm
/approve

**Comment by austincunningham** [comment]
beat me to it

**Pull request merged**
