### PR TITLE
Fix test-cases-lint pipeline 

### PR DESCRIPTION
**Pull request by b1zzu**
# Description

Some test cases have been merged even if the pipeline was failing, this PR is fixing all issues so that the test-cases-lint pipeline can return green

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

This has a merge conflict

**Comment by b1zzu** [comment]
/unhold 

Merge conflicts fixed

**Comment by b1zzu** [comment]
@tonyxrmdavidson @damienomurchu I need the LGTM again

**Pull request merged**
