### PR TITLE
Adds CRO version 0.22.3

### PR DESCRIPTION
**Pull request by jjaferson**
adds cro version 0.22.3

verification:

ensure rhoam installs successfully
ensure cro is 0.22.3 in both the rhoam status block and the container image

### CODE REVIEW

**Comment by KevFan** [comment]
Verified CRO 0.22.3 Installation :+1: 

Screenshot from 2020-11-03 12-02-45

/lgtm

**Comment by laurafitzgerald** [comment]
already verified, quick eyeball of the code. looks all good. 
/approve

**Pull request merged**
