### PR TITLE
MGDAPI-498 - Marin3r Critical SLO Panel

### PR DESCRIPTION
**Pull request by KevFan**
# Description

Branched from https://github.com/integr8ly/integreatly-operator/pull/1502 with an additional commit to fix dashboard panel were not loaded when Critical SLO Dashboard page is initially visited

Jira:
* https://issues.redhat.com/browse/MGDAPI-498
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Verification

- Install RHOAM from this branch
- Run though E04B test case https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
- Access Grafana and verify two alerts are firing in the Critical SLO dashboard in the Marin3r Panel
Screenshot from 2020-12-15 16-54-15
Screenshot from 2020-12-15 17-15-11

## Checklist
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by obrienrobert** [comment]
Verified that 2 Mari3r alerts fired when executing the test case:
mari3r_alerts

@KevFan the E04B may have to be updated once this is merged to scale down the Mari3r deployments and trigger the alerts.

**Comment by KevFan** [comment]
> Verified that 2 Mari3r alerts fired when executing the test case:
> mari3r_alerts
> 
> @KevFan the E04B may have to be updated once this is merged to scale down the Mari3r deployments and trigger the alerts.

Thanks @obrienrobert, good point :+1: E04B probably should also include scaling down customer-grafana also in this case, though I think currently the alerts from scalling down are all `warning` severity so won't be reflected in the dashboard for now. 
* https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/marin3r/prometheusRules.go
* https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/grafana/prometheusRules.go
I can update the test case to include scaling down these deployments as part of this PR, what do you think ? :thinking:

**Comment by obrienrobert** [comment]
@KevFan If using the scripts in the test case to scale the 3scale deployment down also causes the marin3r alerts to trigger in the SLO dashboard then I think everything looks good to me!

**Comment by KevFan** [comment]
> @KevFan If using the scripts in the test case to scale the 3scale deployment down also causes the marin3r alerts to trigger in the SLO dashboard then I think everything looks good to me!

Cool, thanks @obrienrobert. Yeah the current test case will cause the Marin3r critical alerts to fire due to the envoy side car container is down once the 3scale pods are scaled down  :+1: 
* https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/threescale/envoy_prometheusRules.go#L22-L41

**Pull request merged**
