### PR TITLE
Create user-permissions.md

### PR DESCRIPTION
**Pull request by maleck13**
# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by maleck13** [comment]
@matskiv ok to review

**Comment by matskiv** [comment]
@maleck13 Are you aware of this spreadsheet, that describes the permissions - https://docs.google.com/spreadsheets/d/1SplYIdK7Z4SBdUzceDyM24XL2pkeD7EDTbL4-Et7nZQ ?
Depending on the target audience, we might want to stick to one place for this information. Wdyt?

**Comment by maleck13** [comment]
@matskiv I was not aware of that. hmm I am torn as I feel there is value in it being in the upstream also

**Comment by matskiv** [comment]
Maybe we keep general information in the upstream, but don't go into details on per product level?
Linking to a spreadsheet would be nice on one hand, but it's not public, so not sure if we should add it 🤔

**Pull request closed without merging**
