### PR TITLE
MGDAPI-5694 Added guide that details setting up OBO with RHOAM

### PR DESCRIPTION
**Pull request by carlkyrillos**
# Issue link
[MGDAPI-5694](https://issues.redhat.com/browse/MGDAPI-5694)

# What
This PR add a short guide that walks through setting up OBO alongside RHOAM. The PR consists of the guide and the yaml file needed to create the CRs.

# Verification steps
Go through the guide and confirm that you can reach the Prometheus UI and the Alertmanager UI via port forwarding.

### CODE REVIEW

**Comment by Fiona-Waters** [comment]
I have run through the `obo_setup.md` file and can confirm that I could reach the Prometheus UI and the Alertmanager UI via port forwarding.

Prometheus 

image

Alertmanager

image

I wonder if it might be nice to add a little bit of info/context about OBO at the beginning of the document also. If this is needed depends on who will be using it. Just a thought.

**Comment by carlkyrillos** [comment]
> I have run through the `obo_setup.md` file and can confirm that I could reach the Prometheus UI and the Alertmanager UI via port forwarding.
> 
> Prometheus
> 
> image
> 
> Alertmanager
> 
> image
> 
> I wonder if it might be nice to add a little bit of info/context about OBO at the beginning of the document also. If this is needed depends on who will be using it. Just a thought.

@Fiona-Waters Thank you for the review, I updated the doc with links to the Epic Brief and Miro board to provide some more context.

**Pull request merged**
