### PR TITLE
INTLY-4489 - Upgrade Fuse online and fix service discovery

### PR DESCRIPTION
**Pull request by matskiv**
**JIRAs:**
https://issues.redhat.com/browse/INTLY-4489
https://issues.redhat.com/browse/INTLY-4527 (motivation for the Fuse upgrade)

**What:**
- upgraded Fuse to 7.5, manifests are based on [internal repo](http://pkgs.devel.redhat.com/cgit/containers/fuse-online-operator/tree/manifests/7.5.0?h=fuse-7.5-openshift-rhel-7)
- fixed service discovery of (shared) Fuse OpenAPI integrations with 3Scale
- dependency update (separate commit for easy filtering out)
- small improvement to tests code (also separate commit)

**Verification steps:**
Install Integreatly with this PR. 3Scale and Fuse installation needs to complete to proceed with verification.
Verify that new version(7.5) of fuse is displayed in Installation CR status.
Create a htpasswd IDP (`./scripts/setup-htpass-idp.sh`)
Login into OpenShift as customer-admin while the operator is running (so the users are synced into 3Scale)
Open Fuse Online console and create an OpenAPI based integration:
Screenshot 2020-01-08 at 18 08 51
Value for the URL field: `https://raw.githubusercontent.com/syndesisio/syndesis-quickstarts/master/api-provider/task-api.json`
Click Next (twice?) and then click "Publish" (on the top right).
Wait until the integration is built and deployed successfully.
Login into 3Scale console (`https://3scale-admin...`)
Click on "New Product":
Screenshot 2020-01-08 at 17 19 56
Select "Import from OpenShift" (there might be an "Authenticate" button next to this option, click on that first and approve the permissions)
Namespace and Name fields should become populated with a discovered services:
Screenshot 2020-01-08 at 18 19 42
Click "Create Product" and verify there are no errors displayed.

### CODE REVIEW

**Comment by matskiv** [comment]
E2E failed due to unexpected number of route in Fuse ns.
Looking at that now. Likely the test needs to be updated.

**Comment by JameelB** [comment]
/approve

Verified on OSD. Installation completed successfully. Fuse online was upgraded to 7.5 and service discovery worked successfully in 3Scale.

**Pull request merged**
