### PR TITLE
MGDAPI-2489 - 3scale api error

### PR DESCRIPTION
**Pull request by jjaferson**
# Description

There is a issue when creating new tenant accounts in 3scale and smtp is not configured correctly the 3scale API create the tenant account but returns an error, to avoid this from happening the smtp secret needs to be created with empty values so the 3scale API doesn't attempt to send an email after the creation of the new tenant account.

https://issues.redhat.com/browse/MGDAPI-2489

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Verification steps
1) Install the operator from this branch INSTALLATION_TYPE=multitenant-managed-api make cluster/prepare/local && INSTALLATION_TYPE=multitenant-managed-api make code/run
2) Go to the 3scale API under the master account and create a new tenant account or run this curl command below
```
curl -v  -X POST "https://master.<CLUSTER-URL>/master/api/providers.xml" -d 'access_token=<MASTER-TOKEN>&org_name=test2&username=test2&email=test2%40test2.com&password=MT'
```
3) Make sure an error is not returned from the 3scale API.

### CODE REVIEW

**Comment by Patryk-Stefanski** [comment]
1.Installed operator locally  from `3scale-api-error` branch
2.Logged into 3 scale API  as a master.
3.Created a new account successfully without any errors.

/lgtm

**Comment by Boomatang** [comment]
Adding lgtm on behalf of @Patryk-Stefanski 

/lgtm

**Comment by pmccarthy** [comment]
@jjaferson @MStokluska  would it be possible to limit the creation of the smtp secret to the `multitenant-managed-api` installation type? 

We currently have an alert checking that the smtp secret exists which is used by SRE in production to determine if the integration with the SendGrid service in OCM is working as expected. If we're always creating the smtp secret it means that this alert will always be green and we can no longer identify issues with the SendGrid service not creating legitimate credentials on cluster.

**Comment by jjaferson** [comment]
> @jjaferson @MStokluska would it be possible to limit the creation of the smtp secret to the `multitenant-managed-api` installation type?
> 
> We currently have an alert checking that the smtp secret exists which is used by SRE in production to determine if the integration with the SendGrid service in OCM is working as expected. If we're always creating the smtp secret it means that this alert will always be green and we can no longer identify issues with the SendGrid service not creating legitimate credentials on cluster.

@pmccarthy this PR only removes the dummy data set in the smtp secret to avoid the 3scale api to return errors when the smtp account is not valid, if it's the intention to remove the creation of the smtp I would suggest we create another ticket to address that as it will bring up other issues.

**Comment by MStokluska** [comment]
@pmccarthy I've verified it again, turns out it was a false alert and this PR is ready to be approved. Sorry for holding it up @jjaferson

**Pull request merged**
