### PR TITLE
Added some missing steps to the test case h24

### PR DESCRIPTION
**Pull request by austincunningham**
# Description

- Added some missing steps to the test case h24

## Type of change

- [x] Update test-case

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by austincunningham** [comment]
Fyi @joaedwar this test case is base off the doc [Deploying a self-managed APIcast API gateway](https://access.redhat.com/documentation/en-us/red_hat_openshift_api_management/1/guide/757a6ad2-8ca0-4150-b949-cbb1ee4e5969#_ca8e43cd-5336-4a9e-8d42-8cd5ceef1299). In this PR I have update this test case where the it is unclear see [jira comment ](https://issues.redhat.com/browse/MGDAPI-1851?focusedCommentId=16223168&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16223168). It may we worth updating the `Deploying a self-managed APIcast API gateway` docs with some of the same changes

**Comment by joaedwar** [comment]
@austincunningham Thanks a million. Will incorporate changes. Cheers

**Pull request merged**
