### PR TITLE
cssre-2126 moving sops per jira

### PR DESCRIPTION
**Pull request by sclarkso**
# Issue link
https://issues.redhat.com/browse/CSSRE-2126

# What
I am moving sops from /sops/2.x/ directory to /sops/rhoam/ directory as 2.x no longer exists and was causing confusion.  These sops are referenced by the go code I have updated in this PR.

# Verification steps
I am changing the files that I was told to change.  I do not know personally that these changes are correct as I do not know Go.  This will need to be reviewed.

### CODE REVIEW

**Comment by sclarkso** [comment]
Is this test failing because the SOPs don't exist yet?  That PR hasn't been merged yet: https://github.com/RHCloudServices/integreatly-help/pull/838

**Comment by Boomatang** [comment]
@sclarkso It seem you are having a formatting issue. If you run `make code/fix` this should resolve your issue. You can run the ci/prow/format check locally with `make code/check`. I would also like to ask you to amend the commit message. The commit messages should start a jira number or issue ID.

**Comment by sclarkso** [comment]
@Boomatang Thanks for the help, so after I run make code/fix I need to commit those new changes?  Or should I delete this branch and start over in your opinion?

` sclarkso  ~  repos  integreatly-operator  make code/check
golint ./pkg/... | grep -v  "comment on" | grep -v "or be unexported"
/bin/bash: line 1: golint: command not found
make: *** [Makefile:183: code/check] Error 1
 sclarkso  ~  repos  integreatly-operator  git status
On branch cssre-2126-sop-cleanup
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   pkg/resources/sop_url.go

no changes added to commit (use "git add" and/or "git commit -a")
`

**Comment by MStokluska** [comment]
by-passing codecov

**Pull request merged**
