### PR TITLE
MGDAPI-5730 updating to use ClusterPackage

### PR DESCRIPTION
**Pull request by Fiona-Waters**
# Issue link
[MGDAPI-5730](https://issues.redhat.com/browse/MGDAPI-5730)

# What
Updating to use ClusterPackage

### CODE REVIEW

**Comment by carlkyrillos** [comment]
The vendor check is passing for me when I run it locally and I verified the change works.
/lgtm

**Comment by laurafitzgerald** [comment]
/override ci/prow/multitenant-rhoam-e2e
/override ci/prow/rhoam-e2e 
/override ci/prow/vendor

Overriding vendor because the image build is failing. The package is available locally and vendor check is completing sucessfully locally. 
Overriding e2e tests are they require some fixing for this branch.

**Pull request merged**
