### PR TITLE
MGDAPI-4413 Test case updates for 1.25.0

### PR DESCRIPTION
**Pull request by trepel**
# Issue link

https://issues.redhat.com/browse/MGDAPI-4413

# What

Just updates of test cases (targets) for 1.25.0

# Verification steps

Check that these were indeed done in 1.25.0:
project = MGDAPI AND issuetype = Task AND fixVersion = 1.25.0 AND labels = test-case

### CODE REVIEW

**Comment by martinhesko** [comment]
Verified that all of the test cases were done this sprint,
/lgtm

**Comment by KevFan** [comment]
Code coverage checks not required as it is a test case documentation update - overriding

/override codecov/project

**Comment by trepel** [comment]
Cheers, @KevFan I did not know about that override! Quite useful.

**Pull request merged**
