### PR TITLE
MGDAPI-2073 - Address high CVEs discovered in keycloak-operator image…

### PR DESCRIPTION
**Pull request by valerymo**
Address high CVEs discovered in keycloak-operator image (used in RHOAM v1.8.0)
Jira: https://issues.redhat.com/browse/MGDAPI-2073

# Description
Upgrade to latest - 14.0.0 version of keycloack operator. This version is Passed vulnerability scanning - No vulnerabilities.  
https://quay.io/repository/keycloak/keycloak-operator?tab=tags
It's replacing 13.0.1 version  of keycloack operator that has 1 High-level vulnerability.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by austincunningham** [comment]
The code changes look good to me. 

Wondering how to verify do you have steps you took to verify the change ?

**Comment by valerymo** [comment]
Hi @austincunningham , thank you for review!  
Regarding testing. I adding log/steps below (part from history) + attached file as I see some error now in redhat-rhoam-rhsso-operator.
$ oc whoami --show-server
https://api.valerym01.2dv3.s1.devshift.org:6443

redhat-rhoam-user-sso-operator
==============================
10026  2021-06-24 17:14:33 oc proejct redhat-rhoam-user-sso-operator
10031  2021-06-24 17:15:11 oc describe pod keycloak-operator-6b48759955-6q5h4 |less
[GitHub]$ oc describe pod keycloak-operator-6b48759955-6q5h4 |grep 14.0
              containerImage: quay.io/keycloak/keycloak-operator:14.0.0
    Image:         quay.io/keycloak/keycloak-operator:14.0.0
      OPERATOR_CONDITION_NAME:      keycloak-operator.v14.0.0
[GitHub]$ oc describe pod keycloak-operator-6b48759955-6q5h4 |grep 13.0
10033  2021-06-24 17:15:53 oc logs  keycloak-operator-6b48759955-6q5h4 |grep -i Error
10034  2021-06-24 17:15:59 oc logs  keycloak-operator-6b48759955-6q5h4 |grep -i Fail
            FAILED Update RHSSO Deployment (StatefulSet)"}

redhat-rhoam-rhsso-operator
============================
10014  2021-06-24 13:05:10 oc project redhat-rhoam-rhsso-operator
10015  2021-06-24 13:05:15 oc get pod
10016  2021-06-24 13:05:26 oc describe pod keycloak-operator-b65f86d99-jlg2w
[GitHub]$ oc describe pod keycloak-operator-b65f86d99-jlg2w |grep 14.0
              containerImage: quay.io/keycloak/keycloak-operator:14.0.0
    Image:         quay.io/keycloak/keycloak-operator:14.0.0
      OPERATOR_CONDITION_NAME:      keycloak-operator.v14.0.0
[GitHub]$ oc describe pod keycloak-operator-b65f86d99-jlg2w |grep 13.0
[GitHub]$ oc logs keycloak-operator-b65f86d99-jlg2w > log
** I see some errors now, so adding log 
[log.txt](https://github.com/integr8ly/integreatly-operator/files/6710119/log.txt)

**Comment by austincunningham** [comment]
# Verified
rhoam installed without issue

rhsso-operator pod pointing at 14.0.0 image
```bash
oc project redhat-rhoam-rhsso-operator 
Now using project "redhat-rhoam-rhsso-operator" on server "https://api.mw-collab-byoc.7jfv.s1.devshift.org:6443".
oc get po
NAME                                READY   STATUS    RESTARTS   AGE
keycloak-operator-b65f86d99-65rkg   1/1     Running   0          4m31s
rhmi-registry-cs-d58ns              1/1     Running   0          4m59s
oc get po keycloak-operator-b65f86d99-65rkg -o json |jq .status.containerStatuses   
[
  {
    "containerID": "cri-o://1b912c22ac233352cf4abc78f543cbf52ffb09e1b1d5096350954e0581c90d9c",
    "image": "quay.io/keycloak/keycloak-operator:14.0.0",
    "imageID": "quay.io/keycloak/keycloak-operator@sha256:50f954a75f2b52096054b86af80e326b8a5d86eced42ef357aac02ed0959be41",
    "lastState": {},
    "name": "keycloak-operator",
    "ready": true,
    "restartCount": 0,
    "started": true,
    "state": {
      "running": {
        "startedAt": "2021-06-24T14:20:37Z"
      }
    }
  }
]
```

user-sso-operator pod
```bash
oc project redhat-rhoam-user-sso-operator 
Now using project "redhat-rhoam-user-sso-operator" on server "https://api.mw-collab-byoc.7jfv.s1.devshift.org:6443".
oc get po
NAME                                 READY   STATUS    RESTARTS   AGE
keycloak-operator-6b48759955-tfjnh   1/1     Running   0          17s
rhmi-registry-cs-5qpp4               1/1     Running   0          71s
oc get po keycloak-operator-6b48759955-tfjnh -o json |jq .status.containerStatuses
[
  {
    "containerID": "cri-o://6af94d8c9b0d55f60c80b255696e57e21d43b4ff1685058f8e14bb3bfb4a70ab",
    "image": "quay.io/keycloak/keycloak-operator:14.0.0",
    "imageID": "quay.io/keycloak/keycloak-operator@sha256:50f954a75f2b52096054b86af80e326b8a5d86eced42ef357aac02ed0959be41",
    "lastState": {},
    "name": "keycloak-operator",
    "ready": true,
    "restartCount": 0,
    "started": true,
    "state": {
      "running": {
        "startedAt": "2021-06-24T14:37:33Z"
      }
    }
  }
]
```
installation of rhsso and user-sso completed, @valerymo not to worried about the errors as they appear to be the standard object has updated errors which are common with operator's
/lgtm

**Pull request merged**
