### PR TITLE
Single-Stage RHOAM demo

### PR DESCRIPTION
**Pull request by makslion**
# Issue link
[MGDAPI-3747](https://issues.redhat.com/browse/MGDAPI-3747)

# What
Demo of the Single-Stage RHOAM. This PR isn't intended to be merged at this stage of development. 

# Verification steps
Not applicable

### CODE REVIEW

**Comment by austincunningham** [comment]
message

**Comment by makslion** [comment]
rebased of master to run e2e tests 

/test rhoam-e2e multitenant-rhoam-e2e

**Comment by makslion** [comment]
rebased to run e2e tests 

/test rhoam-e2e

**Comment by makslion** [comment]
rebased and brought MT RHOAM to the single stage installation. 

/test rhoam-e2e multitenant-rhoam-e2e

**Comment by makslion** [comment]
This PR is not needed any longer. The code will be merged here #2729

**Pull request closed without merging**
