### PR TITLE
MGDAPI-5904 Re-added removed OBO PrometheusRules

### PR DESCRIPTION
**Pull request by carlkyrillos**
# Issue link
JIRA: [MGDAPI-5904](https://issues.redhat.com/browse/MGDAPI-5904)

# What
Some PrometheusRules were mistakenly removed when implementing the [OO uninstall logic](https://github.com/integr8ly/integreatly-operator/pull/3278/commits/c6639420c874c4a4a59166b15f12afeb1093d2bd#diff-5a222ffa7e3ccbffdfdbbc30a65069fed706079810a31e1b8074a6f5eacf257f). This PR re-adds them but also slightly refactors them:
- Renames the `ksm-endpoint-alerts` group to be `obo-ksm-endpoint-alerts` since they are all observability related PrometheusRules
- Removes the following alerts as they don't apply with OBO:
  - `RHOAMMiddlewareMonitoringOperatorApplicationMonitoringMetricsServiceEndpointDown`
  - `RHOAMMiddlewareMonitoringOperatorGrafanaServiceEndpointDown`
  - `RHOAMMiddlewareMonitoringOperatorRhmiRegistryCsServiceEndpointDown`

This PR also updates the `C04 - Verify Alerts exist` e2e test to reflect the refactored PrometheusRules.

# Verification steps
1. Provision a cluster
2. Checkout this PR
3. When the cluster is ready prepare for an OLM install: 
    ```bash
    make cluster/prepare/local
    ```
4. Create a CatalogSource using this [index image](https://quay.io/repository/ckyrillo/managed-api-service-index?tab=tags&tag=1.38.0) (you can also build your own from this PR if you'd prefer):
    ```bash
    cat << EOF | oc create -f -
    apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: rhoam-operators
      namespace: openshift-marketplace
    spec:
      sourceType: grpc
      image: quay.io/ckyrillo/managed-api-service-index:1.38.0
    EOF
    ```
5. Install the RHOAM operator through the OperatorHub
6. Create an RHMI CR:
    ```bash
    IN_PROW=false USE_CLUSTER_STORAGE=true make deploy/integreatly-rhmi-cr.yml
    ```
7. When the installation is complete, forward the Prometheus port:
    ```bash
    oc port-forward services/prometheus-operated -n redhat-rhoam-operator-observability 9090:9090
    ```
8. Navigate to the `Alerts` [page](http://127.0.0.1:9090/alerts) and confirm that all the PrometheusRules have been re-added
9. Run the `C04 - Verify Alerts exist` e2e test and confirm it passes:
    ```bash
    TEST="C04 - Verify Alerts exist" make test/e2e/single 
    ```

### CODE REVIEW

**Comment by MStokluska** [comment]
/lgtm
Alerts are added back in and the test passes. Good job!

**Comment by carlkyrillos** [comment]
@briangallagher Can you override the codecov check? This PR should actually improve coverage from where it was before these PrometheusRules were removed because we were able to eliminate some unused rules in this PR.

**Pull request merged**
