### PR TITLE
temporarilly added memory and cpu limits to the operator

### PR DESCRIPTION
**Pull request by pawelpaszki**
# Description
https://issues.redhat.com/browse/INTLY-7790

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by pawelpaszki** [comment]
I will run it against my cluster as soon as it becomes available

**Comment by matskiv** [comment]
/lgtm

Let's run it on OSD cluster for a few hours to see that we are requesting enough CPU.

**Comment by pawelpaszki** [comment]
@matskiv CPU usage never went above 35MB. Is it ok to merge?

**Pull request merged**
