### PR TITLE
MGDAPI-4485 create alert for absent cro metrics

### PR DESCRIPTION
**Pull request by cecobask**
# Issue link
https://issues.redhat.com/browse/MGDAPI-4485

# What
In an effort to help with root cause analysis of CRO alerts ensure that alerts do not fire due to missing or absent CRO metrics. Instead create a separate alert that will fire when metrics are absent.

# Verification steps
- Provision an AWS CCS cluster
- Prepare the cluster and install RHOAM from the latest stable version `v1.27.0`:
```
git checkout tags/rhoam-v1.27.0 -b rhoam-v1.27.0

make cluster/prepare/local LOCAL=false

cat << EOF | oc create -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhoam-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/tdimov0/managed-api-service-index:1.27.0
EOF

make deploy/integreatly-rhmi-cr.yml LOCAL=false USE_CLUSTER_STORAGE=false
```
- Install the RHOAM operator from Operator Hub
- Wait until the Installation completes successfully
- Ensure no alerts are firing
- Patch the catalog source to point at the image which contain the changes from this pull request and upgrade RHOAM:
```
oc patch catalogsource rhoam-operators -n openshift-marketplace --type=json -p='[{"op": "replace", "path": /spec/image, "value": "quay.io/tdimov0/managed-api-service-index:1.28.0"}]'
```
- Wait until the upgrade completes successfully
- Ensure none of these alerts are firing:
```
***PostgresInstanceUnavailable
***PostgresConnectionFailed
***PostgresResourceStatusPhasePending
***PostgresResourceDeletionStatusPhaseFailed
***RedisCacheUnavailable
***RedisCacheConnectionFailed
***RedisResourceStatusPhasePending
***RedisResourceDeletionStatusPhaseFailed
```
- Scale down the `cloud-resource-operator` deployment to simulate triggering the new alert:
```
oc patch deployment cloud-resource-operator -n redhat-rhoam-cloud-resources-operator --type=json -p='[{"op": "replace", "path": /spec/replicas, "value": 0}]'
```
- After ~5 minutes verify that the `RHOAMCloudResourceOperatorMetricsMissing` alert is firing
- Scale up the `cloud-resource-operator` deployment back to what it was before:
```
oc patch deployment cloud-resource-operator -n redhat-rhoam-cloud-resources-operator --type=json -p='[{"op": "replace", "path": /spec/replicas, "value": 1}]'
```
- Ensure no alerts are firing

### CODE REVIEW

**Comment by carlkyrillos** [comment]
@cecobask I tried verifying this but the `RHOAMCloudResourceOperatorMetricsMissing` alert began firing as soon as the upgrade from 1.27.0 to 1.28.0 completed and before I could even scale down the CRO deployment.

**Comment by cecobask** [comment]
> @cecobask I tried verifying this but the `RHOAMCloudResourceOperatorMetricsMissing` alert began firing as soon as the upgrade from 1.27.0 to 1.28.0 completed and before I could even scale down the CRO deployment.

Hey @carlkyrillos, during the upgrade was the alert in firing state or it just triggered for a short period of time?
Do you happen to have an estimate how long the alert took to stop firing? I can increase the fire time from 5m to 10m if that makes sense?

**Pull request merged**
