### PR TITLE
MGDAPI-1173 - update github.com/openshift/api and k8s.io/api versions to support gogo/protobuf 1.3.2

### PR DESCRIPTION
**Pull request by valerymo**
# What
github.com/openshift/client-go and k8s.io/client-go  version changed to newer to support gogo/protobuf 1.3.2
Also - more k8s.io libs were updated from v0.20.6  and v0.20.2 to v0.22.2, to have same version for all k8s.io.

# Verification steps
- Rhoam e2e tests
- check vulnerability issue

### CODE REVIEW

**Comment by valerymo** [comment]
Tests done as e2e single test for following tests: E01|E02|E03|E05|E09
Passed - All
Command used example: $TEST=E01 INSTALLATION_TYPE=managed-api make test/e2e/single
Log - attached
[test_MGDAPI-1173.txt](https://github.com/integr8ly/integreatly-operator/files/7448425/test_MGDAPI-1173.txt)

**Comment by laurafitzgerald** [comment]
Thanks for the test logs @valerymo 
Looks like you need a rebase now. :/ 
We are in testing week now so if you want to address this next week that's fine.
It won't merge until the release is done anyway. 👍

**Comment by valerymo** [comment]
@laurafitzgerald    sorry, I actually wanted ask you about this rebase, I saw it. But there are 400+ files changed in vendors, so it's actually not rebase but Vendors Upgrade, so wanted to ask you how better do it

**Comment by laurafitzgerald** [comment]
@valerymo the easiest way to do it is to carry out the rebase on master - fix the conflict in go.mod and vendor/modules.txt once that is done run a `make vendor/fix` which will resolve all the dependencies, git add everything updated in the vendor directory and continue the rebase. Once the rebase is done run a `make vendor/check` to ensure that everything went okay during the rebase. The check shouldn't fail if everything went okay. Let me know if you want to step through it at some point. 👍

**Pull request merged**
