### PR TITLE
RHMI-2.3.0 UXD test-cases

### PR DESCRIPTION
**Pull request by tonyxrmdavidson**
# Description
Update UXD test-cases for RHMI-2.3.0 release testing (Sprint 18)

## Type of change

Deletion of un-needed test-cases and update to existing test-cases to capture related recent updates.

### CODE REVIEW

**Comment by pawelpaszki** [comment]
The content looks good

**Comment by matskiv** [comment]
/hold 
I don't want this to accidentally reset retesting on #756, it should be done in the next hour or so. I will unhold after that.

**Pull request merged**
