### PR TITLE
Renaming API usage alerts to reference RHOAM

### PR DESCRIPTION
**Pull request by pmccarthy**
# Description
Renaming the following API usage alerts:
```
Level1ThreeScaleApiUsageThresholdExceeded -> RHOAMApiUsageLevel1ThresholdExceeded
Level2ThreeScaleApiUsageThresholdExceeded -> RHOAMApiUsageLevel2ThresholdExceeded
Level3ThreeScaleApiUsageThresholdExceeded -> RHOAMApiUsageLevel3ThresholdExceeded
```
This ensures consistency with what we've done with RHMI in the past

## Verification
1. Install RHOAM from this branch on an OSD cluster
2. Login to the middleware-monitoring prometheus instance
3. Verify that the new alert names are in place and that the old ones are not listed

## Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
Functionality Verified in cluster
Screenshot 2020-11-04 at 10 24 51
/approve

**Comment by laurafitzgerald** [comment]
Is test-case-lint new? 🤔

**Comment by pmccarthy** [comment]
@laurafitzgerald yeah I'm not sure about that one. The job is failing for an unrelated reason:
```
sh: oc: command not found
```

**Comment by KevFan** [comment]
@laurafitzgerald @pmccarthy `test-cases-lint` is related to formatting of test cases. Running `make test-cases/fix` and pushing the formatted test case should fix it the prow job :thinking: 
* https://github.com/integr8ly/integreatly-operator/blob/master/make/test-cases.mk#L8

**Comment by philbrookes** [comment]
/override ci/prow/e2e
/override ci/prow/rhoam-e2e

Already passed

**Pull request merged**
