### PR TITLE
expect new configmaps for alertmanager setup

### PR DESCRIPTION
**Pull request by aidenkeating**
currently there is a manual sop for setting up alertmanager config
via a secret

in this commit two new secrets are now expected by the operator:
- a secret for dead mans snitch url
- a secret for pagerduty service key

these secrets will be used by the operator to create a new config
secret for alertmanager called.

verification:
- run 'make code/run'
- ensure the 'redhat-rhmi-smtp' secret is created
- ensure the 'redhat-rhmi-pagerduty' secret is created
- ensure the 'redhat-rhmi-dead-mans-snitch' secret is created
- ensure the operator isn't halted waiting for the secrets
- ensure the monitoring stage completes successfully
- ensure the secret 'alertmanager-application-monitoring' exists
  in the monitoring operator namespace and follows the structure
  in https://issues.redhat.com/browse/INTLY-5200
- ensure the values from the three pre-requisite secrets are used
  in the new 'alertmanager-application-monitoring' secret data
- ensure the 'smtp to' email addresses in the config secret are
  formatted as noreply@<alertmanager-route>
- ensure the new config is visible through the ui of prometheus/
  alertmanager
- run 'ALERTING_EMAIL_ADDRESS=akeating@redhat.com make code/run'
- wait for the monitoring reconciliation to complete
- ensure the 'smtp to' email addresses in the config secret are
  'akeating@redhat.com'

### CODE REVIEW

**Comment by HubertStefanski** [comment]
## Prometheusrule being triggered 
by scaling down console pod to 0, this query then can't reach the endpoint address
image
## Pagerduty alert email 
image
## Sendgrid email from alertmanager
image
The phone pagerduty also works and from testing appears to have the fastest response time for the current settings,
Rules in pagerduty services were set to respond to any `critical` severity alerts raised
image
it also appears that by default alerts are being suppressed if no explicit conditions are specified in the service page

**Comment by aidenkeating** [comment]
Cleaning up test comments due to prow being unavailable

**Comment by austincunningham** [comment]
/lgtm
already verified
/approved

**Pull request merged**
