### PR TITLE
Expose upgrade metrics

### PR DESCRIPTION
**Pull request by jjaferson**
# Description

This PR is rebased off https://github.com/integr8ly/integreatly-operator/pull/776

### CODE REVIEW

**Comment by matskiv** [comment]
I removed "approved" label.
I just want to clarify something about this metric before we merge. Sorry about the potential delay caused by this.

**Comment by matskiv** [comment]
Verified:
Screenshot 2020-05-27 at 14 44 09
Screenshot 2020-05-27 at 14 43 56
/lgtm
/approve

**Comment by david-martin** [comment]
Retroactively tagging @openshift/openshift-team-monitoring for code changes that expose `rhmi_version` metric. 
See #795 for cluster-monitoring-operator PR to whitelist this metric.

**Pull request merged**
