### PR TITLE
test: e2e - monitoring resources created check

### PR DESCRIPTION
**Pull request by jhellar**
## Description

https://issues.redhat.com/browse/INTLY-4227

### CODE REVIEW

**Comment by grdryn** [comment]
The e2e test failure here is _not_ the same as the one I described on the stand-up earlier. This looks more like it's related to this PR.

**Comment by jhellar** [comment]
@davidkirwan the tests now passed. Seems that alerts were not created properly when the test failed.

**Comment by davidkirwan** [comment]
/lgtm

Folks if you could approve please:
/cc @david-martin 
/cc @matskiv 
/cc @philbrookes

**Pull request merged**
