### PR TITLE
3scale update to 0.6.0

### PR DESCRIPTION
**Pull request by fh-automatron**
Update 3scale manifest to 0.6.0 

This is an automatically generated branch to track the '0.6.0' version of the '3scale' OLM manifests.
This branch will be automatically updated with any changes related to this version until it finally GAs. 

Changes required to fix installation issues should be applied to this branch following the usual [PR Workflow](https://github.com/integr8ly/delorean/blob/master/docs/integrealy-ci/prow-pr-workflow.md)

More details about the Early Warning System that generated this can be found [here](https://github.com/integr8ly/delorean/tree/master/docs/ews)

## Type of change

- [X] Product Update

## Checklist
- [ ] Older product manifests (N-2) have been removed
- [ ] Operator and Product Versions are updated correctly
- [ ] Go Modules are updated if required

### CODE REVIEW

**Comment by b1zzu** [comment]
The E2E tests failed to install the 3scale within the given timeout

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/integr8ly_integreatly-operator/944/pull-ci-integr8ly-integreatly-operator-master-e2e/1285605235808538624/artifacts/e2e/rhmi.yaml
```
products:
      name: products
      phase: in progress
      products:
        3scale:
          name: 3scale
          operatorversion: ""
          version: ""
          host: ""
          type: ""
          mobile: false
          status: in progress
```

I will try to see if I can understand why from the 3scale operator logs

**Comment by mikenairn** [comment]
``` 
--- FAIL: TestIntegreatly/integreatly/Verify_Alerts_are_not_firing_during_or_after_installation_apart_from_DeadMansSwitch (3.93s)
             alerts_firing.go:99: 
                The following alerts were not fired, but were expected to be firing:
                	alert: DeadMansSwitch
                The following alerts were fired:
                	alert: ThreeScaleZyncPodAvailability 
```

```         
--- FAIL: TestIntegreatly/integreatly/F05_-_Verify_Replicas_Scale_correctly_in_Threescale (101.90s)
            scale_up_replicas_threescale.go:50: Checking correct number of replicas are set
            scale_up_replicas_threescale.go:60: Checking correct number of updated replicas are set
            scale_up_replicas_threescale.go:70: Checking correct number of updated replicas are set
            scale_up_replicas_threescale.go:80: Checking correct number of replicas has been reset
            scale_up_replicas_threescale.go:251: Replicas Ready 1
            scale_up_replicas_threescale.go:86: Replicas not Ready within timeout: Number of replicas for threescale replicas is not correct : Replicas - 1, Expected - 2 
```


@b1zzu Failing on the tests now, failures look likely to be related to the update. Will need further investigation.

**Pull request merged**
