### PR TITLE
J03 - Add note to comment out unnecessary tests

### PR DESCRIPTION
**Pull request by HubertStefanski**
# Description
Added a note to comment out unnecessary tests, speeding up the time taken to complete this test, as well as a minor note reminding about the need for manual 3scale namespace restoration.

### CODE REVIEW

**Comment by trepel** [comment]
@HubertStefanski could you please resolve the conflicts? Thanks

**Comment by HubertStefanski** [comment]
@trepel resolved conflicts, mind putting LGTM again?

**Pull request merged**
