### PR TITLE
Bump AMO to 1.7.0

### PR DESCRIPTION
**Pull request by carlkyrillos**
# Description
This bumps AMO to 1.7.0 in order to incorporate a bugfix in [this PR](https://github.com/integr8ly/application-monitoring-operator/pull/170) from AMO as required for [MGDAPI-2282](https://issues.redhat.com/browse/MGDAPI-2282).

JIRA: https://issues.redhat.com/browse/MGDAPI-2282

### CODE REVIEW

**Comment by carlkyrillos** [comment]
@matskiv Can you review this when you get a chance?

**Comment by matskiv** [comment]
/lgtm

We will need to merge the changes in AMO, run the AMO release pipeline and then I'd trigger rhoam-e2e tests here.

**Comment by carlkyrillos** [comment]
The v1.7.0 build is in Quay and the security check is green:

AMO-v1 7 0

**Pull request merged**
