### PR TITLE
MGDAPI-2526: Introduce polling for SA token

### PR DESCRIPTION
**Pull request by sergioifg94**
# Description

The test has failed ocassionally when retrieving the token that's created for a testing ServiceAccount. The reason of this is that the token is attempted to be retrieved immediately after the SA is created, which might result if the token not being created by the time that code is executed.
Fix by introducing polling which waits for the token secret to be set in the service account `secrets` list.

# Verification

* The E05 test passes

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by Boomatang** [comment]
To verify I check the logs in the prow e2e test runs for both rhoam and rhmi. The code looks good and nothing is jumping out at me.
As this was a bit of a flaky test proving this fixed the issue will be hard but over the next few week close attention will be give to this test in the pipeline watches.

/lgtm

**Comment by sergioifg94** [comment]
Sounds like a good approach, thanks @Boomatang

**Pull request merged**
