### PR TITLE
MGDAPI-1385 - update user SSO resources

### PR DESCRIPTION
**Pull request by matskiv**
# Description
JIRA: https://issues.redhat.com/browse/MGDAPI-1385
Updating User SSO resources based on our finding from perf tests.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Review by austincunningham — APPROVED** [review]
/lgtm
/approve

**Comment by matskiv** [comment]
Thanks for review guys!
I will hold off with merging a little bit. Pavel is testing one User SSO upgrade issue, and we want to test with master image, but without this change.

**Pull request merged**
