### PR TITLE
Intly 7469 RHMI uninstallation gets stuck (master branch)

### PR DESCRIPTION
**Pull request by Boomatang**
# Description

Fix issue of un-install not been completed.
**Jira** https://issues.redhat.com/browse/INTLY-7469

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by philbrookes** [comment]
looks like commit c4da50b5b196e135fd7ad95aab8403b72e47e1f8 got pulled into this branch somehow? Was that intentional?

**Comment by philbrookes** [comment]
/retest
throttling flake in prow

**Comment by Boomatang** [comment]
@philbrookes I have fixed that issue with bring in the extra commit to the PR.

**Pull request merged**
