### PR TITLE
INTLY-9043 - Add condition for ThreeScaleUIBBT prometheusRule

### PR DESCRIPTION
**Pull request by HubertStefanski**
# Description
Following on with the changes to prometheusRules done in https://issues.redhat.com/browse/INTLY-8459, to Fix the Alert query for Threescale UIBBT

## JIRA
https://issues.redhat.com/browse/INTLY-9043

## Verification
- After installation, scale down the 3scale system-app pod(s)
- Verify the ThreeScaleDeveloperUIBBT, ThreeScaleSystemAdminUIBBT & ThreeScaleAdminUIBBT alerts goes to pending (and eventually fire)

## Type of change

- [:heavy_check_mark: ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by obrienrobert** [comment]
Verified using the steps provided:
3scale_uibbt

/lgtm

**Comment by HubertStefanski** [comment]
@obrienrobert Thanks for verifying! :+1: , @david-martin mind approving?

**Pull request merged**
