### PR TITLE
Update 3scale test container to 2.9

### PR DESCRIPTION
**Pull request by b1zzu**
# Description

Update the 3sclae test container to `quay.io/integreatly/3scale-py-testsuite:2.9`

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

### CODE REVIEW

**Comment by b1zzu** [comment]
cc @mikenairn @wei-lee @merlante

**Comment by b1zzu** [comment]
@wei-lee I can't approve it on my own

**Comment by mikenairn** [comment]
@b1zzu Why are we updating master to the 2.9 test conatiner when it's still installing 2.8?

**Comment by b1zzu** [comment]
@mikenairn it's working also with the 2.8, or at least I tried against rhmi 2.4.0, I don't know why is called 2.9

**Comment by mikenairn** [comment]
@b1zzu OK, ideally it would have been 2.8, and we updated to 2.9 in this PR https://github.com/integr8ly/integreatly-operator/pull/944. I guess we're not quite there yet though

**Pull request merged**
